import LOEIS.A340.A340727.Defs

set_option linter.unusedVariables false

/-!
# A340727

a(n) is the smallest integer that can be written as a product of n distinct integers > 1 in at least two different ways.

The 20 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A340727

/-- Known terms of `A340727`, starting at index `2`. -/
def data : List retType :=
  [12, 48, 240, 1440, 8640, 60480, 604800, 5443200, 59875200, 718502400,
    9340531200, 124540416000, 1743565824000, 29640619008000, 502146957312000, 8536498274304000, 162193467211776000, 3406062811447296000, 68121256228945920000, 1498667637036810240000]

/-- `A340727` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 22) : A340727 n = data[n.val - 2]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 22) : fn n = data[n - 2]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 22) : fz n = data[n.toNat - 2]! := sorry

end A340727
