import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A207373

Numbers whose square is the product of a number and its reverse.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A207373

/-- Index type of `A207373` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A207373`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A207373

/-- Numbers whose square is the product of a number and its reverse. -/
def A207373 : A207373.argType → A207373.retType := sorry

namespace A207373

/-- Relation that defines `A207373`. -/
def prop : argType → retType → Prop := sorry

/-- `A207373` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A207373` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A207373 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A207373 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A207373 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A207373
