import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A359835

a(n) = 0 if A353418(n) = 0, otherwise 1. Here A353418 is Dirichlet inverse of the characteristic function for numbers k at which points A156552(k) is a multiple of 3.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A359835

/-- Index type of `A359835` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A359835`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A359835

/-- a(n) = 0 if A353418(n) = 0, otherwise 1. Here A353418 is Dirichlet inverse of the characteristic function for numbers k at which points A156552(k) is a multiple of 3. -/
def A359835 : A359835.argType → A359835.retType := sorry

namespace A359835

/-- Relation that defines `A359835`. -/
def prop : argType → retType → Prop := sorry

/-- `A359835` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A359835` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A359835 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A359835 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A359835 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A359835
