import LOEIS.A283.A283178.Defs

set_option linter.unusedVariables false

/-!
# A283178

Decimal representation of the x-axis, from the origin to the right edge, of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 590", based on the 5-celled von Neumann neighborhood.

The 34 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A283178

/-- Known terms of `A283178`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 7, 11, 19, 63, 87, 131, 395, 951,
    1327, 2507, 7667, 8959, 27927, 49475, 115915, 153591, 458863, 590155,
    2032883, 2432767, 8082711, 9841475, 32424139, 43009015, 97601647, 179763531, 274816243, 832974591,
    2004782359, 2230172483, 6967279819, 16347939831]

/-- `A283178` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 34) : A283178 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 34) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 34) : fz n = data[n.toNat]! := sorry

end A283178
