import LOEIS.A176.A176883.Defs

set_option linter.unusedVariables false

/-!
# A176883

Sum of distances of numbers between successive powers of 2 (beginning with 2^1) to previous numbers with same number of prime factors, repetitions included. See example.

The 30 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A176883

/-- Known terms of `A176883`, starting at index `1`. -/
def data : List retType :=
  [1, 6, 19, 55, 151, 359, 849, 1956, 4416, 9861,
    21776, 47659, 103501, 223362, 479527, 1024599, 2180237, 4622633, 9769597, 20587721,
    43272599, 90739538, 189867698, 396512548, 826579593, 1720267980, 3574753738, 7417943000, 15372756795, 31819255488]

/-- `A176883` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 31) : A176883 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 31) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 31) : fz n = data[n.toNat - 1]! := sorry

end A176883
