import LOEIS.A032.A032247.Defs

set_option linter.unusedVariables false

/-!
# A032247

"DHK[ 6 ]" (bracelet, identity, unlabeled, 6 parts) transform of 1,1,1,1,...

The 38 terms known to OEIS, indexed from `9`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A032247

/-- Known terms of `A032247`, starting at index `9`. -/
def data : List retType :=
  [3, 6, 16, 29, 56, 90, 150, 222, 336, 474,
    672, 908, 1233, 1612, 2112, 2693, 3432, 4282, 5340, 6542,
    8008, 9666, 11648, 13874, 16503, 19432, 22848, 26639, 31008, 35832,
    41346, 47400, 54264, 61776, 70224, 79434, 89733, 100914]

/-- `A032247` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 47) : A032247 n = data[n.val - 9]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 9 ≤ n) (h : n < 47) : fn n = data[n - 9]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 9 ≤ n) (h : n < 47) : fz n = data[n.toNat - 9]! := sorry

end A032247
