import LOEIS.A319.A319182.Defs

set_option linter.unusedVariables false

/-!
# A319182

Irregular triangle where T(n,k) is the number of set partitions of {1,...,n} with block-sizes given by the integer partition with Heinz number A215366(n,k).

The 67 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A319182

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 3, 1, 1, 3, 4, 6,
    1, 1, 5, 10, 15, 10, 10, 1, 1, 15,
    6, 10, 15, 15, 60, 45, 20, 15, 1, 1,
    7, 21, 35, 105, 21, 105, 70, 105, 35, 210,
    105, 35, 21, 1, 1, 8, 28, 35, 28, 56,
    210, 168, 280, 280, 105, 420, 56, 840, 280, 420,
    70, 560, 210, 56, 28, 1, 1]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 68) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 68) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 68) : flatFz n = flatData[n.toNat - 1]! := sorry

end A319182
