import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A100791

Group the natural numbers so that the n-th group contains n(n+1)/2 = T(n) terms: (1), (2,3,4), (5,6,7,8,9,10), (11,12,13,14,15,16,17,18,19,20),(21,22,23,24,25,26,27,28,29,30,31,32,33,34,35),... The n-th row of the following triangle is formed from the sum of first n terms, next n-1 terms,next n-2 terms ... of the n-th group; e.g. third row is (5+6+7), (8+9), (10) or 18,17,10. Sequence contains the triangle read by rows.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A100791

/-- Index type of `flat` (OEIS offset `1`). -/
abbrev flatArgType : Type := PNat

/-- Value type of `flat`. -/
abbrev flatRetType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev flatOffset : Int := 1

/-- Group the natural numbers so that the n-th group contains n(n+1)/2 = T(n) terms: (1), (2,3,4), (5,6,7,8,9,10), (11,12,13,14,15,16,17,18,19,20),(21,22,23,24,25,26,27,28,29,30,31,32,33,34,35),... The n-th row of the following triangle is formed from the sum of first n terms, next n-1 terms,next n-2 terms ... of the n-th group; e.g. third row is (5+6+7), (8+9), (10) or 18,17,10. Sequence contains the triangle read by rows. -/
def flat : flatArgType → flatRetType := sorry

end A100791

namespace A100791

/-- Relation that defines `flat`. -/
def flatProp : flatArgType → flatRetType → Prop := sorry

/-- `flat` as a total function on `Nat`; junk value outside the domain. -/
def flatFn : Nat → flatRetType := sorry

/-- `flat` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def flatFz : Int → flatRetType := sorry

/-- The main definition satisfies its defining relation. -/
theorem flat_prop_correct (n : flatArgType) : flatProp n (flat n) := sorry

/-- `flatFn` agrees with the main definition. -/
theorem flat_fn_eq (n : Nat) (h : 0 < n) : flatFn n = flat ⟨n, h⟩ := sorry

/-- `flatFz` agrees with the main definition on the domain. -/
theorem flat_fz_eq (n : Int) (h : 1 ≤ n) : flatFz n = flat ⟨n.toNat, by omega⟩ := sorry

/-- `flatFn` and `flatFz` agree on the overlapping domain. -/
theorem flat_fn_eq_fz (n : Nat) (h : 0 < n) : flatFn n = flatFz (n : Int) := sorry

end A100791
