import LOEIS.A035.A035045.Defs

set_option linter.unusedVariables false

/-!
# A035045

Inverse binomial transform of A002054.

The 29 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A035045

/-- Known terms of `A035045`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 12, 35, 101, 291, 839, 2423, 7011, 20326,
    59038, 171777, 500603, 1461032, 4269828, 12493857, 36599403, 107325540, 315027276, 925501857,
    2721208599, 8007114171, 23577440439, 69470880381, 204821487269, 604223501426, 1783419354954, 5266582196407, 15560042628205]

/-- `A035045` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 29) : A035045 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 29) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 29) : fz n = data[n.toNat]! := sorry

end A035045
