import LOEIS.A267.A267836.Defs

set_option linter.unusedVariables false

/-!
# A267836

T(n,k)=Number of nXk arrays containing k copies of 0..n-1 with every element equal to or 1 greater than any northeast neighbor modulo n and the upper left element equal to 0.

The 47 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A267836

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 3, 2, 1, 10, 11, 6,
    1, 35, 91, 54, 24, 1, 126, 829, 924, 330,
    120, 1, 462, 8013, 19696, 10924, 2430, 720, 1, 1716,
    80497, 456052, 499523, 147340, 20970, 5040, 1, 6435, 830673, 11169884,
    26266875, 13895954, 2247540, 207900, 40320, 1, 24310]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 48) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 48) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 48) : flatFz n = flatData[n.toNat - 1]! := sorry

end A267836
