import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A141393

a(n) is the smallest number, larger than the previous, such that the RMS (Root Mean Square) of a(0) through a(n) is an integer.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A141393

/-- Index type of `A141393` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A141393`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A141393

/-- a(n) is the smallest number, larger than the previous, such that the RMS (Root Mean Square) of a(0) through a(n) is an integer. -/
def A141393 : A141393.argType → A141393.retType := sorry

namespace A141393

/-- Relation that defines `A141393`. -/
def prop : argType → retType → Prop := sorry

/-- `A141393` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A141393` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A141393 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A141393 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A141393 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A141393
