import LOEIS.A261.A261955.Defs

set_option linter.unusedVariables false

/-!
# A261955

Start with a single equilateral triangle for n=0; for the odd n-th generation add a triangle at each expandable side of the triangles of the (n-1)-th generation (this is the "side to side" version); for the even n-th generation use the "vertex to side" version; a(n) is the number of triangles added in the n-th generation.

The 51 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A261955

/-- Known terms of `A261955`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 6, 15, 12, 24, 15, 33, 21, 45,
    39, 72, 36, 78, 39, 87, 45, 99, 63, 126,
    60, 132, 63, 141, 69, 153, 87, 180, 84, 186,
    87, 195, 93, 207, 111, 234, 108, 240, 111, 249,
    117, 261, 135, 288, 132, 294, 135, 303, 141, 315,
    159]

/-- `A261955` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 51) : A261955 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 51) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 51) : fz n = data[n.toNat]! := sorry

end A261955
