import LOEIS.A354.A354598.Defs

set_option linter.unusedVariables false

/-!
# A354598

Maximal GCD of eight positive integers with sum n.

The 93 terms known to OEIS, indexed from `8`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A354598

/-- Known terms of `A354598`, starting at index `8`. -/
def data : List retType :=
  [1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
    2, 1, 2, 1, 2, 1, 3, 1, 2, 3,
    2, 1, 3, 1, 4, 3, 2, 1, 4, 1,
    2, 3, 5, 1, 3, 1, 4, 5, 2, 1,
    6, 1, 5, 3, 4, 1, 6, 5, 7, 3,
    2, 1, 6, 1, 2, 7, 8, 5, 6, 1,
    4, 3, 7, 1, 9, 1, 2, 5, 4, 7,
    6, 1, 10, 9, 2, 1, 7, 5, 2, 3,
    11, 1, 10, 7, 4, 3, 2, 5, 12, 1,
    7, 11, 10]

/-- `A354598` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 101) : A354598 n = data[n.val - 8]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 8 ≤ n) (h : n < 101) : fn n = data[n - 8]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 8 ≤ n) (h : n < 101) : fz n = data[n.toNat - 8]! := sorry

end A354598
