import LOEIS.A080.A080299.Defs

set_option linter.unusedVariables false

/-!
# A080299

A014486-encoding of plane binary trees (Stanley's d) whose interior zigzag-tree (Stanley's c, i.e., tree obtained by discarding the outermost edges of the binary tree) is isomorphic to a valid plane binary tree (Stanley's d).

The 31 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A080299

/-- Known terms of `A080299`, starting at index `0`. -/
def data : List retType :=
  [2, 50, 818, 914, 13106, 13202, 14642, 14738, 15506, 209714,
    209810, 211250, 211346, 212114, 234290, 234386, 235826, 235922, 236690, 248114,
    248210, 248978, 255122, 3355442, 3355538, 3356978, 3357074, 3357842, 3380018, 3380114,
    3381554]

/-- `A080299` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 31) : A080299 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 31) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 31) : fz n = data[n.toNat]! := sorry

end A080299
