import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A233007

Numbers k such that (k-1)^2 + k^2 + (k+1)^2 is a palindrome.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A233007

/-- Index type of `A233007` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A233007`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A233007

/-- Numbers k such that (k-1)^2 + k^2 + (k+1)^2 is a palindrome. -/
def A233007 : A233007.argType → A233007.retType := sorry

namespace A233007

/-- Relation that defines `A233007`. -/
def prop : argType → retType → Prop := sorry

/-- `A233007` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A233007` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A233007 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A233007 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A233007 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A233007
