import LOEIS.A235.A235253.Defs

set_option linter.unusedVariables false

/-!
# A235253

Number of (n+1) X (3+1) 0..7 arrays with every 2 X 2 subblock having its diagonal sum differing from its antidiagonal sum by 7, with no adjacent elements equal (constant-stress tilted 1 X 1 tilings).

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A235253

/-- Known terms of `A235253`, starting at index `1`. -/
def data : List retType :=
  [2672, 8328, 24232, 80812, 251656, 878988, 2873128, 10362212, 35132248, 129681452,
    452445096, 1699526196, 6067071432, 23102391980, 84025709016, 323468947012, 1194691128744, 4640522916700, 17359355152040, 67935545177540]

/-- `A235253` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 21) : A235253 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : fz n = data[n.toNat - 1]! := sorry

end A235253
