import LOEIS.A163.A163283.Defs

set_option linter.unusedVariables false

/-!
# A163283

Triangle read by rows in which row n lists n+1 terms, starting with n^3 and ending with n^4, such that the difference between successive terms is equal to n^3 - n^2.

The 51 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A163283

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [0, 1, 1, 8, 12, 16, 27, 45, 63, 81,
    64, 112, 160, 208, 256, 125, 225, 325, 425, 525,
    625, 216, 396, 576, 756, 936, 1116, 1296, 343, 637,
    931, 1225, 1519, 1813, 2107, 2401, 512, 960, 1408, 1856,
    2304, 2752, 3200, 3648, 4096, 729, 1377, 2025, 2673, 3321,
    3969]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 51) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 51) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 51) : flatFz n = flatData[n.toNat]! := sorry

end A163283
