import LOEIS.A316.A316005.Defs

set_option linter.unusedVariables false

/-!
# A316005

Coordination sequence Gal.5.75.5 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A316005

/-- Known terms of `A316005`, starting at index `0`. -/
def data : List retType :=
  [1, 6, 9, 14, 20, 24, 28, 31, 36, 44,
    50, 47, 56, 62, 68, 72, 71, 80, 86, 94,
    87, 98, 104, 110, 116, 111, 124, 130, 136, 127,
    142, 146, 152, 158, 151, 168, 174, 180, 165, 186,
    190, 194, 200, 189, 212, 218, 224, 205, 228, 234]

/-- `A316005` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A316005 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A316005
