import LOEIS.A060.A060570.Defs

set_option linter.unusedVariables false

/-!
# A060570

Number of flips between the d-dimensional tilings of the unary zonotope Z(D,d). Here d=2 and D varies.

The 6 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A060570

/-- Known terms of `A060570`, starting at index `2`. -/
def data : List retType :=
  [0, 1, 8, 100, 2144, 80360]

/-- `A060570` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 8) : A060570 n = data[n.val - 2]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 8) : fn n = data[n - 2]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 8) : fz n = data[n.toNat - 2]! := sorry

end A060570
