import LOEIS.A332.A332925.Defs

set_option linter.unusedVariables false

/-!
# A332925

6*a(n) are the perimeters of distinct triangles with integer sides i <= j <= k, whose area equals 5 times their perimeter. Terms occurring more than once belong to different triangles.

The 52 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A332925

/-- Known terms of `A332925`, starting at index `1`. -/
def data : List retType :=
  [18, 20, 21, 22, 22, 25, 27, 28, 28, 30,
    31, 35, 36, 44, 46, 50, 52, 53, 58, 68,
    68, 69, 76, 77, 77, 84, 86, 99, 105, 108,
    124, 134, 145, 151, 154, 182, 182, 209, 210, 242,
    252, 260, 266, 391, 407, 468, 629, 742, 901, 910,
    1751, 3434]

/-- `A332925` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 53) : A332925 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 53) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 53) : fz n = data[n.toNat - 1]! := sorry

end A332925
