import LOEIS.A202.A202120.Defs

set_option linter.unusedVariables false

/-!
# A202120

Number of -4..4 arrays of n elements with first, second and third differences also in -4..4.

The 22 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A202120

/-- Known terms of `A202120`, starting at index `1`. -/
def data : List retType :=
  [9, 61, 323, 1279, 5205, 21093, 85771, 348841, 1418711, 5769945,
    23467095, 95443593, 388180467, 1578775913, 6421070989, 26115267153, 106213924727, 431984776463, 1756933935339, 7145661191995,
    29062261695493, 118199706395781]

/-- `A202120` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 23) : A202120 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 23) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 23) : fz n = data[n.toNat - 1]! := sorry

end A202120
