import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A369731

Number of solutions to +- 1^3 +- 2^3 +- 3^3 +- ... +- n^3 = 1.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A369731

/-- Index type of `A369731` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A369731`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A369731

/-- Number of solutions to +- 1^3 +- 2^3 +- 3^3 +- ... +- n^3 = 1. -/
def A369731 : A369731.argType → A369731.retType := sorry

namespace A369731

/-- Relation that defines `A369731`. -/
def prop : argType → retType → Prop := sorry

/-- `A369731` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A369731` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A369731 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A369731 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A369731 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A369731
