import LOEIS.A366.A366896.Defs

set_option linter.unusedVariables false

/-!
# A366896

a(n) is the least positive integer not already in the sequence with the property that the concatenation a(0)a(1)...a(n) forms an integer with n distinct prime factors.

The 19 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A366896

/-- Known terms of `A366896`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 4, 2, 11, 21, 30, 216, 118, 170,
    1092, 8484, 97104, 96720, 493170, 251496, 1380652, 12137510, 113661933]

/-- `A366896` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 19) : A366896 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 19) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 19) : fz n = data[n.toNat]! := sorry

end A366896
