import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A289023

Position in the sequence of numbers that are not perfect powers (A007916) of the smallest positive integer x such that for some positive integer y we have n = x^y (A052410).

OEIS offset `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A289023

/-- Index type of `A289023` (OEIS offset `2`). -/
abbrev argType : Type := {n : Nat // 2 ≤ n}

/-- Value type of `A289023`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 2

end A289023

/-- Position in the sequence of numbers that are not perfect powers (A007916) of the smallest positive integer x such that for some positive integer y we have n = x^y (A052410). -/
def A289023 : A289023.argType → A289023.retType := sorry

namespace A289023

/-- Relation that defines `A289023`. -/
def prop : argType → retType → Prop := sorry

/-- `A289023` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A289023` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A289023 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 2 ≤ n) : fn n = A289023 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 2 ≤ n) : fz n = A289023 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 2 ≤ n) : fn n = fz (n : Int) := sorry

end A289023
