import LOEIS.A218.A218254.Defs

set_option linter.unusedVariables false

/-!
# A218254

Irregular table, where row n (n >= 0) starts with n, the next term is n-A000120(n), and the successive terms are obtained by repeatedly subtracting the number of 1's in the previous term's binary expansion, until zero is reached, after which the next row starts with one larger n.

The 85 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A218254

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [0, 1, 0, 2, 1, 0, 3, 1, 0, 4,
    3, 1, 0, 5, 3, 1, 0, 6, 4, 3,
    1, 0, 7, 4, 3, 1, 0, 8, 7, 4,
    3, 1, 0, 9, 7, 4, 3, 1, 0, 10,
    8, 7, 4, 3, 1, 0, 11, 8, 7, 4,
    3, 1, 0, 12, 10, 8, 7, 4, 3, 1,
    0, 13, 10, 8, 7, 4, 3, 1, 0, 14,
    11, 8, 7, 4, 3, 1, 0, 15, 11, 8,
    7, 4, 3, 1, 0]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 85) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 85) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 85) : flatFz n = flatData[n.toNat]! := sorry

end A218254
