import LOEIS.A343.A343251.Defs

set_option linter.unusedVariables false

/-!
# A343251

a(n) is the least k0 <= n such that v_5(n), the 5-adic order of n, can be obtained by the formula: v_5(n) = log_5(n / L_5(k0, n)), where L_5(k0, n) is the lowest common denominator of the elements of the set S_5(k0, n) = {(1/n)*binomial(n, k), with 0 < k <= k0 such that k is not divisible by 5} or 0 if no such k0 exists.

The 80 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A343251

/-- Known terms of `A343251`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 3, 4, 1, 3, 7, 8, 9, 2,
    11, 4, 13, 7, 3, 16, 17, 9, 19, 4,
    7, 11, 23, 8, 1, 13, 27, 7, 29, 3,
    31, 32, 11, 17, 7, 9, 37, 19, 13, 8,
    41, 7, 43, 11, 9, 23, 47, 16, 49, 2,
    17, 13, 53, 27, 11, 8, 19, 29, 59, 4,
    61, 31, 9, 64, 13, 11, 67, 17, 23, 7,
    71, 9, 73, 37, 3, 19, 11, 13, 79, 16]

/-- `A343251` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 81) : A343251 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 81) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 81) : fz n = data[n.toNat - 1]! := sorry

end A343251
