import LOEIS.A385.A385188.Defs

set_option linter.unusedVariables false

/-!
# A385188

Primes p == 3 (mod 4) such that the multiplicative order of 2+-i modulo p in Gaussian integers (A385165) is not divisible by 2 or 3.

The 43 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A385188

/-- Known terms of `A385188`, starting at index `1`. -/
def data : List retType :=
  [599, 691, 1291, 1451, 2411, 3851, 4919, 5051, 5479, 5531,
    5879, 6599, 7079, 7691, 8011, 8039, 11491, 13291, 14011, 15091,
    15971, 16651, 17359, 18731, 19211, 19531, 20731, 22651, 23971, 24611,
    25639, 25679, 26251, 32051, 32359, 32531, 32771, 32971, 35879, 37039,
    37571, 38011, 38371]

/-- `A385188` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 44) : A385188 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 44) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 44) : fz n = data[n.toNat - 1]! := sorry

end A385188
