import LOEIS.A337.A337262.Defs

set_option linter.unusedVariables false

/-!
# A337262

A328078(2*n+1).

The 21 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A337262

/-- Known terms of `A337262`, starting at index `0`. -/
def data : List retType :=
  [2, 5, 15, 48, 169, 618, 2319, 8804, 33649, 129046,
    495779, 1906520, 7335029, 28227578, 108642983, 418176700, 1609656953, 6196050718, 23850681323, 91809753632,
    353409321213]

/-- `A337262` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 21) : A337262 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 21) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 21) : fz n = data[n.toNat]! := sorry

end A337262
