import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A004003

Number of domino tilings (or dimer coverings) of a 2n X 2n square.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A004003

/-- Index type of `A004003` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A004003`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A004003

/-- Number of domino tilings (or dimer coverings) of a 2n X 2n square. -/
def A004003 : A004003.argType → A004003.retType := sorry

namespace A004003

/-- Relation that defines `A004003`. -/
def prop : argType → retType → Prop := sorry

/-- `A004003` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A004003` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A004003 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A004003 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A004003 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A004003
