import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A066470

Numbers having exactly five anti-divisors.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A066470

/-- Index type of `A066470` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A066470`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A066470

/-- Numbers having exactly five anti-divisors. -/
def A066470 : A066470.argType → A066470.retType := sorry

namespace A066470

/-- Relation that defines `A066470`. -/
def prop : argType → retType → Prop := sorry

/-- `A066470` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A066470` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A066470 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A066470 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A066470 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A066470
