import LOEIS.A286.A286438.Defs

set_option linter.unusedVariables false

/-!
# A286438

Number of ways to tile an n X n X n triangular area with three 2 X 2 X 2 triangular tiles and an appropriate number (= n^2-12) of 1 X 1 X 1 tiles.

The 32 terms known to OEIS, indexed from `3`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A286438

/-- Known terms of `A286438`, starting at index `3`. -/
def data : List retType :=
  [0, 4, 63, 494, 2247, 7396, 19739, 45518, 94259, 179732,
    321031, 543774, 881423, 1376724, 2083267, 3067166, 4408859, 6205028, 8570639, 11641102,
    15574551, 20554244, 26791083, 34526254, 44033987, 55624436, 69646679, 86491838, 106596319, 130445172,
    158575571, 191580414]

/-- `A286438` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 35) : A286438 n = data[n.val - 3]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 3 ≤ n) (h : n < 35) : fn n = data[n - 3]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 3 ≤ n) (h : n < 35) : fz n = data[n.toNat - 3]! := sorry

end A286438
