import LOEIS.A253.A253742.Defs

set_option linter.unusedVariables false

/-!
# A253742

Number of (n+1) X (1+1) 0..2 arrays with every 2 X 2 subblock ne-sw antidiagonal difference nondecreasing horizontally and nw+se diagonal sum nondecreasing vertically.

The 22 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A253742

/-- Known terms of `A253742`, starting at index `1`. -/
def data : List retType :=
  [81, 450, 1998, 7803, 28107, 95940, 315576, 1011357, 3181653, 9876870,
    30368034, 92726271, 281717919, 852821640, 2574980172, 7760330145, 23356488105, 70229896650, 211029428790, 633805512579,
    1902926487411, 5711950356300]

/-- `A253742` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 23) : A253742 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 23) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 23) : fz n = data[n.toNat - 1]! := sorry

end A253742
