import LOEIS.A220.A220314.Defs

set_option linter.unusedVariables false

/-!
# A220314

binomial(2n,n) - (2n)^pi(n), where pi(n) is the number of primes <= n.

The 24 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A220314

/-- Known terms of `A220314`, starting at index `1`. -/
def data : List retType :=
  [1, 2, -16, 6, -748, -804, -34984, -52666, -56356, 24756,
    -4448200, -5258468, -298515176, -441773704, -573882480, -472661434, -50189743924, -69289028796, -4312446874696, -6415753471180,
    -9144394121976, -11944124661496, -913956731941456, -1320357856911588]

/-- `A220314` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 25) : A220314 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 25) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 25) : fz n = data[n.toNat - 1]! := sorry

end A220314
