import LOEIS.A167.A167762.Defs

set_option linter.unusedVariables false

/-!
# A167762

a(n) = 2*a(n-1)+3*a(n-2)-6*a(n-3) starting a(0)=a(1)=0, a(2)=1.

The 34 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A167762

/-- Known terms of `A167762`, starting at index `0`. -/
def data : List retType :=
  [0, 0, 1, 2, 7, 14, 37, 74, 175, 350,
    781, 1562, 3367, 6734, 14197, 28394, 58975, 117950, 242461, 484922,
    989527, 1979054, 4017157, 8034314, 16245775, 32491550, 65514541, 131029082, 263652487, 527304974,
    1059392917, 2118785834, 4251920575, 8503841150]

/-- `A167762` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 34) : A167762 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 34) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 34) : fz n = data[n.toNat]! := sorry

end A167762
