import LOEIS.A339.A339344.Defs

set_option linter.unusedVariables false

/-!
# A339344

Lexicographically earliest sequence of odd primes such that the asymptotic density of the numbers which are divisible by at least one of these primes is 1/2.

The 9 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A339344

/-- Known terms of `A339344`, starting at index `1`. -/
def data : List retType :=
  [3, 5, 17, 257, 65537, 4294967311, 1229782942255939601, 88962710886098567818446141338419231, 255302062200114858892457591448999891874349780170241684791167583265041]

/-- `A339344` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 10) : A339344 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 10) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 10) : fz n = data[n.toNat - 1]! := sorry

end A339344
