import LOEIS.A149.A149114.Defs

set_option linter.unusedVariables false

/-!
# A149114

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 0), (-1, 1, -1), (1, 0, -1), (1, 1, 1)}.

The 30 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A149114

/-- Known terms of `A149114`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 4, 9, 30, 90, 308, 963, 3438, 11234,
    40152, 135794, 490832, 1683168, 6124726, 21354425, 78003828, 274576966, 1008967842, 3580440440,
    13189340250, 47178798464, 174283519352, 626647788638, 2320640184718, 8387827155210, 31116693592454, 112928607749642, 419803477131832, 1528896400255678]

/-- `A149114` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 30) : A149114 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 30) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 30) : fz n = data[n.toNat]! := sorry

end A149114
