import LOEIS.A250.A250941.Defs

set_option linter.unusedVariables false

/-!
# A250941

Number of (n+1)X(7+1) 0..2 arrays with nondecreasing x(i,j)+x(i,j-1) in the i direction and nondecreasing absolute value of x(i,j)-x(i-1,j) in the j direction.

The 16 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A250941

/-- Known terms of `A250941`, starting at index `1`. -/
def data : List retType :=
  [103093, 1188599, 9865706, 72722706, 475951361, 2839711239, 15686582837, 81197881457, 397409857238, 1852256126330,
    8268389261288, 35518343223640, 147408746536971, 593071701754583, 2319960593452318, 8846272931682598]

/-- `A250941` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A250941 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 17) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 17) : fz n = data[n.toNat - 1]! := sorry

end A250941
