import LOEIS.A116.A116550.Defs

set_option linter.unusedVariables false

/-!
# A116550

The bi-unitary analog of Euler's totient function of n.

The 74 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A116550

/-- Known terms of `A116550`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 2, 3, 4, 3, 6, 7, 8, 6,
    10, 8, 12, 9, 9, 15, 16, 12, 18, 14,
    14, 15, 22, 17, 24, 18, 26, 21, 28, 15,
    30, 31, 23, 24, 25, 29, 36, 27, 28, 31,
    40, 21, 42, 35, 34, 33, 46, 36, 48, 36,
    37, 42, 52, 39, 42, 46, 42, 42, 58, 34,
    60, 45, 51, 63, 50, 35, 66, 56, 51, 38,
    70, 62, 72, 54]

/-- `A116550` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 75) : A116550 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 75) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 75) : fz n = data[n.toNat - 1]! := sorry

end A116550
