import LOEIS.A272.A272317.Defs

set_option linter.unusedVariables false

/-!
# A272317

First differences of number of active (ON, black) cells in n-th stage of growth of two-dimensional cellular automaton defined by "Rule 465", based on the 5-celled von Neumann neighborhood.

The 45 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A272317

/-- Known terms of `A272317`, starting at index `0`. -/
def data : List retType :=
  [3, 5, 19, -3, 59, -35, 91, -51, 171, -147,
    267, -219, 371, -299, 387, -275, 523, -499, 747, -699,
    979, -907, 1123, -1003, 1347, -1275, 1555, -1411, 1723, -1507,
    1563, -1235, 1739, -1715, 2219, -2171, 2707, -2635, 3107, -2987,
    3587, -3515, 4051, -3907, 4475]

/-- `A272317` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 45) : A272317 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 45) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 45) : fz n = data[n.toNat]! := sorry

end A272317
