import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A364314

Number of polynomials (with nonnegative coefficients) of Cantor's height n and degree k (in the range {1, 2, ..., n-1}), for n >= 2; and for n = 1 the degree is k = 1.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A364314

/-- Index type of `A364314` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A364314`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A364314

/-- Number of polynomials (with nonnegative coefficients) of Cantor's height n and degree k (in the range {1, 2, ..., n-1}), for n >= 2; and for n = 1 the degree is k = 1. -/
def A364314 : A364314.argType → A364314.retType := sorry

namespace A364314

/-- Relation that defines `A364314`. -/
def prop : argType → retType → Prop := sorry

/-- `A364314` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A364314` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A364314 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A364314 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A364314 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A364314
