import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A013950

Start with 1, apply 1->12, 21->21, 22->21, 2->2 (for final 2); a(n) = length of n-th term.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A013950

/-- Index type of `A013950` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A013950`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A013950

/-- Start with 1, apply 1->12, 21->21, 22->21, 2->2 (for final 2); a(n) = length of n-th term. -/
def A013950 : A013950.argType → A013950.retType := sorry

namespace A013950

/-- Relation that defines `A013950`. -/
def prop : argType → retType → Prop := sorry

/-- `A013950` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A013950` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A013950 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A013950 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A013950 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A013950
