import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A063642

Primes of form p*q*r + 2, where p, q and r are primes (not necessarily distinct).

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A063642

/-- Index type of `A063642` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A063642`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A063642

/-- Primes of form p*q*r + 2, where p, q and r are primes (not necessarily distinct). -/
def A063642 : A063642.argType → A063642.retType := sorry

namespace A063642

/-- Relation that defines `A063642`. -/
def prop : argType → retType → Prop := sorry

/-- `A063642` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A063642` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A063642 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A063642 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A063642 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A063642
