import LOEIS.A354.A354280.Defs

set_option linter.unusedVariables false

/-!
# A354280

a(n) is the numerator of Cesàro means sequence c(n) of A237420 when the denominator is A141310(n).

The 69 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A354280

/-- Known terms of `A354280`, starting at index `0`. -/
def data : List retType :=
  [0, 0, 2, 1, 6, 2, 12, 3, 20, 4,
    30, 5, 42, 6, 56, 7, 72, 8, 90, 9,
    110, 10, 132, 11, 156, 12, 182, 13, 210, 14,
    240, 15, 272, 16, 306, 17, 342, 18, 380, 19,
    420, 20, 462, 21, 506, 22, 552, 23, 600, 24,
    650, 25, 702, 26, 756, 27, 812, 28, 870, 29,
    930, 30, 992, 31, 1056, 32, 1122, 33, 1190]

/-- `A354280` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 69) : A354280 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 69) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 69) : fz n = data[n.toNat]! := sorry

end A354280
