import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A216490

G.f. satisfies A(x) = 1 + x*A(x)^2 + x^3*A(x)^5.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A216490

/-- Index type of `A216490` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A216490`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A216490

/-- G.f. satisfies A(x) = 1 + x*A(x)^2 + x^3*A(x)^5. -/
def A216490 : A216490.argType → A216490.retType := sorry

namespace A216490

/-- Relation that defines `A216490`. -/
def prop : argType → retType → Prop := sorry

/-- `A216490` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A216490` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A216490 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A216490 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A216490 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A216490
