import LOEIS.A084.A084718.Defs

set_option linter.unusedVariables false

/-!
# A084718

a(n) = A084717(n+1)/A084717(n).

The 71 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A084718

/-- Known terms of `A084718`, starting at index `1`. -/
def data : List retType :=
  [2, 2, 2, 2, 4, 2, 3, 6, 4, 5,
    5, 5, 10, 4, 3, 5, 8, 22, 13, 14,
    2, 5, 5, 2, 20, 9, 9, 24, 5, 26,
    15, 14, 25, 25, 4, 9, 30, 9, 21, 12,
    11, 10, 2, 40, 19, 8, 13, 11, 50, 3,
    25, 25, 8, 5, 25, 46, 19, 47, 54, 9,
    13, 14, 43, 4, 24, 28, 16, 33, 25, 152,
    2]

/-- `A084718` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 72) : A084718 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 72) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 72) : fz n = data[n.toNat - 1]! := sorry

end A084718
