import LOEIS.A332.A332597.Defs

set_option linter.unusedVariables false

/-!
# A332597

Number of edges in a "frame" of size n X n (see Comments in A331776 for definition).

The 41 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A332597

/-- Known terms of `A332597`, starting at index `1`. -/
def data : List retType :=
  [8, 92, 360, 860, 1792, 3124, 5256, 8188, 12304, 17460,
    24568, 33244, 44688, 58228, 74664, 94028, 118080, 145380, 178568, 216252,
    259776, 308276, 365352, 428556, 501152, 580804, 670536, 768908, 880992, 1001764,
    1138248, 1286748, 1449984, 1625300, 1817752, 2023740, 2252048, 2495476, 2759304, 3040460,
    3349056]

/-- `A332597` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 42) : A332597 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 42) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 42) : fz n = data[n.toNat - 1]! := sorry

end A332597
