import LOEIS.A103.A103276.Defs

set_option linter.unusedVariables false

/-!
# A103276

a(n) = (prime(n+1) + prime(k))/prime(n), where k is the smallest number such that prime(n+1) + prime(k)==0 mod prime(n), n+1 < k.

The 80 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A103276

/-- Known terms of `A103276`, starting at index `1`. -/
def data : List retType :=
  [4, 4, 4, 4, 4, 6, 6, 4, 6, 12,
    6, 4, 10, 6, 6, 12, 6, 8, 4, 4,
    6, 4, 6, 12, 12, 6, 12, 24, 6, 12,
    6, 8, 4, 22, 6, 8, 8, 6, 6, 6,
    10, 10, 4, 10, 6, 6, 12, 10, 30, 4,
    12, 6, 22, 6, 6, 12, 12, 14, 4, 12,
    4, 6, 6, 6, 16, 4, 8, 10, 4, 6,
    6, 4, 20, 24, 10, 14, 12, 4, 6, 4]

/-- `A103276` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 81) : A103276 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 81) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 81) : fz n = data[n.toNat - 1]! := sorry

end A103276
