import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A005397

Number of n-step polygons on Kagome lattice.

OEIS offset `3`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A005397

/-- Index type of `A005397` (OEIS offset `3`). -/
abbrev argType : Type := {n : Nat // 3 ≤ n}

/-- Value type of `A005397`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 3

end A005397

/-- Number of n-step polygons on Kagome lattice. -/
def A005397 : A005397.argType → A005397.retType := sorry

namespace A005397

/-- Relation that defines `A005397`. -/
def prop : argType → retType → Prop := sorry

/-- `A005397` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A005397` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A005397 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 3 ≤ n) : fn n = A005397 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 3 ≤ n) : fz n = A005397 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 3 ≤ n) : fn n = fz (n : Int) := sorry

end A005397
