import LOEIS.A229.A229518.Defs

set_option linter.unusedVariables false

/-!
# A229518

Number of n X 5 0..2 arrays of the median of the corresponding element, the element to the east and the element to the south in a larger (n+1) X 6 0..2 array without adjacent equal elements in the latter.

The 16 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A229518

/-- Known terms of `A229518`, starting at index `1`. -/
def data : List retType :=
  [91, 1751, 23059, 275243, 3336437, 39543877, 476435051, 5674074209, 68219097971, 814769931161,
    9781725263921, 116995909271027, 1403306980742023, 16797171022505615, 201366600573393261, 2411277822466400339]

/-- `A229518` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A229518 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 17) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 17) : fz n = data[n.toNat - 1]! := sorry

end A229518
