import LOEIS.A282.A282105.Defs

set_option linter.unusedVariables false

/-!
# A282105

Decimal representation of the x-axis, from the left edge to the origin, of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 427", based on the 5-celled von Neumann neighborhood.

The 34 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A282105

/-- Known terms of `A282105`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 7, 4, 29, 23, 124, 69, 471, 380,
    1989, 1111, 7548, 6085, 31831, 17788, 120773, 97367, 509308, 284613,
    1932375, 1557884, 8148933, 4553815, 30918012, 24926149, 130382935, 72861052, 494688197, 398818391,
    2086126972, 1165776837, 7915011159, 6381094268]

/-- `A282105` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 34) : A282105 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 34) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 34) : fz n = data[n.toNat]! := sorry

end A282105
