import LOEIS.A332.A332035.Defs

set_option linter.unusedVariables false

/-!
# A332035

Indices of A004394(n) in A055932.

The 53 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A332035

/-- Known terms of `A332035`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 3, 4, 6, 9, 12, 13, 15, 21,
    26, 30, 36, 49, 53, 63, 72, 86, 114, 149,
    175, 212, 221, 285, 367, 424, 505, 541, 643, 687,
    703, 886, 1015, 1198, 1272, 1496, 1586, 1704, 2116, 2491,
    2912, 3076, 3587, 3791, 4052, 4971, 5999, 6087, 6845, 6955,
    7330, 8481, 8933]

/-- `A332035` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 54) : A332035 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 54) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 54) : fz n = data[n.toNat - 1]! := sorry

end A332035
