import LOEIS.A027.A027950.Defs

set_option linter.unusedVariables false

/-!
# A027950

a(n) = T(2n,n+2), T given by A027948.

The 26 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A027950

/-- Known terms of `A027950`, starting at index `2`. -/
def data : List retType :=
  [1, 6, 63, 344, 1383, 4685, 14323, 41119, 113590, 306605,
    816410, 2157046, 5674578, 14893364, 39040633, 102273950, 267839033, 701315739, 1836198205, 4807389285,
    12586103720, 32951083211, 86267338468, 225851160284, 591286410708, 1548008385490]

/-- `A027950` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 28) : A027950 n = data[n.val - 2]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 28) : fn n = data[n - 2]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 28) : fz n = data[n.toNat - 2]! := sorry

end A027950
