import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A129038

Number of n-node triangulations of the triple torus S_3 in which every node has degree >= 3.

OEIS offset `9`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A129038

/-- Index type of `A129038` (OEIS offset `9`). -/
abbrev argType : Type := {n : Nat // 9 ≤ n}

/-- Value type of `A129038`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 9

end A129038

/-- Number of n-node triangulations of the triple torus S_3 in which every node has degree >= 3. -/
def A129038 : A129038.argType → A129038.retType := sorry

namespace A129038

/-- Relation that defines `A129038`. -/
def prop : argType → retType → Prop := sorry

/-- `A129038` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A129038` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A129038 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 9 ≤ n) : fn n = A129038 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 9 ≤ n) : fz n = A129038 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 9 ≤ n) : fn n = fz (n : Int) := sorry

end A129038
