import LOEIS.A377.A377220.Defs

set_option linter.unusedVariables false

/-!
# A377220

Expansion of (1/x) * series_reversion(x*E_4(x)), where E_4(x) denotes the Eisenstein series of weight 4 (see A004009).

The 14 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A377220

/-- Known terms of `A377220`, starting at index `0`. -/
def data : List retType :=
  [1, -240, 113040, -66534720, 43859560080, -30976854078240, 22919806575299520, -17536455012714130560, 13761543459443537811600, -11015192093055645841813680,
    8958361831335008460574345440, -7381454927286057227098811282880, 6148958599311807793865548969813440, -5169975617288319668409172392988655520]

/-- `A377220` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 14) : A377220 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 14) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 14) : fz n = data[n.toNat]! := sorry

end A377220
