import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A173205

a(n) = 98*a(n-1)-a(n-2) for n>2, a(1)=1, a(2)=98.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A173205

/-- Index type of `A173205` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A173205`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A173205

/-- a(n) = 98*a(n-1)-a(n-2) for n>2, a(1)=1, a(2)=98. -/
def A173205 : A173205.argType → A173205.retType := sorry

namespace A173205

/-- Relation that defines `A173205`. -/
def prop : argType → retType → Prop := sorry

/-- `A173205` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A173205` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A173205 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A173205 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A173205 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A173205
