import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A292808

G.f.: Sum_{n>=1} Sum_{k=0..n} binomial(n,k) * x^(k^2) * (x^n - x^k)^(n-k), ignoring the constant term.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A292808

/-- Index type of `A292808` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A292808`. -/
abbrev retType : Type := Int

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A292808

/-- G.f.: Sum_{n>=1} Sum_{k=0..n} binomial(n,k) * x^(k^2) * (x^n - x^k)^(n-k), ignoring the constant term. -/
def A292808 : A292808.argType → A292808.retType := sorry

namespace A292808

/-- Relation that defines `A292808`. -/
def prop : argType → retType → Prop := sorry

/-- `A292808` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A292808` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A292808 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A292808 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A292808 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A292808
