import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A034333

Number of matroids: column 3 of A034328.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A034333

/-- Index type of `A034333` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A034333`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A034333

/-- Number of matroids: column 3 of A034328. -/
def A034333 : A034333.argType → A034333.retType := sorry

namespace A034333

/-- Relation that defines `A034333`. -/
def prop : argType → retType → Prop := sorry

/-- `A034333` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A034333` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A034333 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A034333 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A034333 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A034333
