import LOEIS.A226.A226123.Defs

set_option linter.unusedVariables false

/-!
# A226123

Number of terms of the form 2^k in Collatz(3x+1) trajectory of n.

The 87 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A226123

/-- Known terms of `A226123`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 5, 3, 5, 5, 5, 4, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    7, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 6, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 7, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 7, 5, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 9, 5, 5, 5, 5, 5,
    5, 5, 5, 7, 9, 5, 5]

/-- `A226123` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 88) : A226123 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 88) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 88) : fz n = data[n.toNat - 1]! := sorry

end A226123
