import LOEIS.A371.A371400.Defs

set_option linter.unusedVariables false

/-!
# A371400

Triangle read by rows: T(n, k) = binomial(k + n, k)*binomial(2*n - k, n).

The 45 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A371400

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 2, 2, 6, 9, 6, 20, 40, 40, 20,
    70, 175, 225, 175, 70, 252, 756, 1176, 1176, 756,
    252, 924, 3234, 5880, 7056, 5880, 3234, 924, 3432, 13728,
    28512, 39600, 39600, 28512, 13728, 3432, 12870, 57915, 135135, 212355,
    245025, 212355, 135135, 57915, 12870]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 45) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 45) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 45) : flatFz n = flatData[n.toNat]! := sorry

end A371400
