import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A354602

a(n) is the number of trivial braids on 3 strands with 2*n crossings.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A354602

/-- Index type of `A354602` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A354602`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A354602

/-- a(n) is the number of trivial braids on 3 strands with 2*n crossings. -/
def A354602 : A354602.argType → A354602.retType := sorry

namespace A354602

/-- Relation that defines `A354602`. -/
def prop : argType → retType → Prop := sorry

/-- `A354602` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A354602` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A354602 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A354602 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A354602 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A354602
