import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A348913

Number of N(0,1) variables needed for a 1/2 chance that their maximum exceeds the maximum of n N(1,1) variables.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A348913

/-- Index type of `A348913` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A348913`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A348913

/-- Number of N(0,1) variables needed for a 1/2 chance that their maximum exceeds the maximum of n N(1,1) variables. -/
def A348913 : A348913.argType → A348913.retType := sorry

namespace A348913

/-- Relation that defines `A348913`. -/
def prop : argType → retType → Prop := sorry

/-- `A348913` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A348913` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A348913 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A348913 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A348913 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A348913
