import LOEIS.A392.A392577.Defs

set_option linter.unusedVariables false

/-!
# A392577

a(0) = 0, a(1) = 1; for n > 1, a(n) = a(n-1) - A056240(n) if nonnegative and not already in the sequence, otherwise a(n) = a(n-1) + A056240(n), where A056240(n) is the smallest number whose prime divisors, counted with multiplicity, sum to n.

The 60 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A392577

/-- Known terms of `A392577`, starting at index `0`. -/
def data : List retType :=
  [0, 1, 3, 6, 2, 7, 15, 8, 23, 9,
    30, 19, 54, 41, 74, 48, 87, 70, 5, 24,
    75, 37, 94, 71, 166, 120, 51, 143, 28, 57,
    218, 187, 100, 38, 131, 255, 410, 373, 156, 82,
    193, 152, 337, 294, 171, 85, 214, 167, 382, 288,
    147, 335, 570, 517, 188, 294, 135, 347, 612, 553]

/-- `A392577` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 60) : A392577 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 60) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 60) : fz n = data[n.toNat]! := sorry

end A392577
