import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A187240

Number of ways to place 8 nonattacking bishops on an n X n board.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A187240

/-- Index type of `A187240` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A187240`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A187240

/-- Number of ways to place 8 nonattacking bishops on an n X n board. -/
def A187240 : A187240.argType → A187240.retType := sorry

namespace A187240

/-- Relation that defines `A187240`. -/
def prop : argType → retType → Prop := sorry

/-- `A187240` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A187240` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A187240 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A187240 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A187240 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A187240
