import LOEIS.A125.A125268.Defs

set_option linter.unusedVariables false

/-!
# A125268

Numbers that end with decimal digit 1, 3, 7, or 9 and that produce only composite numbers when any of the digits 0,1,...,9 is inserted anywhere in them (including at the beginning or end).

The 34 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A125268

/-- Known terms of `A125268`, starting at index `1`. -/
def data : List retType :=
  [25011, 52647, 72753, 122313, 168699, 283251, 324021, 598041, 783441, 804131,
    837207, 924807, 1247241, 1905759, 2514819, 3461101, 3514077, 3617389, 3905817, 4112913,
    4142139, 4203151, 4229871, 4283679, 4531907, 4628827, 4828443, 5380413, 5478091, 5632671,
    5714889, 5818569, 5989269, 5990961]

/-- `A125268` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 35) : A125268 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 35) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 35) : fz n = data[n.toNat - 1]! := sorry

end A125268
