import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A055280

Number of rooted trees with n nodes and 5 leaves.

OEIS offset `6`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A055280

/-- Index type of `A055280` (OEIS offset `6`). -/
abbrev argType : Type := {n : Nat // 6 ≤ n}

/-- Value type of `A055280`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 6

end A055280

/-- Number of rooted trees with n nodes and 5 leaves. -/
def A055280 : A055280.argType → A055280.retType := sorry

namespace A055280

/-- Relation that defines `A055280`. -/
def prop : argType → retType → Prop := sorry

/-- `A055280` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A055280` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A055280 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 6 ≤ n) : fn n = A055280 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 6 ≤ n) : fz n = A055280 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 6 ≤ n) : fn n = fz (n : Int) := sorry

end A055280
