import LOEIS.A283.A283636.Defs

set_option linter.unusedVariables false

/-!
# A283636

Number of 3Xn 0..1 arrays with no 1 equal to more than one of its horizontal, diagonal and antidiagonal neighbors, with the exception of exactly two elements.

The 21 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A283636

/-- Known terms of `A283636`, starting at index `1`. -/
def data : List retType :=
  [0, 6, 37, 639, 2875, 21963, 127635, 693783, 3852792, 20064881,
    103580688, 524492026, 2611146243, 12857829918, 62584105607, 301823257243, 1443755263689, 6855724802293, 32346704566179, 151738352019137,
    708116512419058]

/-- `A283636` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 22) : A283636 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 22) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 22) : fz n = data[n.toNat - 1]! := sorry

end A283636
