import LOEIS.A219.A219307.Defs

set_option linter.unusedVariables false

/-!
# A219307

Unchanging value maps: number of nX5 binary arrays indicating the locations of corresponding elements unequal to no horizontal or vertical neighbor in a random 0..2 nX5 array.

The 16 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A219307

/-- Known terms of `A219307`, starting at index `1`. -/
def data : List retType :=
  [12, 142, 1958, 25647, 326444, 4215579, 54797587, 710493819, 9194088812, 119051026450,
    1542298398563, 19977719144984, 258742519096389, 3351214351286909, 43406104354037517, 562207779495312746]

/-- `A219307` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A219307 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 17) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 17) : fz n = data[n.toNat - 1]! := sorry

end A219307
