import LOEIS.A314.A314032.Defs

set_option linter.unusedVariables false

/-!
# A314032

Coordination sequence Gal.6.324.4 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A314032

/-- Known terms of `A314032`, starting at index `0`. -/
def data : List retType :=
  [1, 5, 11, 15, 20, 26, 30, 36, 41, 45,
    51, 56, 61, 67, 71, 76, 82, 86, 92, 97,
    101, 107, 112, 117, 123, 127, 132, 138, 142, 148,
    153, 157, 163, 168, 173, 179, 183, 188, 194, 198,
    204, 209, 213, 219, 224, 229, 235, 239, 244, 250]

/-- `A314032` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A314032 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A314032
