import LOEIS.A386.A386642.Defs

set_option linter.unusedVariables false

/-!
# A386642

Roll n fair, distinguishable, n-sided dice and sort the dice in increasing order with the lowest on the left, highest on the right. Let m be the maximum value rolled and select the m-th die from the right. Then a(n) is the number of such rolls (over all n^n possible outcomes) where the selected die shows 1.

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A386642

/-- Known terms of `A386642`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 16, 137, 1606, 23497, 409592, 8271937, 189789418, 4874472641,
    138523776172, 4314925824673, 146181218441870, 5350951285699489, 210455196008787256, 8850666552984340097, 396319364478527061970, 18825724592531059826305, 945498791510410439544644, 50060067791679691665368161]

/-- `A386642` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 21) : A386642 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : fz n = data[n.toNat - 1]! := sorry

end A386642
