import LOEIS.A339.A339108.Defs

set_option linter.unusedVariables false

/-!
# A339108

Number of compositions (ordered partitions) of n into distinct parts >= 7.

The 61 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A339108

/-- Known terms of `A339108`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
    1, 1, 1, 1, 1, 3, 3, 5, 5, 7,
    7, 9, 9, 11, 17, 19, 25, 33, 39, 47,
    59, 67, 79, 93, 129, 143, 185, 223, 289, 333,
    423, 491, 611, 703, 847, 1089, 1281, 1547, 1889, 2323,
    2833, 3417, 4095, 4967, 5939, 7099, 8359, 10653, 12345, 15047,
    17993]

/-- `A339108` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 61) : A339108 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 61) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 61) : fz n = data[n.toNat]! := sorry

end A339108
