import LOEIS.A135.A135613.Defs

set_option linter.unusedVariables false

/-!
# A135613

Initial digit of Mersenne primes A000668.

The 48 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A135613

/-- Known terms of `A135613`, starting at index `1`. -/
def data : List retType :=
  [3, 7, 3, 1, 8, 1, 5, 2, 2, 6,
    1, 1, 6, 5, 1, 1, 4, 2, 1, 2,
    4, 3, 2, 4, 4, 4, 8, 5, 5, 5,
    7, 1, 1, 4, 8, 6, 1, 4, 9, 1,
    2, 1, 3, 1, 2, 1, 3, 5]

/-- `A135613` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 49) : A135613 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 49) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 49) : fz n = data[n.toNat - 1]! := sorry

end A135613
