import LOEIS.A311.A311252.Defs

set_option linter.unusedVariables false

/-!
# A311252

Coordination sequence Gal.6.117.3 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A311252

/-- Known terms of `A311252`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 8, 12, 16, 21, 25, 29, 33, 37,
    42, 46, 50, 54, 57, 61, 66, 71, 75, 78,
    82, 87, 92, 96, 100, 103, 106, 111, 116, 121,
    124, 127, 132, 137, 142, 146, 149, 152, 156, 161,
    166, 170, 173, 177, 182, 187, 192, 195, 198, 202]

/-- `A311252` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A311252 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A311252
