import LOEIS.A150.A150693.Defs

set_option linter.unusedVariables false

/-!
# A150693

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 0), (-1, 0, 1), (-1, 1, -1), (1, 0, 1), (1, 1, 0)}.

The 28 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A150693

/-- Known terms of `A150693`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 8, 26, 118, 438, 2078, 8209, 39754, 162831,
    797320, 3344263, 16483408, 70313101, 348008609, 1503387856, 7461490857, 32553374801, 161874095473, 711874224388,
    3544621282571, 15690913376927, 78205701748159, 348111360116639, 1736283725383760, 7765241828198106, 38751745866315018, 174023171833791778]

/-- `A150693` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 28) : A150693 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 28) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 28) : fz n = data[n.toNat]! := sorry

end A150693
