import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A319911

Number of distinct pairs (m, y), where m >= 1 and y is an integer partition of n with no 1's, such that m can be obtained by iteratively adding or multiplying together parts of y until only one part (equal to m) remains.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A319911

/-- Index type of `A319911` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A319911`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A319911

/-- Number of distinct pairs (m, y), where m >= 1 and y is an integer partition of n with no 1's, such that m can be obtained by iteratively adding or multiplying together parts of y until only one part (equal to m) remains. -/
def A319911 : A319911.argType → A319911.retType := sorry

namespace A319911

/-- Relation that defines `A319911`. -/
def prop : argType → retType → Prop := sorry

/-- `A319911` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A319911` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A319911 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A319911 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A319911 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A319911
