name = "LOEIS"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LOEIS"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0-rc1"

[[require]]
name = "leansqlite"
scope = "leanprover"
rev = "main"


[[lean_lib]]
name = "LOEIS"

[[lean_lib]]
name = "Scripts"
roots = ["Scripts.OeisIngest"]
globs = ["Scripts.OeisIngest.+"]

[[lean_exe]]
name = "oeis-ingest"
root = "Scripts.OeisIngest"
