import LOEIS.A279.A279470.Defs

set_option linter.unusedVariables false

/-!
# A279470

Decimal representation of the x-axis, from the left edge to the origin, of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 157", based on the 5-celled von Neumann neighborhood.

The 37 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A279470

/-- Known terms of `A279470`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 2, 12, 5, 58, 8, 243, 22, 1006,
    42, 4036, 81, 16302, 138, 65332, 369, 261854, 722, 1047788,
    1453, 4193246, 2642, 16773388, 5229, 67101182, 11522, 268422392, 20111, 1073711992,
    41803, 4294908838, 97934, 17179755306, 179088, 68719308495, 293624]

/-- `A279470` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 37) : A279470 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 37) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 37) : fz n = data[n.toNat]! := sorry

end A279470
