import LOEIS.A002.A002542.Defs

set_option linter.unusedVariables false

/-!
# A002542

Number of two-valued complete Post functions of n variables.

The 8 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A002542

/-- Known terms of `A002542`, starting at index `1`. -/
def data : List retType :=
  [0, 2, 56, 16256, 1073709056, 4611686016279904256, 85070591730234615856620279821087277056, 28948022309329048855892746252171976963147354982949671778132708698262398304256]

/-- `A002542` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 9) : A002542 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 9) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 9) : fz n = data[n.toNat - 1]! := sorry

end A002542
