import LOEIS.A211.A211316.Defs

set_option linter.unusedVariables false

/-!
# A211316

Maximal size of sum-free set in additive group of integers mod n.

The 70 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A211316

/-- Known terms of `A211316`, starting at index `2`. -/
def data : List retType :=
  [1, 1, 2, 2, 3, 2, 4, 3, 5, 4,
    6, 4, 7, 6, 8, 6, 9, 6, 10, 7,
    11, 8, 12, 10, 13, 9, 14, 10, 15, 10,
    16, 12, 17, 14, 18, 12, 19, 13, 20, 14,
    21, 14, 22, 18, 23, 16, 24, 16, 25, 18,
    26, 18, 27, 22, 28, 19, 29, 20, 30, 20,
    31, 21, 32, 26, 33, 22, 34, 24, 35, 24]

/-- `A211316` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 72) : A211316 n = data[n.val - 2]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 72) : fn n = data[n - 2]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 72) : fz n = data[n.toNat - 2]! := sorry

end A211316
