import LOEIS.A039.A039272.Defs

set_option linter.unusedVariables false

/-!
# A039272

Numbers whose base-12 representation has the same number of 9's and 10's.

The 70 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A039272

/-- Known terms of `A039272`, starting at index `1`. -/
def data : List retType :=
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 11,
    12, 13, 14, 15, 16, 17, 18, 19, 20, 23,
    24, 25, 26, 27, 28, 29, 30, 31, 32, 35,
    36, 37, 38, 39, 40, 41, 42, 43, 44, 47,
    48, 49, 50, 51, 52, 53, 54, 55, 56, 59,
    60, 61, 62, 63, 64, 65, 66, 67, 68, 71,
    72, 73, 74, 75, 76, 77, 78, 79, 80, 83]

/-- `A039272` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 71) : A039272 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 71) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 71) : fz n = data[n.toNat - 1]! := sorry

end A039272
