import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A121421

Column 0 of triangle A121420.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A121421

/-- Index type of `A121421` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A121421`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A121421

/-- Column 0 of triangle A121420. -/
def A121421 : A121421.argType → A121421.retType := sorry

namespace A121421

/-- Relation that defines `A121421`. -/
def prop : argType → retType → Prop := sorry

/-- `A121421` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A121421` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A121421 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A121421 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A121421 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A121421
