import LOEIS.A099.A099909.Defs

set_option linter.unusedVariables false

/-!
# A099909

(prime(n)*(prime(n+1)-1) + (prime(n)-1)*prime(n+1)) / 2.

The 40 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A099909

/-- Known terms of `A099909`, starting at index `2`. -/
def data : List retType :=
  [11, 29, 68, 131, 206, 305, 416, 641, 869, 1113,
    1478, 1721, 1976, 2441, 3071, 3539, 4023, 4688, 5111, 5691,
    6476, 7301, 8540, 9698, 10301, 10916, 11555, 12206, 14231, 16508,
    17813, 18905, 20567, 22349, 23553, 25431, 27056, 28721, 30791, 32219]

/-- `A099909` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 42) : A099909 n = data[n.val - 2]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 42) : fn n = data[n - 2]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 42) : fz n = data[n.toNat - 2]! := sorry

end A099909
