import LOEIS.A281.A281269.Defs

set_option linter.unusedVariables false

/-!
# A281269

Triangle read by rows: T(n,k) is the number of edge covers of the complete labeled graph on n nodes that are minimal and have exactly k edges, n>=2, 1<=k<=n-1.

The 66 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A281269

/-- Known terms of `flat`, starting at index `2`. -/
def flatData : List flatRetType :=
  [1, 0, 3, 0, 3, 4, 0, 0, 30, 5,
    0, 0, 15, 150, 6, 0, 0, 0, 315, 525,
    7, 0, 0, 0, 105, 3360, 1568, 8, 0, 0,
    0, 0, 3780, 24570, 4284, 9, 0, 0, 0, 0,
    945, 69300, 142380, 11070, 10, 0, 0, 0, 0, 0,
    51975, 866250, 713790, 27555, 11, 0, 0, 0, 0, 0,
    10395, 1455300, 8399160, 3250500, 66792, 12]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 68) : flat n = flatData[n.val - 2]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 68) : flatFn n = flatData[n - 2]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 68) : flatFz n = flatData[n.toNat - 2]! := sorry

end A281269
