import LOEIS.A203.A203447.Defs

set_option linter.unusedVariables false

/-!
# A203447

Number of (n+1)X4 0..1 arrays with column and row pair sums b(i,j)=a(i,j)+a(i,j-1) and c(i,j)=a(i,j)+a(i-1,j) such that rows of b(i,j) and columns of c(i,j) are lexicographically nondecreasing.

The 25 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A203447

/-- Known terms of `A203447`, starting at index `1`. -/
def data : List retType :=
  [32, 80, 321, 1177, 4200, 13777, 42112, 120522, 325918, 838830,
    2069033, 4920266, 11341301, 25458409, 55884995, 120402167, 255405453, 534912676, 1108733446, 2279008959,
    4653553590, 9452873217, 19124629018, 38573101568, 77618789808]

/-- `A203447` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 26) : A203447 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 26) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 26) : fz n = data[n.toNat - 1]! := sorry

end A203447
