import LOEIS.A224.A224299.Defs

set_option linter.unusedVariables false

/-!
# A224299

Collatz problem with rational negative numbers: number of steps to reach the end of the cycle starting with 1/(2n+1) where n is negative (the initial term is not counted).

The 66 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A224299

/-- Known terms of `A224299`, starting at index `1`. -/
def data : List retType :=
  [0, 1, 4, 9, 4, 8, 14, 4, 17, 36,
    13, 7, 24, 9, 36, 38, 24, 23, 55, 20,
    28, 77, 20, 25, 93, 9, 100, 29, 37, 38,
    78, 17, 36, 120, 7, 60, 99, 16, 54, 67,
    10, 106, 184, 43, 74, 153, 51, 16, 84, 34,
    10, 212, 12, 170, 208, 26, 60, 57, 8, 57,
    92, 53, 85, 58, 148, 52]

/-- `A224299` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 67) : A224299 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 67) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 67) : fz n = data[n.toNat - 1]! := sorry

end A224299
