import LOEIS.A148.A148780.Defs

set_option linter.unusedVariables false

/-!
# A148780

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 0), (-1, 1, -1), (0, 0, -1), (0, 1, 1), (1, -1, 0)}.

The 29 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A148780

/-- Known terms of `A148780`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 8, 23, 81, 280, 961, 3559, 13454,
    50692, 196368, 776979, 3070167, 12268437, 49815796, 203119103, 831940820, 3442970866, 14329445203,
    59783757046, 250943394923, 1059386977640, 4484344952953, 19051650390329, 81318085577387, 348069408274893, 1493378869048524, 6429188146005489]

/-- `A148780` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 29) : A148780 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 29) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 29) : fz n = data[n.toNat]! := sorry

end A148780
