import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A318847

Number of tree-partitions of a multiset whose multiplicities are the prime indices of n.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A318847

/-- Index type of `A318847` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A318847`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A318847

/-- Number of tree-partitions of a multiset whose multiplicities are the prime indices of n. -/
def A318847 : A318847.argType → A318847.retType := sorry

namespace A318847

/-- Relation that defines `A318847`. -/
def prop : argType → retType → Prop := sorry

/-- `A318847` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A318847` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A318847 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A318847 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A318847 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A318847
