import LOEIS.A205.A205914.Defs

set_option linter.unusedVariables false

/-!
# A205914

Number of (n+1) X 6 0..2 arrays with every 2 X 2 subblock having the same number of clockwise edge increases as its horizontal neighbors and the same number of counterclockwise edge increases as its vertical neighbors.

The 14 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A205914

/-- Known terms of `A205914`, starting at index `1`. -/
def data : List retType :=
  [43155, 387267, 8986929, 231526056, 6011669886, 157611325827, 4140502079766, 109077858375072, 2875376462502051, 75869626381275306,
    2002323261874373574, 52863137289825399351, 1395740977514471843850, 36856545167116354878438]

/-- `A205914` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 15) : A205914 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 15) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 15) : fz n = data[n.toNat - 1]! := sorry

end A205914
