import LOEIS.A215.A215176.Defs

set_option linter.unusedVariables false

/-!
# A215176

Number of nXnXn triangular 0..2 arrays with every horizontal row nondecreasing, first elements of rows nonincreasing, last elements of rows nondecreasing, and every row having the same average value.

The 24 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A215176

/-- Known terms of `A215176`, starting at index `1`. -/
def data : List retType :=
  [3, 4, 5, 9, 17, 48, 141, 559, 2231, 11148,
    55733, 334389, 2006325, 14044264, 98309837, 786478683, 6291829451, 56626465044, 509638185381, 5096381853793,
    50963818537913, 560602003917024, 6166622043087245, 73999464517046919]

/-- `A215176` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 25) : A215176 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 25) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 25) : fz n = data[n.toNat - 1]! := sorry

end A215176
