import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A117885

Numbers k such that a regular (k^3-k)-gon can be constructed by means of a ruler and compass.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A117885

/-- Index type of `A117885` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A117885`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A117885

/-- Numbers k such that a regular (k^3-k)-gon can be constructed by means of a ruler and compass. -/
def A117885 : A117885.argType → A117885.retType := sorry

namespace A117885

/-- Relation that defines `A117885`. -/
def prop : argType → retType → Prop := sorry

/-- `A117885` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A117885` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A117885 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A117885 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A117885 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A117885
