import LOEIS.A236.A236245.Defs

set_option linter.unusedVariables false

/-!
# A236245

Primes of the form C(2*m, m) + prime(m), where C(2*m, m) = (2*m)!/(m!)^2.

The 9 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A236245

/-- Known terms of `A236245`, starting at index `1`. -/
def data : List retType :=
  [263, 937, 3449, 12889, 2704193, 10400641, 35345263867, 23623985175715118288974865541854103729347, 362048725489728431058442528694228154899210914562190067]

/-- `A236245` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 10) : A236245 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 10) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 10) : fz n = data[n.toNat - 1]! := sorry

end A236245
