import LOEIS.A098.A098795.Defs

set_option linter.unusedVariables false

/-!
# A098795

The two digits touching the first comma have as absolute difference 0. The next such difference is 1. The next one is 2. Then 3, 4, 5... etc. When we reach 9 the differences start a new cycle: 0, 1, 2, 3... etc. Among many such possible sequences, this is the slowest increasing one starting with "1".

The 50 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A098795

/-- Known terms of `A098795`, starting at index `1`. -/
def data : List retType :=
  [1, 10, 11, 30, 31, 50, 51, 70, 71, 90,
    91, 100, 103, 104, 105, 106, 107, 108, 109, 110,
    909, 918, 927, 936, 945, 954, 963, 972, 981, 990,
    991, 1000, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
    9009, 9018, 9027, 9036, 9045, 9054, 9063, 9072, 9081, 9090]

/-- `A098795` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 51) : A098795 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 51) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 51) : fz n = data[n.toNat - 1]! := sorry

end A098795
