import LOEIS.A142.A142239.Defs

set_option linter.unusedVariables false

/-!
# A142239

Denominators of continued fraction convergents to sqrt(3/2).

The 28 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A142239

/-- Known terms of `A142239`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 9, 40, 89, 396, 881, 3920, 8721, 38804,
    86329, 384120, 854569, 3802396, 8459361, 37639840, 83739041, 372596004, 828931049, 3688320200,
    8205571449, 36510605996, 81226783441, 361417739760, 804062262961, 3577666791604, 7959395846169, 35415250176280]

/-- `A142239` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 28) : A142239 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 28) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 28) : fz n = data[n.toNat]! := sorry

end A142239
