import LOEIS.A263.A263237.Defs

set_option linter.unusedVariables false

/-!
# A263237

Number of (n+3)X(2+3) 0..1 arrays with each row and column not divisible by 11, read as a binary number with top and left being the most significant bits.

The 13 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A263237

/-- Known terms of `A263237`, starting at index `1`. -/
def data : List retType :=
  [366629, 12652497, 365832647, 10595045187, 306234039025, 8971344440493, 259877539798060, 7558319565205403, 219503638927712079, 6370066248057714293,
    184726447984445515275, 5358013099014479637987, 155381832153450791875837]

/-- `A263237` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 14) : A263237 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 14) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 14) : fz n = data[n.toNat - 1]! := sorry

end A263237
