import LOEIS.A177.A177210.Defs

set_option linter.unusedVariables false

/-!
# A177210

Numbers k that are the products of two distinct primes such that 2*k-1 are also products of two distinct primes.

The 54 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A177210

/-- Known terms of `A177210`, starting at index `1`. -/
def data : List retType :=
  [26, 33, 35, 39, 46, 58, 62, 65, 93, 94,
    111, 118, 119, 133, 134, 146, 155, 161, 178, 183,
    202, 206, 209, 214, 219, 226, 235, 237, 247, 249,
    253, 259, 267, 287, 291, 295, 299, 334, 335, 341,
    362, 377, 382, 386, 391, 393, 395, 407, 422, 445,
    447, 451, 453, 478]

/-- `A177210` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 55) : A177210 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 55) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 55) : fz n = data[n.toNat - 1]! := sorry

end A177210
