import LOEIS.A349.A349275.Defs

set_option linter.unusedVariables false

/-!
# A349275

Semiprimes with only semiprime digits, each appearing at least once.

The 53 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A349275

/-- Known terms of `A349275`, starting at index `1`. -/
def data : List retType :=
  [469, 649, 694, 4469, 4694, 4699, 4946, 6499, 6649, 6694,
    9446, 9466, 9469, 9946, 44669, 44966, 44969, 46469, 46946, 46969,
    46994, 46999, 49466, 49649, 49694, 49699, 49969, 64469, 64649, 64669,
    64949, 64994, 66469, 66494, 66694, 69449, 69469, 69494, 69694, 69949,
    94469, 94669, 94699, 94969, 96449, 96494, 96649, 96946, 96949, 96994,
    99646, 99649, 444694]

/-- `A349275` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 54) : A349275 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 54) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 54) : fz n = data[n.toNat - 1]! := sorry

end A349275
