import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A194914

Fractalization of (1+[n/sqrt(8)]), where [ ]=floor.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A194914

/-- Index type of `A194914` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A194914`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A194914

/-- Fractalization of (1+[n/sqrt(8)]), where [ ]=floor. -/
def A194914 : A194914.argType → A194914.retType := sorry

namespace A194914

/-- Relation that defines `A194914`. -/
def prop : argType → retType → Prop := sorry

/-- `A194914` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A194914` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A194914 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A194914 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A194914 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A194914
