import LOEIS.A236.A236363.Defs

set_option linter.unusedVariables false

/-!
# A236363

Sum of digits of A114440(n).

The 76 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A236363

/-- Known terms of `A236363`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 3, 4, 5, 6, 7, 8, 9, 3,
    9, 3, 6, 9, 9, 6, 9, 12, 9, 9,
    9, 9, 12, 9, 9, 9, 9, 9, 18, 9,
    9, 18, 18, 18, 18, 18, 18, 18, 18, 18,
    9, 18, 18, 18, 18, 27, 18, 9, 18, 18,
    27, 18, 18, 27, 27, 27, 18, 36, 27, 27,
    27, 18, 27, 27, 27, 27, 27, 27, 27, 27,
    27, 36, 36, 36, 36, 27]

/-- `A236363` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 77) : A236363 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 77) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 77) : fz n = data[n.toNat - 1]! := sorry

end A236363
