import LOEIS.A271.A271244.Defs

set_option linter.unusedVariables false

/-!
# A271244

Number of nXnXn triangular 0..6 arrays with new values introduced in sequential zero-upwards order and exactly one inverted 2x2x2 triangle having values all different.

The 8 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A271244

/-- Known terms of `A271244`, starting at index `1`. -/
def data : List retType :=
  [0, 0, 77, 39210, 48347502, 187829420863, 2247557960061633, 79899827658375960942]

/-- `A271244` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 9) : A271244 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 9) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 9) : fz n = data[n.toNat - 1]! := sorry

end A271244
