import LOEIS.A086.A086955.Defs

set_option linter.unusedVariables false

/-!
# A086955

a(n) = n^2 + 2*n + 2 - (-1)^n.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A086955

/-- Known terms of `A086955`, starting at index `0`. -/
def data : List retType :=
  [1, 6, 9, 18, 25, 38, 49, 66, 81, 102,
    121, 146, 169, 198, 225, 258, 289, 326, 361, 402,
    441, 486, 529, 578, 625, 678, 729, 786, 841, 902,
    961, 1026, 1089, 1158, 1225, 1298, 1369, 1446, 1521, 1602,
    1681, 1766, 1849, 1938, 2025, 2118, 2209, 2306, 2401, 2502]

/-- `A086955` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A086955 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A086955
