import LOEIS.A376.A376732.Defs

set_option linter.unusedVariables false

/-!
# A376732

Triangle read by rows: T(n,k) is the maximum number of squares covered (i.e., attacked) by k independent (i.e., non-attacking) queens on an n X n chessboard.

The 66 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A376732

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 4, 0, 9, 9, 0, 12, 15, 16, 16,
    17, 23, 25, 25, 25, 20, 30, 35, 36, 36,
    36, 25, 37, 45, 49, 49, 49, 49, 28, 44,
    55, 62, 64, 64, 64, 64, 33, 52, 66, 76,
    81, 81, 81, 81, 81, 36, 60, 77, 92, 100,
    100, 100, 100, 100, 100, 41, 68, 88, 104, 121,
    121, 121, 121, 121, 121, 121]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 67) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 67) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 67) : flatFz n = flatData[n.toNat - 1]! := sorry

end A376732
