import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A263844

Constant term in expansion of n in Fraenkel's exotic ternary representation.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A263844

/-- Index type of `A263844` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A263844`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A263844

/-- Constant term in expansion of n in Fraenkel's exotic ternary representation. -/
def A263844 : A263844.argType → A263844.retType := sorry

namespace A263844

/-- Relation that defines `A263844`. -/
def prop : argType → retType → Prop := sorry

/-- `A263844` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A263844` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A263844 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A263844 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A263844 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A263844
