import LOEIS.A279.A279719.Defs

set_option linter.unusedVariables false

/-!
# A279719

Decimal representation of the x-axis, from the origin to the right edge, of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 189", based on the 5-celled von Neumann neighborhood.

The 34 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A279719

/-- Known terms of `A279719`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 3, 20, 7, 104, 79, 16, 927,
    288, 3135, 2880, 1663, 27776, 22783, 13568, 223743, 250368, 427007,
    848896, 1779711, 3622912, 6950911, 14929920, 22323199, 17113088, 184041471, 18300928, 986349567,
    363102208, 3410034687, 2520580096, 795475967]

/-- `A279719` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 34) : A279719 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 34) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 34) : fz n = data[n.toNat]! := sorry

end A279719
