import LOEIS.A240.A240378.Defs

set_option linter.unusedVariables false

/-!
# A240378

Number of nX3 0..3 arrays with no element equal to zero plus the sum of elements to its left or two plus the sum of elements above it or zero plus the sum of the elements diagonally to its northwest, modulo 4.

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A240378

/-- Known terms of `A240378`, starting at index `1`. -/
def data : List retType :=
  [4, 38, 330, 2066, 16994, 116030, 884792, 6273952, 46648918, 335571098,
    2468592214, 17883911418, 130889355348, 951392168734, 6947056359884, 50571064277718, 368890128041664, 2687133002363550, 19592211767424272, 142760104420636614]

/-- `A240378` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 21) : A240378 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : fz n = data[n.toNat - 1]! := sorry

end A240378
