import LOEIS.A240.A240888.Defs

set_option linter.unusedVariables false

/-!
# A240888

Number of n X 3 0..2 arrays with no element equal to a different number of vertical neighbors than horizontal neighbors, with new values 0..2 introduced in row major order.

The 22 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A240888

/-- Known terms of `A240888`, starting at index `1`. -/
def data : List retType :=
  [2, 11, 57, 289, 1485, 7609, 38981, 199761, 1023597, 5245049,
    26876501, 137719297, 705694973, 3616090505, 18529407461, 94947553233, 486525966349, 2493034391385, 12774694280053, 65459511713057,
    335424674724381, 1718767975363881]

/-- `A240888` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 23) : A240888 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 23) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 23) : fz n = data[n.toNat - 1]! := sorry

end A240888
