import LOEIS.A283.A283377.Defs

set_option linter.unusedVariables false

/-!
# A283377

Binary representation of the x-axis, from the origin to the right edge, of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 627", based on the 5-celled von Neumann neighborhood.

The 20 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A283377

/-- Known terms of `A283377`, starting at index `0`. -/
def data : List retType :=
  [1, 10, 100, 1110, 11000, 100110, 1110000, 11001110, 101001000, 1011110110,
    10011000000, 111000111110, 1101100111000, 10000110100110, 111110011110000, 1111010011001110, 11100110001001000, 110100001011110110, 1001111110011000000, 11001111000000111110]

/-- `A283377` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 20) : A283377 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 20) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 20) : fz n = data[n.toNat]! := sorry

end A283377
