import LOEIS.A394.A394313.Defs

set_option linter.unusedVariables false

/-!
# A394313

Primes that are the least prime factor of some Fibonacci number.

The 57 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A394313

/-- Known terms of `A394313`, starting at index `1`. -/
def data : List retType :=
  [2, 3, 5, 13, 37, 59, 73, 89, 139, 157,
    179, 193, 233, 269, 277, 313, 353, 359, 397, 457,
    479, 509, 557, 577, 613, 619, 673, 677, 719, 733,
    757, 809, 839, 877, 953, 977, 997, 1019, 1049, 1069,
    1093, 1109, 1153, 1213, 1237, 1319, 1439, 1453, 1511, 1579,
    1597, 1619, 1657, 1699, 1753, 1873, 1877]

/-- `A394313` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 58) : A394313 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 58) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 58) : fz n = data[n.toNat - 1]! := sorry

end A394313
