import LOEIS.A263.A263378.Defs

set_option linter.unusedVariables false

/-!
# A263378

Number of (n+1)X(4+1) 0..4 arrays with each row and column divisible by 9, read as a base-5 number with top and left being the most significant digits.

The 12 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A263378

/-- Known terms of `A263378`, starting at index `1`. -/
def data : List retType :=
  [31, 6731, 2332320, 787486033, 271477636708, 94234480080401, 32785038500076147, 11408914805662871537, 3970303184293507213506, 1381662664358658502302495,
    480818286459067326489389236, 167324733669324390798735322667]

/-- `A263378` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 13) : A263378 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 13) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 13) : fz n = data[n.toNat - 1]! := sorry

end A263378
