import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A265758

Expansion of Product_{k>=1} ((1 + k*x^k)/(1 - k*x^k)).

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A265758

/-- Index type of `A265758` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A265758`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A265758

/-- Expansion of Product_{k>=1} ((1 + k*x^k)/(1 - k*x^k)). -/
def A265758 : A265758.argType → A265758.retType := sorry

namespace A265758

/-- Relation that defines `A265758`. -/
def prop : argType → retType → Prop := sorry

/-- `A265758` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A265758` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A265758 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A265758 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A265758 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A265758
