import LOEIS.A212.A212200.Defs

set_option linter.unusedVariables false

/-!
# A212200

Multiplicative order of n in nim-multiplication.

The 78 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A212200

/-- Known terms of `A212200`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 3, 15, 15, 15, 15, 5, 15, 5,
    15, 15, 5, 5, 15, 85, 85, 255, 255, 85,
    85, 255, 255, 85, 85, 255, 255, 255, 255, 85,
    85, 255, 255, 255, 255, 85, 255, 85, 255, 255,
    255, 255, 255, 255, 85, 255, 85, 255, 85, 85,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    85, 85, 255, 255, 51, 255, 255, 255, 51, 255,
    255, 17, 255, 85, 255, 17, 255, 85]

/-- `A212200` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 79) : A212200 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 79) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 79) : fz n = data[n.toNat - 1]! := sorry

end A212200
