import LOEIS.A292.A292251.Defs

set_option linter.unusedVariables false

/-!
# A292251

The 3-adic valuation of A048673(n).

The 120 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A292251

/-- Known terms of `A292251`, starting at index `1`. -/
def data : List retType :=
  [0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
    0, 0, 2, 0, 2, 0, 0, 0, 1, 0,
    0, 0, 1, 0, 0, 0, 2, 0, 0, 0,
    0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
    0, 0, 1, 0, 0, 0, 3, 0, 0, 0,
    1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 1, 0, 1, 0, 2, 0, 0, 0,
    0, 0, 0, 0, 1, 0, 2, 0, 1, 0,
    0, 0, 2, 0, 0, 0, 1, 0, 0, 0,
    0, 0, 1, 0, 4, 0, 1, 0, 0, 0,
    0, 0, 3, 0, 0, 0, 0, 0, 1, 0,
    0, 0, 0, 0, 1, 0, 1, 0, 1, 0]

/-- `A292251` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 121) : A292251 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 121) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 121) : fz n = data[n.toNat - 1]! := sorry

end A292251
