import LOEIS.A195.A195289.Defs

set_option linter.unusedVariables false

/-!
# A195289

Decimal expansion of normalized Philo sum, Philo(ABC,I), where I=incenter of a 3,4,5 right triangle ABC.

The 100 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A195289

/-- Known terms of `A195289`, starting at index `0`. -/
def data : List retType :=
  [4, 8, 4, 7, 8, 2, 3, 8, 5, 3,
    6, 6, 1, 7, 5, 3, 4, 8, 3, 3,
    5, 1, 6, 5, 4, 1, 8, 0, 2, 2,
    8, 1, 1, 5, 2, 7, 8, 0, 8, 8,
    2, 5, 5, 4, 5, 2, 2, 8, 2, 5,
    9, 9, 2, 3, 4, 1, 2, 9, 5, 4,
    4, 3, 3, 4, 6, 0, 2, 1, 8, 8,
    6, 9, 4, 6, 2, 9, 6, 2, 9, 3,
    6, 8, 4, 9, 2, 7, 9, 5, 9, 9,
    8, 0, 7, 0, 1, 2, 2, 0, 6, 2]

/-- `A195289` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 100) : A195289 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 100) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 100) : fz n = data[n.toNat]! := sorry

end A195289
