import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A002698

Coefficients of Chebyshev polynomials: n*(2*n-3)*2^(2*n-5).

OEIS offset `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A002698

/-- Index type of `A002698` (OEIS offset `2`). -/
abbrev argType : Type := {n : Nat // 2 ≤ n}

/-- Value type of `A002698`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 2

end A002698

/-- Coefficients of Chebyshev polynomials: n*(2*n-3)*2^(2*n-5). -/
def A002698 : A002698.argType → A002698.retType := sorry

namespace A002698

/-- Relation that defines `A002698`. -/
def prop : argType → retType → Prop := sorry

/-- `A002698` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A002698` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A002698 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 2 ≤ n) : fn n = A002698 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 2 ≤ n) : fz n = A002698 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 2 ≤ n) : fn n = fz (n : Int) := sorry

end A002698
