import LOEIS.A114.A114028.Defs

set_option linter.unusedVariables false

/-!
# A114028

n-th partial concatenation of A114027 divided by n-th composite.

The 18 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A114028

/-- Known terms of `A114028`, starting at index `1`. -/
def data : List retType :=
  [1, 8, 61, 5424, 488161, 4068009, 34868649, 3254407241, 305100678845, 2712006034178,
    244080543076021, 23245766007240096, 2218914027963827346, 203400452563350840051, 19526443446081680644897, 1877542639046315446624712, 18080040227853408004534264, 1743432450543007200437232601]

/-- `A114028` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 19) : A114028 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 19) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 19) : fz n = data[n.toNat - 1]! := sorry

end A114028
