import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A325076

Prime numbers congruent to 1, 16 or 22 modulo 39 neither representable by x^2 + x*y + 10*y^2 nor by x^2 + x*y + 127*y^2.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A325076

/-- Index type of `A325076` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A325076`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A325076

/-- Prime numbers congruent to 1, 16 or 22 modulo 39 neither representable by x^2 + x*y + 10*y^2 nor by x^2 + x*y + 127*y^2. -/
def A325076 : A325076.argType → A325076.retType := sorry

namespace A325076

/-- Relation that defines `A325076`. -/
def prop : argType → retType → Prop := sorry

/-- `A325076` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A325076` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A325076 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A325076 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A325076 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A325076
