import LOEIS.A263.A263122.Defs

set_option linter.unusedVariables false

/-!
# A263122

Number of (n+3)X(4+3) 0..1 arrays with each row divisible by 15 and column not divisible by 15, read as a binary number with top and left being the most significant bits.

The 16 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A263122

/-- Known terms of `A263122`, starting at index `1`. -/
def data : List retType :=
  [912, 28048, 316392, 3049840, 16751376, 216762400, 2168966344, 20154887792, 138240703248, 1449388911184,
    14047136614696, 130631050676464, 1009951152099984, 9665650741329760, 91463371579618312, 848124382235101936]

/-- `A263122` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A263122 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 17) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 17) : fz n = data[n.toNat - 1]! := sorry

end A263122
