import LOEIS.A029.A029871.Defs

set_option linter.unusedVariables false

/-!
# A029871

Number of connected functions on n points with a loop of length 8.

The 28 terms known to OEIS, indexed from `8`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A029871

/-- Known terms of `A029871`, starting at index `8`. -/
def data : List retType :=
  [1, 1, 6, 25, 104, 384, 1380, 4729, 15806, 51478,
    164788, 519296, 1617066, 4983855, 15233671, 46235252, 139506803, 418838281, 1252174861, 3730058316,
    11077154790, 32808815240, 96953599162, 285945645659, 841909040785, 2475184643011, 7267678432397, 21315839832323]

/-- `A029871` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 36) : A029871 n = data[n.val - 8]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 8 ≤ n) (h : n < 36) : fn n = data[n - 8]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 8 ≤ n) (h : n < 36) : fz n = data[n.toNat - 8]! := sorry

end A029871
