import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A061574

Simple quadratic fields (i.e., with a unique prime factorization).

OEIS offset `-9`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A061574

/-- Index type of `A061574` (OEIS offset `-9`). -/
abbrev argType : Type := {n : Int // -9 ≤ n}

/-- Value type of `A061574`. -/
abbrev retType : Type := Int

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := -9

end A061574

/-- Simple quadratic fields (i.e., with a unique prime factorization). -/
def A061574 : A061574.argType → A061574.retType := sorry

namespace A061574

/-- Relation that defines `A061574`. -/
def prop : argType → retType → Prop := sorry

/-- `A061574` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A061574 n) := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : -9 ≤ n) : fz n = A061574 ⟨n, h⟩ := sorry

end A061574
