import LOEIS.A094.A094268.Defs

set_option linter.unusedVariables false

/-!
# A094268

Starting term of smallest consecutive n-tuples of abundant numbers.

The 3 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A094268

/-- Known terms of `A094268`, starting at index `1`. -/
def data : List retType :=
  [12, 5775, 171078830]

/-- `A094268` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 4) : A094268 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 4) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 4) : fz n = data[n.toNat - 1]! := sorry

end A094268
