import LOEIS.A270.A270225.Defs

set_option linter.unusedVariables false

/-!
# A270225

Lesser of twin primes where both primes are the sum of three squares.

The 50 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A270225

/-- Known terms of `A270225`, starting at index `1`. -/
def data : List retType :=
  [3, 11, 17, 41, 59, 107, 137, 179, 227, 281,
    347, 419, 521, 569, 617, 641, 659, 809, 827, 857,
    881, 1019, 1049, 1091, 1289, 1427, 1451, 1481, 1619, 1667,
    1697, 1721, 1787, 1931, 2027, 2081, 2129, 2267, 2339, 2657,
    2729, 2801, 2969, 3251, 3257, 3299, 3329, 3371, 3467, 3539]

/-- `A270225` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 51) : A270225 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 51) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 51) : fz n = data[n.toNat - 1]! := sorry

end A270225
