import LOEIS.A057.A057701.Defs

set_option linter.unusedVariables false

/-!
# A057701

Twin lucky numbers: (n,m) are lucky numbers with |n-m|=2.

The 56 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A057701

/-- Known terms of `A057701`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 7, 9, 13, 15, 31, 33, 49, 51,
    67, 69, 73, 75, 127, 129, 133, 135, 169, 171,
    193, 195, 235, 237, 259, 261, 283, 285, 319, 321,
    391, 393, 427, 429, 475, 477, 487, 489, 517, 519,
    535, 537, 577, 579, 613, 615, 619, 621, 643, 645,
    727, 729, 739, 741, 883, 885]

/-- `A057701` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 57) : A057701 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 57) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 57) : fz n = data[n.toNat - 1]! := sorry

end A057701
