import LOEIS.A223.A223240.Defs

set_option linter.unusedVariables false

/-!
# A223240

3-loop graph coloring a rectangular array: number of n X 1 0..6 arrays where 0..6 label nodes of a graph with edges 0,1 1,2 2,0 0,3 3,4 4,0 0,5 5,6 6,0 and every array movement to a horizontal or vertical neighbor moves along an edge of this graph.

The 25 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A223240

/-- Known terms of `A223240`, starting at index `1`. -/
def data : List retType :=
  [7, 18, 60, 168, 528, 1536, 4704, 13920, 42144, 125664,
    378528, 1132512, 3403680, 10198752, 30620832, 91813344, 275538336, 826418400, 2479648416, 7438158816,
    22316049312, 66945002208, 200841298080, 602511311328, 1807559099808]

/-- `A223240` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 26) : A223240 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 26) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 26) : fz n = data[n.toNat - 1]! := sorry

end A223240
