import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A244043

Numbers n for new peaks of floor(sigma(n)/primepi(n)).

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A244043

/-- Index type of `A244043` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A244043`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A244043

/-- Numbers n for new peaks of floor(sigma(n)/primepi(n)). -/
def A244043 : A244043.argType → A244043.retType := sorry

namespace A244043

/-- Relation that defines `A244043`. -/
def prop : argType → retType → Prop := sorry

/-- `A244043` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A244043` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A244043 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A244043 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A244043 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A244043
