import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A202283

Decimal expansion of x>0 satisfying x*cosh(2x)=2.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A202283

/-- Index type of `A202283` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A202283`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A202283

/-- Decimal expansion of x>0 satisfying x*cosh(2x)=2. -/
def A202283 : A202283.argType → A202283.retType := sorry

namespace A202283

/-- Relation that defines `A202283`. -/
def prop : argType → retType → Prop := sorry

/-- `A202283` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A202283` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A202283 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A202283 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A202283 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A202283
