import LOEIS.A286.A286964.Defs

set_option linter.unusedVariables false

/-!
# A286964

Binary representation of the diagonal from the origin to the corner of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 229", based on the 5-celled von Neumann neighborhood.

The 22 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A286964

/-- Known terms of `A286964`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 0, 11, 10000, 111, 0, 11001111, 11000000, 11111,
    0, 100000111111, 100000000, 1111111, 100000000000000, 1110011111111, 10110000000000, 110000000111111111, 100000000000000000, 1111000001111111111,
    11000001000000000000, 10000000011111111111]

/-- `A286964` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 22) : A286964 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 22) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 22) : fz n = data[n.toNat]! := sorry

end A286964
