import LOEIS.A149.A149457.Defs

set_option linter.unusedVariables false

/-!
# A149457

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, 0, 0), (0, -1, 1), (0, 1, -1), (1, -1, 1), (1, 1, 0)}.

The 28 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A149457

/-- Known terms of `A149457`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 4, 13, 50, 197, 817, 3449, 15026, 66258,
    296866, 1344971, 6152390, 28369819, 131750885, 615462749, 2890281896, 13635305645, 64586737048, 307031508266,
    1464257058727, 7003257082275, 33582347819527, 161414183206126, 777497336095945, 3752328608212588, 18141590558135163, 87853347328977242]

/-- `A149457` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 28) : A149457 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 28) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 28) : fz n = data[n.toNat]! := sorry

end A149457
