import LOEIS.A173.A173772.Defs

set_option linter.unusedVariables false

/-!
# A173772

a(n) = (4*10^n + 23)/9.

The 21 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A173772

/-- Known terms of `A173772`, starting at index `1`. -/
def data : List retType :=
  [7, 47, 447, 4447, 44447, 444447, 4444447, 44444447, 444444447, 4444444447,
    44444444447, 444444444447, 4444444444447, 44444444444447, 444444444444447, 4444444444444447, 44444444444444447, 444444444444444447, 4444444444444444447, 44444444444444444447,
    444444444444444444447]

/-- `A173772` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 22) : A173772 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 22) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 22) : fz n = data[n.toNat - 1]! := sorry

end A173772
