import LOEIS.A190.A190336.Defs

set_option linter.unusedVariables false

/-!
# A190336

a(n) = n + [n*r/s] + [n*t/s];  r=2, s=sqrt(2), t=1/s.

The 74 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A190336

/-- Known terms of `A190336`, starting at index `1`. -/
def data : List retType :=
  [2, 5, 8, 11, 14, 17, 19, 23, 25, 29,
    31, 34, 37, 40, 43, 46, 49, 52, 54, 58,
    60, 64, 66, 69, 72, 75, 78, 81, 84, 87,
    89, 93, 95, 99, 101, 104, 107, 110, 113, 116,
    118, 122, 124, 128, 130, 134, 136, 139, 142, 145,
    148, 151, 153, 157, 159, 163, 165, 169, 171, 174,
    177, 180, 183, 186, 188, 192, 194, 198, 200, 203,
    206, 209, 212, 215]

/-- `A190336` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 75) : A190336 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 75) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 75) : fz n = data[n.toNat - 1]! := sorry

end A190336
