import LOEIS.A103.A103287.Defs

set_option linter.unusedVariables false

/-!
# A103287

Main diagonal of triangle A103286, in which row n+1 is formed by sorting, in ascending order, the result of the convolution of row n with {2,1}.

The 27 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A103287

/-- Known terms of `A103287`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 5, 12, 30, 77, 202, 540, 1464, 4014,
    11101, 30910, 86542, 243416, 687364, 1947736, 5536216, 15779646, 45088304, 129124925,
    370550378, 1065368994, 3068348448, 8851297414, 25571726480, 73981434516, 214317561452]

/-- `A103287` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 27) : A103287 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 27) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 27) : fz n = data[n.toNat]! := sorry

end A103287
