import LOEIS.A293.A293968.Defs

set_option linter.unusedVariables false

/-!
# A293968

Number of sets of exactly six nonempty words with a total of n letters over n-ary alphabet such that within each prefix of a word every letter of the alphabet is at least as frequent as the subsequent alphabet letter.

The 23 terms known to OEIS, indexed from `14`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A293968

/-- Known terms of `A293968`, starting at index `14`. -/
def data : List retType :=
  [4, 62, 417, 2414, 12190, 57686, 260349, 1143710, 4936266, 21117128,
    90035798, 384416432, 1649398948, 7133455202, 31173583589, 137947781614, 619247938106, 2824375268432, 13105785174035, 61940904739132,
    298438345898409, 1466892183248186, 7358885205363735]

/-- `A293968` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 37) : A293968 n = data[n.val - 14]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 14 ≤ n) (h : n < 37) : fn n = data[n - 14]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 14 ≤ n) (h : n < 37) : fz n = data[n.toNat - 14]! := sorry

end A293968
