import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A076195

Numbers k such that k!! + 2^8 is prime.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A076195

/-- Index type of `A076195` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A076195`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A076195

/-- Numbers k such that k!! + 2^8 is prime. -/
def A076195 : A076195.argType → A076195.retType := sorry

namespace A076195

/-- Relation that defines `A076195`. -/
def prop : argType → retType → Prop := sorry

/-- `A076195` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A076195` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A076195 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A076195 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A076195 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A076195
