import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A347212

a(n) is the next Ulam number (A002858) after 2^(n-1).

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A347212

/-- Index type of `A347212` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A347212`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A347212

/-- a(n) is the next Ulam number (A002858) after 2^(n-1). -/
def A347212 : A347212.argType → A347212.retType := sorry

namespace A347212

/-- Relation that defines `A347212`. -/
def prop : argType → retType → Prop := sorry

/-- `A347212` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A347212` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A347212 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A347212 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A347212 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A347212
