import LOEIS.A216.A216869.Defs

set_option linter.unusedVariables false

/-!
# A216869

The smallest non-constant arithmetic progression of integer squares of maximal length three.

The 3 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A216869

/-- Known terms of `A216869`, starting at index `1`. -/
def data : List retType :=
  [1, 25, 49]

/-- `A216869` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 4) : A216869 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 4) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 4) : fz n = data[n.toNat - 1]! := sorry

end A216869
