import LOEIS.A292.A292752.Defs

set_option linter.unusedVariables false

/-!
# A292752

Dimensions of centralizer algebras of groups associated with Z_4-codes.

The 24 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A292752

/-- Known terms of `A292752`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 16, 108, 811, 6513, 54706, 472818, 4157701,
    36931023, 329937796, 2957233128, 26554062991, 238681391133, 2146606641286, 19311830377038, 173768326420681, 1563724202922843, 14072564151989176,
    126648308996320548, 1139810939108974771, 10258179242691222153, 92323017137773245466]

/-- `A292752` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 24) : A292752 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 24) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 24) : fz n = data[n.toNat]! := sorry

end A292752
