import LOEIS.A005.A005791.Defs

set_option linter.unusedVariables false

/-!
# A005791

5-dimensional Catalan numbers.

The 14 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A005791

/-- Known terms of `A005791`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 42, 6006, 1662804, 701149020, 396499770810, 278607172289160, 231471904322784840, 219738059326729823880,
    232553551737813227594400, 269396678720275351794712800, 336839101096824285057473785200, 449620757769949216266129125515200]

/-- `A005791` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 14) : A005791 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 14) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 14) : fz n = data[n.toNat]! := sorry

end A005791
