import LOEIS.A325.A325250.Defs

set_option linter.unusedVariables false

/-!
# A325250

Number of integer partitions of n whose omega-sequence is strict (no repeated parts).

The 51 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A325250

/-- Known terms of `A325250`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 2, 3, 2, 5, 2, 5, 4,
    6, 2, 11, 3, 10, 12, 17, 12, 31, 22,
    42, 47, 57, 60, 98, 94, 119, 143, 174, 182,
    256, 253, 321, 365, 425, 480, 615, 645, 803, 946,
    1180, 1341, 1766, 2021, 2607, 3145, 3951, 4727, 6123, 7236,
    9136]

/-- `A325250` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 51) : A325250 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 51) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 51) : fz n = data[n.toNat]! := sorry

end A325250
