import LOEIS.A252.A252640.Defs

set_option linter.unusedVariables false

/-!
# A252640

T(n,k)=Number of (n+2)X(k+2) 0..3 arrays with every 3X3 subblock row and diagonal sum equal to 0 3 4 6 or 7 and every 3X3 column and antidiagonal sum not equal to 0 3 4 6 or 7.

The 36 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A252640

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [572, 1013, 687, 1758, 1684, 1189, 3162, 4026, 4226, 2230,
    6598, 8253, 12840, 10259, 4382, 13038, 22701, 29463, 39492, 28978,
    8697, 24852, 56953, 110665, 95904, 145594, 80304, 17046, 51396, 121016,
    355574, 448323, 395940, 527688, 205127, 34424]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 37) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 37) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 37) : flatFz n = flatData[n.toNat - 1]! := sorry

end A252640
