import LOEIS.A229.A229107.Defs

set_option linter.unusedVariables false

/-!
# A229107

Palindromic prime time display in hours, minutes, seconds on a six-digit 24-hour digital clock.

The 42 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A229107

/-- Known terms of `A229107`, starting at index `1`. -/
def data : List retType :=
  [2, 3, 5, 7, 11, 101, 131, 151, 313, 353,
    727, 757, 919, 929, 10301, 10501, 10601, 11311, 11411, 12421,
    12721, 12821, 13331, 13831, 13931, 14341, 14741, 15451, 15551, 30103,
    30203, 30403, 30703, 30803, 31013, 31513, 32323, 32423, 33533, 34543,
    34843, 35053]

/-- `A229107` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 43) : A229107 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 43) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 43) : fz n = data[n.toNat - 1]! := sorry

end A229107
