import LOEIS.A101.A101810.Defs

set_option linter.unusedVariables false

/-!
# A101810

Number of compositions (ordered partitions) of the n-th prime into n nonnegative integers.

The 19 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A101810

/-- Known terms of `A101810`, starting at index `1`. -/
def data : List retType :=
  [1, 4, 21, 120, 1365, 8568, 100947, 657800, 7888725, 163011640,
    1121099408, 22595200368, 266783135710, 1889912732400, 22512762077400, 443643407165376, 8550047575185300, 62724534168736440, 1206459883091241450]

/-- `A101810` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 20) : A101810 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 20) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 20) : fz n = data[n.toNat - 1]! := sorry

end A101810
