import LOEIS.A123.A123845.Defs

set_option linter.unusedVariables false

/-!
# A123845

Number of ways, counted up to symmetry, to build a contiguous building with n LEGO blocks of size 5 X 5 which is symmetric after a rotation by 180 degrees.

The 8 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A123845

/-- Known terms of `A123845`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 29, 143, 3497, 22303, 503847, 3778105]

/-- `A123845` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 9) : A123845 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 9) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 9) : fz n = data[n.toNat - 1]! := sorry

end A123845
