import LOEIS.A113.A113335.Defs

set_option linter.unusedVariables false

/-!
# A113335

a(n) = 3^5 * binomial(n+4, 5).

The 30 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A113335

/-- Known terms of `A113335`, starting at index `1`. -/
def data : List retType :=
  [243, 1458, 5103, 13608, 30618, 61236, 112266, 192456, 312741, 486486,
    729729, 1061424, 1503684, 2082024, 2825604, 3767472, 4944807, 6399162, 8176707, 10328472,
    12910590, 15984540, 19617390, 23882040, 28857465, 34628958, 41288373, 48934368, 57672648, 67616208]

/-- `A113335` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 31) : A113335 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 31) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 31) : fz n = data[n.toNat - 1]! := sorry

end A113335
