import LOEIS.A256.A256863.Defs

set_option linter.unusedVariables false

/-!
# A256863

Primes that can't be written in form a^2 + b^4.

The 56 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A256863

/-- Known terms of `A256863`, starting at index `1`. -/
def data : List retType :=
  [3, 7, 11, 13, 19, 23, 29, 31, 43, 47,
    53, 59, 61, 67, 71, 73, 79, 83, 89, 103,
    107, 109, 113, 127, 131, 139, 149, 151, 157, 163,
    167, 173, 179, 191, 193, 199, 211, 223, 227, 229,
    233, 239, 251, 263, 269, 271, 283, 293, 307, 311,
    313, 317, 331, 347, 349, 353]

/-- `A256863` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 57) : A256863 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 57) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 57) : fz n = data[n.toNat - 1]! := sorry

end A256863
