import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A149293

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 1), (-1, 0, 1), (-1, 1, 0), (1, 0, -1), (1, 0, 1)}.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A149293

/-- Index type of `A149293` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A149293`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A149293

/-- Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 1), (-1, 0, 1), (-1, 1, 0), (1, 0, -1), (1, 0, 1)}. -/
def A149293 : A149293.argType → A149293.retType := sorry

namespace A149293

/-- Relation that defines `A149293`. -/
def prop : argType → retType → Prop := sorry

/-- `A149293` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A149293` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A149293 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A149293 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A149293 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A149293
