import LOEIS.A234.A234009.Defs

set_option linter.unusedVariables false

/-!
# A234009

Free polyominoes with 4n squares, having 90-degree rotational symmetry about a square corner.

The 14 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A234009

/-- Known terms of `A234009`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 4, 10, 35, 114, 403, 1432, 5239, 19271,
    71820, 269417, 1017920, 3864879]

/-- `A234009` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 15) : A234009 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 15) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 15) : fz n = data[n.toNat - 1]! := sorry

end A234009
