import LOEIS.A318.A318354.Defs

set_option linter.unusedVariables false

/-!
# A318354

Triangle read by rows: T(n,k) is the number of permutations p of {1..n} such that p(1)=k and p(i+1) < p(i) iff a strict majority of {1..n} \ {p(1)..p(i)} are < p(i).

The 55 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A318354

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 2, 1, 2, 5, 3, 3, 5,
    16, 11, 8, 11, 16, 62, 46, 35, 35, 46,
    62, 286, 224, 178, 143, 178, 224, 286, 1519, 1233,
    1009, 831, 831, 1009, 1233, 1519, 9184, 7665, 6432, 5423,
    4592, 5423, 6432, 7665, 9184, 62000, 52816, 45151, 38719, 33296,
    33296, 38719, 45151, 52816, 62000]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 56) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 56) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 56) : flatFz n = flatData[n.toNat - 1]! := sorry

end A318354
