import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A245468

Numbers x such that sigma(x)=sigma(T(x)), where sigma(x) is the sum of the divisors of x and T(x) the transform defined in A243993.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A245468

/-- Index type of `A245468` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A245468`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A245468

/-- Numbers x such that sigma(x)=sigma(T(x)), where sigma(x) is the sum of the divisors of x and T(x) the transform defined in A243993. -/
def A245468 : A245468.argType → A245468.retType := sorry

namespace A245468

/-- Relation that defines `A245468`. -/
def prop : argType → retType → Prop := sorry

/-- `A245468` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A245468` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A245468 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A245468 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A245468 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A245468
