import LOEIS.A015.A015580.Defs

set_option linter.unusedVariables false

/-!
# A015580

Expansion of x/(1 - 9*x - 4*x^2).

The 22 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A015580

/-- Known terms of `A015580`, starting at index `0`. -/
def data : List retType :=
  [0, 1, 9, 85, 801, 7549, 71145, 670501, 6319089, 59553805,
    561260601, 5289560629, 49851088065, 469818035101, 4427766668169, 41729172153925, 393273616058001, 3706379233137709, 34930507562471385, 329200084994793301,
    3102522795203025249, 29239505496806400445]

/-- `A015580` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 22) : A015580 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 22) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 22) : fz n = data[n.toNat]! := sorry

end A015580
