import LOEIS.A229.A229585.Defs

set_option linter.unusedVariables false

/-!
# A229585

Number of defective 3-colorings of an n X 7 0..2 array connected horizontally and antidiagonally with exactly one mistake, and colors introduced in row-major 0..2 order.

The 14 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A229585

/-- Known terms of `A229585`, starting at index `1`. -/
def data : List retType :=
  [96, 5724, 264300, 11035044, 435326724, 16551428868, 613195191972, 22285439501940, 798023885879412, 28242628279003332,
    990013172442084324, 34429588531063458516, 1189375483329032617620, 40853134231990887545316]

/-- `A229585` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 15) : A229585 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 15) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 15) : fz n = data[n.toNat - 1]! := sorry

end A229585
