import LOEIS.A227.A227184.Defs

set_option linter.unusedVariables false

/-!
# A227184

a(n) = product of parts of the unordered partition encoded with the runlengths of binary expansion of n.

The 76 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A227184

/-- Known terms of `A227184`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 1, 2, 4, 1, 2, 3, 9, 4,
    1, 8, 6, 2, 3, 4, 16, 9, 4, 18,
    16, 1, 8, 27, 12, 6, 2, 12, 8, 3,
    4, 5, 25, 16, 9, 32, 36, 4, 18, 48,
    81, 16, 1, 32, 54, 8, 27, 64, 20, 12,
    6, 24, 24, 2, 12, 36, 15, 8, 3, 16,
    10, 4, 5, 6, 36, 25, 16, 50, 64, 9,
    32, 75, 144, 36, 4, 72]

/-- `A227184` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 76) : A227184 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 76) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 76) : fz n = data[n.toNat]! := sorry

end A227184
