import LOEIS.A091.A091074.Defs

set_option linter.unusedVariables false

/-!
# A091074

Fibonacci sequence beginning 12, 67.

The 32 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A091074

/-- Known terms of `A091074`, starting at index `1`. -/
def data : List retType :=
  [12, 67, 79, 146, 225, 371, 596, 967, 1563, 2530,
    4093, 6623, 10716, 17339, 28055, 45394, 73449, 118843, 192292, 311135,
    503427, 814562, 1317989, 2132551, 3450540, 5583091, 9033631, 14616722, 23650353, 38267075,
    61917428, 100184503]

/-- `A091074` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 33) : A091074 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 33) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 33) : fz n = data[n.toNat - 1]! := sorry

end A091074
