import LOEIS.A153.A153943.Defs

set_option linter.unusedVariables false

/-!
# A153943

Number of planar n X n X n binary triangular grids symmetric both under 120 degree rotation and reflection with no more than 5 ones in any 4 X 4 X 4 subtriangle.

The 27 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A153943

/-- Known terms of `A153943`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 2, 3, 4, 8, 14, 49, 79, 253,
    741, 2335, 6399, 37905, 102246, 593203, 2884877, 16569870, 80670284, 832584915,
    3998999249, 40528587997, 352270529241, 3516190442125, 29997079375598, 543310308646601, 4559849026688799]

/-- `A153943` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 27) : A153943 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 27) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 27) : fz n = data[n.toNat]! := sorry

end A153943
