import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A104363

Euler's totient of A104357(n) = A104350(n) - 1.

OEIS offset `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A104363

/-- Index type of `A104363` (OEIS offset `2`). -/
abbrev argType : Type := {n : Nat // 2 ≤ n}

/-- Value type of `A104363`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 2

end A104363

/-- Euler's totient of A104357(n) = A104350(n) - 1. -/
def A104363 : A104363.argType → A104363.retType := sorry

namespace A104363

/-- Relation that defines `A104363`. -/
def prop : argType → retType → Prop := sorry

/-- `A104363` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A104363` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A104363 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 2 ≤ n) : fn n = A104363 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 2 ≤ n) : fz n = A104363 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 2 ≤ n) : fn n = fz (n : Int) := sorry

end A104363
