import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A243021

Numbers n such that n appears in the sequence beginning with the digit-sum of n and extended by adding successive digit-sums.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A243021

/-- Index type of `A243021` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A243021`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A243021

/-- Numbers n such that n appears in the sequence beginning with the digit-sum of n and extended by adding successive digit-sums. -/
def A243021 : A243021.argType → A243021.retType := sorry

namespace A243021

/-- Relation that defines `A243021`. -/
def prop : argType → retType → Prop := sorry

/-- `A243021` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A243021` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A243021 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A243021 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A243021 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A243021
