import LOEIS.A303.A303623.Defs

set_option linter.unusedVariables false

/-!
# A303623

Number of nX7 0..1 arrays with every element equal to 0, 2, 3, 4, 5 or 6 horizontally, diagonally or antidiagonally adjacent elements, with upper left element zero.

The 15 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A303623

/-- Known terms of `A303623`, starting at index `1`. -/
def data : List retType :=
  [1, 496, 5411, 160807, 5249045, 179884814, 6323564388, 224091914399, 7966090548780, 283582960504149,
    10101258867472961, 359903623078870120, 12824695714808614687, 457013934122432156738, 16286250681449999285061]

/-- `A303623` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 16) : A303623 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 16) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 16) : fz n = data[n.toNat - 1]! := sorry

end A303623
