import LOEIS.A286.A286420.Defs

set_option linter.unusedVariables false

/-!
# A286420

Positions of 0 in A286419; complement of A286421.

The 59 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A286420

/-- Known terms of `A286420`, starting at index `1`. -/
def data : List retType :=
  [1, 7, 8, 10, 15, 18, 19, 25, 26, 28,
    31, 32, 37, 43, 44, 46, 51, 54, 55, 60,
    66, 67, 69, 72, 73, 79, 80, 82, 87, 90,
    91, 97, 98, 100, 103, 104, 109, 115, 116, 118,
    121, 122, 128, 129, 131, 136, 139, 140, 145, 151,
    152, 154, 159, 162, 163, 169, 170, 172, 175]

/-- `A286420` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 60) : A286420 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 60) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 60) : fz n = data[n.toNat - 1]! := sorry

end A286420
