import LOEIS.A097.A097006.Defs

set_option linter.unusedVariables false

/-!
# A097006

Consider the function f(x)=sigma(phi(x))=A062402(x) iterated with initial value n!; a(n) is the path-length of trajectory.

The 13 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A097006

/-- Known terms of `A097006`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 2, 2, 5, 6, 5, 10, 10,
    17, 49, 91]

/-- `A097006` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 13) : A097006 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 13) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 13) : fz n = data[n.toNat]! := sorry

end A097006
