import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A267619

Number of 3 X n arrays containing n copies of 0..3-1 with every element equal to at least one horizontal or antidiagonal neighbor and the top left element equal to 0.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A267619

/-- Index type of `A267619` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A267619`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A267619

/-- Number of 3 X n arrays containing n copies of 0..3-1 with every element equal to at least one horizontal or antidiagonal neighbor and the top left element equal to 0. -/
def A267619 : A267619.argType → A267619.retType := sorry

namespace A267619

/-- Relation that defines `A267619`. -/
def prop : argType → retType → Prop := sorry

/-- `A267619` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A267619` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A267619 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A267619 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A267619 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A267619
