import LOEIS.A035.A035042.Defs

set_option linter.unusedVariables false

/-!
# A035042

a(n) = 2^n - C(n,0)- ... - C(n,9).

The 37 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A035042

/-- Known terms of `A035042`, starting at index `0`. -/
def data : List retType :=
  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 12, 79, 378, 1471, 4944, 14893, 41226, 106762, 262144,
    616666, 1401292, 3096514, 6690448, 14198086, 29703676, 61450327, 126025204, 256737233, 520381366,
    1050777737, 2115862624, 4251885323, 8531819446, 17102205992, 34256863240, 68584333940]

/-- `A035042` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 37) : A035042 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 37) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 37) : fz n = data[n.toNat]! := sorry

end A035042
