import LOEIS.A208.A208864.Defs

set_option linter.unusedVariables false

/-!
# A208864

T(n,k)=Number of nXk 0..3 arrays with new values 0..3 introduced in row major order and no element equal to more than one of its immediate leftward or upward or left-upward diagonal neighbors.

The 38 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A208864

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 2, 2, 5, 11, 5, 15, 127, 127, 15,
    51, 1691, 5796, 1691, 51, 187, 23047, 273049, 273049, 23047,
    187, 715, 315203, 12883280, 44452082, 12883280, 315203, 715, 2795, 4313071,
    607924387, 7240366702, 7240366702, 607924387, 4313071, 2795, 11051, 59022155]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 39) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 39) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 39) : flatFz n = flatData[n.toNat - 1]! := sorry

end A208864
