import LOEIS.A271.A271412.Defs

set_option linter.unusedVariables false

/-!
# A271412

Partial sums of the number of active (ON, black) cells in n-th stage of growth of two-dimensional cellular automaton defined by "Rule 358", based on the 5-celled von Neumann neighborhood.

The 45 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A271412

/-- Known terms of `A271412`, starting at index `0`. -/
def data : List retType :=
  [1, 6, 10, 30, 39, 76, 100, 164, 189, 266,
    335, 504, 548, 720, 824, 1096, 1180, 1416, 1596, 2008,
    2176, 2584, 2792, 3312, 3553, 4094, 4466, 5318, 5694, 6622,
    7035, 8044, 8560, 9776, 10296, 11584, 12104, 13336, 14005, 15526,
    16271, 17988, 18736, 20516, 21429]

/-- `A271412` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 45) : A271412 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 45) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 45) : fz n = data[n.toNat]! := sorry

end A271412
