import LOEIS.A067.A067782.Defs

set_option linter.unusedVariables false

/-!
# A067782

Minimal delay time for an n-element sorting network.

The 17 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A067782

/-- Known terms of `A067782`, starting at index `1`. -/
def data : List retType :=
  [0, 1, 3, 3, 5, 5, 6, 6, 7, 7,
    8, 8, 9, 9, 9, 9, 10]

/-- `A067782` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 18) : A067782 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 18) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 18) : fz n = data[n.toNat - 1]! := sorry

end A067782
