import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A133434

Records in A084739.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A133434

/-- Index type of `A133434` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A133434`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A133434

/-- Records in A084739. -/
def A133434 : A133434.argType → A133434.retType := sorry

namespace A133434

/-- Relation that defines `A133434`. -/
def prop : argType → retType → Prop := sorry

/-- `A133434` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A133434` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A133434 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A133434 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A133434 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A133434
