import LOEIS.A106.A106408.Defs

set_option linter.unusedVariables false

/-!
# A106408

Triangle, read by rows, where T(1,1) = 1; T(2,1) = T(2,2) = 2; for n > 2, T(n,n) = T(n-1,n-1) + T(n-2,n-2); T(n+1,n) = 2 * T(n,n); for all other entries, T(n,k) = T(n-1,k) + T(n-2,k).

The 66 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A106408

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 2, 2, 3, 4, 3, 5, 6, 6, 5,
    8, 10, 9, 10, 8, 13, 16, 15, 15, 16,
    13, 21, 26, 24, 25, 24, 26, 21, 34, 42,
    39, 40, 40, 39, 42, 34, 55, 68, 63, 65,
    64, 65, 63, 68, 55, 89, 110, 102, 105, 104,
    104, 105, 102, 110, 89, 144, 178, 165, 170, 168,
    169, 168, 170, 165, 178, 144]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 67) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 67) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 67) : flatFz n = flatData[n.toNat - 1]! := sorry

end A106408
