import LOEIS.A064.A064849.Defs

set_option linter.unusedVariables false

/-!
# A064849

Period of continued fraction for sqrt(3)*n.

The 82 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A064849

/-- Known terms of `A064849`, starting at index `1`. -/
def data : List retType :=
  [2, 2, 2, 2, 4, 8, 2, 4, 10, 4,
    2, 8, 6, 2, 2, 8, 6, 20, 4, 8,
    14, 8, 8, 12, 16, 2, 30, 2, 16, 4,
    18, 16, 10, 20, 16, 20, 18, 8, 6, 12,
    2, 12, 8, 8, 6, 20, 20, 20, 30, 36,
    6, 2, 8, 68, 14, 2, 16, 32, 22, 4,
    38, 18, 40, 36, 6, 28, 10, 20, 40, 8,
    4, 40, 18, 22, 16, 12, 28, 2, 46, 20,
    98, 8]

/-- `A064849` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 83) : A064849 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 83) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 83) : fz n = data[n.toNat - 1]! := sorry

end A064849
