import LOEIS.A221.A221688.Defs

set_option linter.unusedVariables false

/-!
# A221688

T(n,k)=Number of nXk arrays of occupancy after each element stays put or moves to some king-move neighbor, without consecutive moves in the same direction.

The 31 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A221688

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 3, 3, 6, 35, 6, 13, 396, 396, 13,
    28, 4429, 17480, 4429, 28, 60, 49387, 780692, 780692, 49387,
    60, 129, 550264, 34704624, 140268025, 34704624, 550264, 129, 277, 6129659,
    1542552756]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 32) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 32) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 32) : flatFz n = flatData[n.toNat - 1]! := sorry

end A221688
