import LOEIS.A191.A191645.Defs

set_option linter.unusedVariables false

/-!
# A191645

Numerators of the n-th partial "harmonic" sum of 1 + inverse semiprimes.

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A191645

/-- Known terms of `A191645`, starting at index `1`. -/
def data : List retType :=
  [5, 17, 55, 293, 2141, 445, 457, 5153, 131597, 1745411,
    1772711, 30586537, 31024117, 597115873, 604577173, 14050770329, 99311504603, 100230122303, 101081931443, 101903852543]

/-- `A191645` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 21) : A191645 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : fz n = data[n.toNat - 1]! := sorry

end A191645
