import LOEIS.A239.A239198.Defs

set_option linter.unusedVariables false

/-!
# A239198

Expansion of -(3*x^5+sqrt(-7*x^2-6*x+1)*(3*x^4+5*x^3-11*x^2-7*x+2)-24*x^4-34*x^3+10*x^2+15*x-2) / (7*x^5+sqrt(-7*x^2-6*x+1)*(3*x^4+6*x^3-2*x^2+6*x-5)-15*x^4-12*x^3-12*x^2-19*x+3).

The 21 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A239198

/-- Known terms of `A239198`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 13, 67, 377, 2235, 13701, 85947, 548209, 3540851,
    23093885, 151793203, 1004023273, 6675725867, 44581355765, 298829626795, 2009477057761, 13550281076451, 91594501130989, 620471833255971,
    4211165312423001]

/-- `A239198` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 22) : A239198 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 22) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 22) : fz n = data[n.toNat - 1]! := sorry

end A239198
