import LOEIS.A150.A150536.Defs

set_option linter.unusedVariables false

/-!
# A150536

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 0), (-1, 0, 0), (0, 1, -1), (0, 1, 1), (1, 0, 1)}.

The 28 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A150536

/-- Known terms of `A150536`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 7, 26, 102, 420, 1762, 7546, 32776, 143740,
    636509, 2837470, 12723564, 57356783, 259622346, 1179671953, 5378030204, 24587733520, 112709464907, 517854785497,
    2384306458458, 10998978703826, 50826959867930, 235249720011487, 1090445475090001, 5061348100981751, 23522089805096353, 109444564002516165]

/-- `A150536` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 28) : A150536 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 28) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 28) : fz n = data[n.toNat]! := sorry

end A150536
