import LOEIS.A312.A312350.Defs

set_option linter.unusedVariables false

/-!
# A312350

Coordination sequence Gal.6.420.3 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A312350

/-- Known terms of `A312350`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 8, 14, 17, 21, 26, 28, 35, 41,
    43, 49, 49, 56, 60, 65, 69, 75, 75, 82,
    89, 87, 99, 95, 107, 107, 112, 115, 121, 123,
    130, 140, 132, 148, 139, 155, 155, 160, 164, 168,
    170, 176, 188, 178, 198, 186, 204, 202, 206, 210]

/-- `A312350` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A312350 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A312350
