import LOEIS.A228.A228426.Defs

set_option linter.unusedVariables false

/-!
# A228426

Numerator of Sum(i=1..n-1, 1/i^(2*n-1)).

The 9 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A228426

/-- Known terms of `A228426`, starting at index `1`. -/
def data : List retType :=
  [0, 1, 33, 282251, 5170139875, 36297634492764230063, 43540989124396091246149, 248033379485570104849994099153187946961, 17204019459451797001978107903201762504044841332131]

/-- `A228426` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 10) : A228426 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 10) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 10) : fz n = data[n.toNat - 1]! := sorry

end A228426
