import LOEIS.A390.A390775.Defs

set_option linter.unusedVariables false

/-!
# A390775

a(n) = Sum_{k=0..floor(n/3)} 2^k * 3^(n-3*k) * binomial(k,2*(n-3*k)).

The 41 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A390775

/-- Known terms of `A390775`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 0, 2, 0, 0, 4, 12, 0, 8,
    72, 0, 16, 288, 144, 32, 960, 1440, 64, 2880,
    8640, 1856, 8064, 40320, 24448, 21504, 161280, 194048, 76032, 580608,
    1162240, 511488, 1935360, 5808128, 4070400, 6331392, 25550848, 28182528, 23721984, 102195200,
    166146048]

/-- `A390775` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 41) : A390775 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 41) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 41) : fz n = data[n.toNat]! := sorry

end A390775
