import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A105199

Decimal expansion of arctan(2).

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A105199

/-- Index type of `A105199` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A105199`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A105199

/-- Decimal expansion of arctan(2). -/
def A105199 : A105199.argType → A105199.retType := sorry

namespace A105199

/-- Relation that defines `A105199`. -/
def prop : argType → retType → Prop := sorry

/-- `A105199` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A105199` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A105199 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A105199 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A105199 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A105199
