import LOEIS.A091.A091617.Defs

set_option linter.unusedVariables false

/-!
# A091617

Number of compositions (ordered partitions) of n such that some part is repeated consecutively 3 times and no part is repeated consecutively more than 3 times.

The 34 terms known to OEIS, indexed from `3`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A091617

/-- Known terms of `A091617`, starting at index `3`. -/
def data : List retType :=
  [1, 0, 2, 5, 11, 22, 48, 105, 223, 468,
    979, 2037, 4224, 8710, 17906, 36693, 74973, 152795, 310669, 630353,
    1276544, 2580614, 5208522, 10496954, 21126102, 42464498, 85255651, 170980512, 342553389, 685641724,
    1371134291, 2739685107, 5469923466, 10912945300]

/-- `A091617` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 37) : A091617 n = data[n.val - 3]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 3 ≤ n) (h : n < 37) : fn n = data[n - 3]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 3 ≤ n) (h : n < 37) : fz n = data[n.toNat - 3]! := sorry

end A091617
