import LOEIS.A194.A194999.Defs

set_option linter.unusedVariables false

/-!
# A194999

Number of lower triangles of a 3 X 3 0..n array with each element differing from all of its horizontal and vertical neighbors by one.

The 52 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A194999

/-- Known terms of `A194999`, starting at index `1`. -/
def data : List retType :=
  [2, 20, 42, 66, 90, 114, 138, 162, 186, 210,
    234, 258, 282, 306, 330, 354, 378, 402, 426, 450,
    474, 498, 522, 546, 570, 594, 618, 642, 666, 690,
    714, 738, 762, 786, 810, 834, 858, 882, 906, 930,
    954, 978, 1002, 1026, 1050, 1074, 1098, 1122, 1146, 1170,
    1194, 1218]

/-- `A194999` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 53) : A194999 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 53) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 53) : fz n = data[n.toNat - 1]! := sorry

end A194999
