import LOEIS.A028.A028705.Defs

set_option linter.unusedVariables false

/-!
# A028705

Expansion of (theta_3(z)*theta_3(3z)*theta_3(9z)+theta_2(z)*theta_2(3z)*theta_2(9z))^4.

The 48 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A028705

/-- Known terms of `A028705`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 0, 0, 8, 0, 0, 0, 24, 0,
    0, 0, 40, 32, 0, 0, 88, 192, 0, 0,
    240, 416, 0, 0, 376, 640, 384, 0, 448, 1728,
    1536, 0, 984, 3520, 2304, 0, 1680, 4096, 4608, 2048,
    1552, 6912, 11136, 4096, 2400, 13088, 13824, 6144]

/-- `A028705` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 48) : A028705 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 48) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 48) : fz n = data[n.toNat]! := sorry

end A028705
