import LOEIS.A099.A099225.Defs

set_option linter.unusedVariables false

/-!
# A099225

Numbers of the form m^k+k, with m and k > 1.

The 54 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A099225

/-- Known terms of `A099225`, starting at index `1`. -/
def data : List retType :=
  [6, 11, 18, 20, 27, 30, 37, 38, 51, 66,
    67, 70, 83, 85, 102, 123, 128, 135, 146, 171,
    198, 219, 227, 248, 258, 260, 264, 291, 326, 346,
    363, 402, 443, 486, 515, 521, 531, 578, 627, 629,
    678, 731, 732, 735, 786, 843, 902, 963, 1003, 1026,
    1029, 1034, 1091, 1158]

/-- `A099225` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 55) : A099225 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 55) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 55) : fz n = data[n.toNat - 1]! := sorry

end A099225
