import LOEIS.A330.A330617.Defs

set_option linter.unusedVariables false

/-!
# A330617

Triangle read by rows: T(n,k) is the number of paths from node 0 to k in a directed graph with n+1 vertices labeled 0, 1, ..., n and edges leading from i to i+1 for all i, and from i to i+2 for even i and from i to i-2 for odd i.

The 91 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A330617

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 1, 2, 1, 2, 2, 2,
    1, 2, 2, 2, 4, 1, 3, 2, 4, 4,
    4, 1, 3, 2, 4, 4, 4, 8, 1, 4,
    2, 6, 4, 8, 8, 8, 1, 4, 2, 6,
    4, 8, 8, 8, 16, 1, 5, 2, 8, 4,
    12, 8, 16, 16, 16, 1, 5, 2, 8, 4,
    12, 8, 16, 16, 16, 32, 1, 6, 2, 10,
    4, 16, 8, 24, 16, 32, 32, 32, 1, 6,
    2, 10, 4, 16, 8, 24, 16, 32, 32, 32,
    64]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 91) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 91) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 91) : flatFz n = flatData[n.toNat]! := sorry

end A330617
