import LOEIS.A314.A314755.Defs

set_option linter.unusedVariables false

/-!
# A314755

Coordination sequence Gal.6.466.3 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A314755

/-- Known terms of `A314755`, starting at index `0`. -/
def data : List retType :=
  [1, 5, 9, 13, 19, 23, 27, 34, 39, 41,
    45, 51, 55, 59, 66, 71, 75, 79, 83, 87,
    91, 98, 103, 107, 113, 117, 119, 123, 130, 135,
    139, 145, 149, 153, 157, 162, 167, 171, 177, 181,
    185, 191, 196, 199, 203, 209, 213, 217, 223, 228]

/-- `A314755` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A314755 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A314755
