import LOEIS.A311.A311991.Defs

set_option linter.unusedVariables false

/-!
# A311991

Coordination sequence Gal.4.67.2 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A311991

/-- Known terms of `A311991`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 8, 13, 17, 23, 27, 31, 36, 38,
    45, 49, 55, 57, 64, 62, 73, 75, 83, 83,
    92, 86, 101, 101, 111, 109, 120, 110, 129, 127,
    139, 135, 148, 134, 157, 153, 167, 161, 176, 158,
    185, 179, 195, 187, 204, 182, 213, 205, 223, 213]

/-- `A311991` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A311991 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A311991
