import LOEIS.A103.A103714.Defs

set_option linter.unusedVariables false

/-!
# A103714

Decimal expansion of the area of the surface generated by revolving one arch of the cosine curve about the x-axis.

The 105 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A103714

/-- Known terms of `A103714`, starting at index `2`. -/
def data : List retType :=
  [1, 4, 4, 2, 3, 5, 9, 9, 4, 4,
    8, 4, 1, 4, 0, 9, 3, 9, 2, 9,
    3, 7, 5, 4, 6, 5, 5, 3, 9, 6,
    0, 1, 3, 3, 5, 3, 5, 8, 0, 5,
    4, 1, 1, 5, 2, 3, 5, 9, 5, 2,
    1, 0, 0, 1, 2, 9, 2, 1, 7, 6,
    5, 3, 4, 9, 2, 2, 6, 2, 6, 0,
    7, 2, 9, 7, 2, 2, 1, 9, 5, 3,
    9, 3, 0, 2, 9, 2, 4, 3, 8, 4,
    2, 1, 9, 5, 5, 3, 9, 6, 5, 8,
    6, 5, 9, 8, 6]

/-- `A103714` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 107) : A103714 n = data[n.val - 2]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 107) : fn n = data[n - 2]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 107) : fz n = data[n.toNat - 2]! := sorry

end A103714
