import LOEIS.A371.A371111.Defs

set_option linter.unusedVariables false

/-!
# A371111

Ternary numbers that are concatenated runs C(1)A(1)B(1)C(2)A(2)B(2)...C(k)A(k)B(k), where A(i) is a run of 1's, B(i) a run of 0's, and C(i) a run of 2's, for i = 1..k.

The 32 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A371111

/-- Known terms of `A371111`, starting at index `1`. -/
def data : List retType :=
  [210, 2100, 2110, 2210, 21000, 21100, 21110, 22100, 22110, 22210,
    210000, 210210, 211000, 211100, 211110, 221000, 221100, 221110, 222100, 222110,
    222210, 2100000, 2100210, 2102100, 2102110, 2102210, 2110000, 2110210, 2111000, 2111100,
    2111110, 2210000]

/-- `A371111` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 33) : A371111 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 33) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 33) : fz n = data[n.toNat - 1]! := sorry

end A371111
