import LOEIS.A110.A110797.Defs

set_option linter.unusedVariables false

/-!
# A110797

a(0) = 1, a(1) = 2; then all the products generated by these numbers, then the next number 3 and so on.

The 62 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A110797

/-- Known terms of `A110797`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 3, 6, 4, 8, 12, 24, 5, 10,
    15, 20, 30, 40, 60, 120, 6, 12, 18, 24,
    30, 36, 48, 60, 72, 90, 120, 144, 180, 240,
    360, 720, 7, 14, 21, 28, 35, 42, 42, 56,
    70, 84, 84, 105, 126, 140, 168, 168, 210, 210,
    252, 280, 336, 420, 420, 504, 630, 840, 840, 1008,
    1260, 1680]

/-- `A110797` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 62) : A110797 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 62) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 62) : fz n = data[n.toNat]! := sorry

end A110797
