import LOEIS.A363.A363994.Defs

set_option linter.unusedVariables false

/-!
# A363994

a(n) is the number of partitions of n whose difference multiset has no duplicates; see Comments.

The 58 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A363994

/-- Known terms of `A363994`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 2, 3, 3, 4, 5, 7, 6,
    10, 11, 11, 15, 18, 18, 25, 29, 28, 38,
    44, 47, 54, 67, 68, 84, 88, 102, 114, 137,
    132, 167, 180, 204, 214, 261, 264, 315, 328, 377,
    414, 476, 473, 564, 603, 677, 708, 820, 846, 969,
    1028, 1131, 1214, 1364, 1414, 1596, 1701, 1858]

/-- `A363994` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 58) : A363994 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 58) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 58) : fz n = data[n.toNat]! := sorry

end A363994
