import LOEIS.A350.A350685.Defs

set_option linter.unusedVariables false

/-!
# A350685

Maximum number of points on a hexagonal grid of side length n without arithmetic progression, i.e., no point is exactly at the center between two other points.

The 8 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A350685

/-- Known terms of `A350685`, starting at index `0`. -/
def data : List retType :=
  [0, 1, 6, 12, 18, 27, 33, 42]

/-- `A350685` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 8) : A350685 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 8) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 8) : fz n = data[n.toNat]! := sorry

end A350685
