import LOEIS.A225.A225828.Defs

set_option linter.unusedVariables false

/-!
# A225828

Number of binary pattern classes in the (4,n)-rectangular grid: two patterns are in the same class if one of them can be obtained by a reflection or 180-degree rotation of the other.

The 20 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A225828

/-- Known terms of `A225828`, starting at index `0`. -/
def data : List retType :=
  [1, 10, 76, 1120, 16576, 263680, 4197376, 67133440, 1073790976, 17180262400,
    274878693376, 4398052802560, 70368756760576, 1125900007505920, 18014398710808576, 288230377762324480, 4611686021648613376, 73786976320608010240, 1180591620768950910976, 18889465931890897715200]

/-- `A225828` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 20) : A225828 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 20) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 20) : fz n = data[n.toNat]! := sorry

end A225828
