import LOEIS.A029.A029524.Defs

set_option linter.unusedVariables false

/-!
# A029524

Numbers k such that k divides the (left) concatenation of all numbers <= k written in base 7 (most significant digit on right and removing all least significant zeros before concatenation).

The 16 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A029524

/-- Known terms of `A029524`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 9, 12, 36, 96, 128, 2267, 4031, 29416,
    551444, 2033727, 2056797, 2477144, 7974180, 9482385]

/-- `A029524` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A029524 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 17) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 17) : fz n = data[n.toNat - 1]! := sorry

end A029524
