import LOEIS.A202.A202603.Defs

set_option linter.unusedVariables false

/-!
# A202603

Triangle T(n,k), read by rows, given by (1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...) DELTA (1, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...) where DELTA is the operator defined in A084938.

The 66 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A202603

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 1, 0, 1, 1, -1, -1,
    1, 1, -2, -3, -1, 1, 1, -3, -5, -2,
    0, 1, 1, -4, -7, -2, 2, 1, 1, 1,
    -5, -9, -1, 7, 5, 1, 1, 1, -6, -11,
    1, 15, 12, 3, 0, 1, 1, -7, -13, 4,
    26, 21, 3, -3, -1, 1, 1, -8, -15, 8,
    40, 31, -3, -15, -7, -1]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 66) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 66) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 66) : flatFz n = flatData[n.toNat]! := sorry

end A202603
