import LOEIS.A016.A016719.Defs

set_option linter.unusedVariables false

/-!
# A016719

Decimal expansion of log(96).

The 99 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A016719

/-- Known terms of `A016719`, starting at index `1`. -/
def data : List retType :=
  [4, 5, 6, 4, 3, 4, 8, 1, 9, 1,
    4, 6, 7, 8, 3, 6, 2, 3, 8, 4,
    8, 1, 4, 0, 5, 8, 4, 4, 2, 1,
    3, 4, 0, 8, 5, 4, 5, 0, 2, 4,
    9, 9, 1, 2, 2, 9, 6, 2, 4, 0,
    2, 5, 7, 2, 2, 3, 3, 8, 0, 9,
    4, 3, 8, 1, 1, 0, 4, 4, 6, 2,
    4, 0, 3, 0, 6, 7, 0, 8, 2, 5,
    4, 4, 9, 0, 2, 9, 3, 2, 3, 8,
    9, 7, 9, 5, 8, 2, 5, 5, 2]

/-- `A016719` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 100) : A016719 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 100) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 100) : fz n = data[n.toNat - 1]! := sorry

end A016719
