import LOEIS.A221.A221655.Defs

set_option linter.unusedVariables false

/-!
# A221655

T(n,k)=Number of nXk arrays of occupancy after each element moves to some horizontal, diagonal or antidiagonal neighbor, without move-in move-out left turns.

The 45 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A221655

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [0, 1, 0, 2, 4, 0, 4, 24, 12, 0,
    8, 165, 230, 40, 0, 16, 1054, 5879, 2594, 136,
    0, 32, 6862, 128076, 233781, 28478, 460, 0, 64, 44576,
    2853634, 17254611, 9205038, 313721, 1556, 0, 128, 289789, 63318470, 1312503181,
    2299842566, 361920243, 3449644, 5264, 0]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 46) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 46) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 46) : flatFz n = flatData[n.toNat - 1]! := sorry

end A221655
