import LOEIS.A231.A231130.Defs

set_option linter.unusedVariables false

/-!
# A231130

Number of (n+1)X(7+1) white-square subarrays of 0..2 arrays with no element equal to a strict majority of its diagonal and antidiagonal neighbors, with values 0..2 introduced in row major order.

The 13 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A231130

/-- Known terms of `A231130`, starting at index `1`. -/
def data : List retType :=
  [328, 16368, 924900, 50257244, 2766762720, 151928497692, 8349491299560, 458819265958556, 25213940794848972, 1385606097689928700,
    76144709459504461524, 4184463747005748346676, 229953456825043397843448]

/-- `A231130` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 14) : A231130 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 14) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 14) : fz n = data[n.toNat - 1]! := sorry

end A231130
