import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A343981

a(n) is the least integer h such that there exists a Pythagorean triple whose hypotenuse is h and whose other legs z satisfy A176774(z) = n.

OEIS offset `3`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A343981

/-- Index type of `A343981` (OEIS offset `3`). -/
abbrev argType : Type := {n : Nat // 3 ≤ n}

/-- Value type of `A343981`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 3

end A343981

/-- a(n) is the least integer h such that there exists a Pythagorean triple whose hypotenuse is h and whose other legs z satisfy A176774(z) = n. -/
def A343981 : A343981.argType → A343981.retType := sorry

namespace A343981

/-- Relation that defines `A343981`. -/
def prop : argType → retType → Prop := sorry

/-- `A343981` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A343981` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A343981 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 3 ≤ n) : fn n = A343981 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 3 ≤ n) : fz n = A343981 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 3 ≤ n) : fn n = fz (n : Int) := sorry

end A343981
