import LOEIS.A067.A067008.Defs

set_option linter.unusedVariables false

/-!
# A067008

Numbers k such that Sum_{j=1..k} A008472(j) divides k!.

The 63 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A067008

/-- Known terms of `A067008`, starting at index `1`. -/
def data : List retType :=
  [2, 5, 7, 10, 13, 16, 19, 20, 31, 34,
    37, 40, 41, 44, 46, 48, 51, 53, 55, 56,
    62, 64, 65, 67, 68, 69, 73, 74, 76, 79,
    81, 82, 83, 84, 85, 86, 87, 89, 95, 96,
    97, 99, 100, 101, 106, 107, 108, 109, 111, 112,
    115, 119, 121, 122, 123, 124, 133, 134, 135, 136,
    137, 138, 143]

/-- `A067008` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 64) : A067008 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 64) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 64) : fz n = data[n.toNat - 1]! := sorry

end A067008
