import LOEIS.A136.A136217.Defs

set_option linter.unusedVariables false

/-!
# A136217

Square array, read by antidiagonals, where row n+1 is generated from row n by first removing terms in row n at positions {floor(m*(m+7)/6), m>=0} and then taking partial sums, starting with all 1's in row 0.

The 55 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A136217

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 3, 2, 1, 15, 8, 3, 1,
    108, 49, 15, 4, 1, 1036, 414, 108, 24, 5,
    1, 12569, 4529, 1036, 198, 34, 6, 1, 185704, 61369,
    12569, 2116, 306, 46, 7, 1, 3247546, 996815, 185704, 28052,
    3493, 453, 59, 8, 1, 65762269, 18931547, 3247546, 446560, 48800,
    5555, 622, 74, 9, 1]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 55) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 55) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 55) : flatFz n = flatData[n.toNat]! := sorry

end A136217
