import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A292353

Numbers n with a record number of Lucas-Carmichael numbers that can be generated from them using an adjusted version of Erdős's method.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A292353

/-- Index type of `A292353` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A292353`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A292353

/-- Numbers n with a record number of Lucas-Carmichael numbers that can be generated from them using an adjusted version of Erdős's method. -/
def A292353 : A292353.argType → A292353.retType := sorry

namespace A292353

/-- Relation that defines `A292353`. -/
def prop : argType → retType → Prop := sorry

/-- `A292353` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A292353` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A292353 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A292353 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A292353 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A292353
