import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A390679

a(n) is the permanent of the square matrix A(n) of order 2*n whose generic entry is A(i, j) = n*(2*i - (-1)^i - 3) + 2*j - (-1)^j/2 + (-1)^i - 3/2 with 1 <= i,j <= 2*n.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A390679

/-- Index type of `A390679` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A390679`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A390679

/-- a(n) is the permanent of the square matrix A(n) of order 2*n whose generic entry is A(i, j) = n*(2*i - (-1)^i - 3) + 2*j - (-1)^j/2 + (-1)^i - 3/2 with 1 <= i,j <= 2*n. -/
def A390679 : A390679.argType → A390679.retType := sorry

namespace A390679

/-- Relation that defines `A390679`. -/
def prop : argType → retType → Prop := sorry

/-- `A390679` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A390679` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A390679 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A390679 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A390679 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A390679
