import LOEIS.A376.A376121.Defs

set_option linter.unusedVariables false

/-!
# A376121

Continued fraction expansion of the real root of x^3 - 2*x^2 - 1.

The 93 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A376121

/-- Known terms of `A376121`, starting at index `0`. -/
def data : List retType :=
  [2, 4, 1, 6, 2, 1, 1, 1, 1, 1,
    1, 2, 2, 1, 2, 1, 2, 1, 27, 1654,
    1, 1, 6, 16, 7, 1, 1, 1, 1, 1,
    1, 1, 4, 1, 1, 1, 3, 5, 3, 3,
    1, 2, 3, 1, 2, 2, 197, 1, 8, 1,
    1, 4, 1, 1, 3, 1, 5, 79, 1, 2,
    1, 2, 15, 11, 2, 1, 3, 6, 4, 4,
    17, 1, 12, 1, 1, 1, 1, 1, 1, 1,
    3, 1, 7, 1, 1, 1, 1, 1, 7, 1,
    2, 1, 6]

/-- `A376121` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 93) : A376121 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 93) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 93) : fz n = data[n.toNat]! := sorry

end A376121
