import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A309357

a(0) = 10; for n>0, a(n) is determined by the rule that the concatenation of the leading terms of the difference triangle is the same as the concatenation of the digits of the sequence, with a one-digit delay between the two concatenations.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A309357

/-- Index type of `A309357` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A309357`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A309357

/-- a(0) = 10; for n>0, a(n) is determined by the rule that the concatenation of the leading terms of the difference triangle is the same as the concatenation of the digits of the sequence, with a one-digit delay between the two concatenations. -/
def A309357 : A309357.argType → A309357.retType := sorry

namespace A309357

/-- Relation that defines `A309357`. -/
def prop : argType → retType → Prop := sorry

/-- `A309357` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A309357` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A309357 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A309357 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A309357 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A309357
