import LOEIS.A310.A310232.Defs

set_option linter.unusedVariables false

/-!
# A310232

Coordination sequence Gal.4.11.1 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A310232

/-- Known terms of `A310232`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 7, 12, 15, 20, 22, 25, 30, 35,
    38, 43, 44, 47, 53, 58, 61, 66, 66, 69,
    76, 81, 84, 89, 88, 91, 99, 104, 107, 112,
    110, 113, 122, 127, 130, 135, 132, 135, 145, 150,
    153, 158, 154, 157, 168, 173, 176, 181, 176, 179]

/-- `A310232` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A310232 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A310232
