import LOEIS.A334.A334640.Defs

set_option linter.unusedVariables false

/-!
# A334640

a(n) is the total number of down steps between the 2nd and 3rd up steps in all 2-Dyck paths of length 3*n. A 2-Dyck path is a nonnegative lattice path with steps (1, 2), (1, -1) that starts and ends at y = 0.

The 25 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A334640

/-- Known terms of `A334640`, starting at index `0`. -/
def data : List retType :=
  [0, 0, 9, 19, 72, 324, 1595, 8307, 44982, 250648,
    1427679, 8274825, 48644310, 289334160, 1738043892, 10529070020, 64252519830, 394601627376, 2437058926871, 15126463230165,
    94306717535940, 590318477063700, 3708527622652755, 23374587898663155, 147770791807427880]

/-- `A334640` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 25) : A334640 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 25) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 25) : fz n = data[n.toNat]! := sorry

end A334640
