import LOEIS.A169.A169694.Defs

set_option linter.unusedVariables false

/-!
# A169694

Numbers of the form Fibonacci(i) + Fibonacci(j), where i and j have opposite parity and |i-j| > 1.

The 59 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A169694

/-- Known terms of `A169694`, starting at index `1`. -/
def data : List retType :=
  [2, 4, 5, 6, 9, 10, 13, 14, 16, 22,
    23, 26, 34, 35, 37, 42, 56, 57, 60, 68,
    89, 90, 92, 97, 110, 145, 146, 149, 157, 178,
    233, 234, 236, 241, 254, 288, 378, 379, 382, 390,
    411, 466, 610, 611, 613, 618, 631, 665, 754, 988,
    989, 992, 1000, 1021, 1076, 1220, 1597, 1598, 1600]

/-- `A169694` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 60) : A169694 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 60) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 60) : fz n = data[n.toNat - 1]! := sorry

end A169694
