import LOEIS.A304.A304147.Defs

set_option linter.unusedVariables false

/-!
# A304147

Number of nX6 0..1 arrays with every element unequal to 1, 2, 3 or 6 king-move adjacent elements, with upper left element zero.

The 23 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A304147

/-- Known terms of `A304147`, starting at index `1`. -/
def data : List retType :=
  [5, 157, 238, 117, 3484, 13152, 12582, 139840, 774023, 1302357,
    5969791, 40513904, 104507115, 310823229, 2014755745, 7056836043, 19236900969, 101258778882, 428958694755, 1270322334575,
    5406011650360, 24736396849595, 83207851721176]

/-- `A304147` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 24) : A304147 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 24) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 24) : fz n = data[n.toNat - 1]! := sorry

end A304147
