import LOEIS.A371.A371636.Defs

set_option linter.unusedVariables false

/-!
# A371636

For any number k >= 0, let T_k be the triangle with values in {-1, 0, +1} whose base corresponds to the balanced ternary expansion of k (without leading zeros) and other values, say t above u and v, satisfy t+u+v = 0 mod 3; this sequence lists the numbers k such that T_k has 3-fold rotational symmetry.

The 47 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A371636

/-- Known terms of `A371636`, starting at index `1`. -/
def data : List retType :=
  [0, 1, 4, 13, 19, 25, 40, 103, 112, 121,
    154, 214, 364, 442, 505, 595, 673, 763, 826, 913,
    1003, 1093, 1144, 1369, 1621, 1915, 2167, 2392, 2776, 3028,
    3280, 3628, 4420, 4996, 5668, 6244, 7036, 8203, 9022, 9841,
    10459, 10594, 11782, 12304, 13411, 13627, 14419]

/-- `A371636` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 48) : A371636 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 48) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 48) : fz n = data[n.toNat - 1]! := sorry

end A371636
