import LOEIS.A179.A179503.Defs

set_option linter.unusedVariables false

/-!
# A179503

a(n) = Sum_{k=0..n} C(n,k)*sigma(n,k)*sigma(n,n-k) for n>0 with a(0)=1.

The 16 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A179503

/-- Known terms of `A179503`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 38, 352, 8372, 115584, 4900168, 109607936, 5462020742, 210689453568,
    11579697409448, 585804318154752, 39828186864515408, 2482740302750253056, 188760627291893696552, 14430243196023615258624]

/-- `A179503` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 16) : A179503 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 16) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 16) : fz n = data[n.toNat]! := sorry

end A179503
