import LOEIS.A194.A194572.Defs

set_option linter.unusedVariables false

/-!
# A194572

Number of lower triangles of an n X n 0..4 array with new values introduced in row major order 0..4 and no element equal to more than two horizontal or vertical neighbors.

The 10 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A194572

/-- Known terms of `A194572`, starting at index `1`. -/
def data : List retType :=
  [1, 5, 193, 80780, 225623340, 3211386454648, 223665935176544829, 76009506543180381646618, 126023279808505699474721273930, 1019406708191445081689134021299430885]

/-- `A194572` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 11) : A194572 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 11) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 11) : fz n = data[n.toNat - 1]! := sorry

end A194572
