import LOEIS.A296.A296266.Defs

set_option linter.unusedVariables false

/-!
# A296266

Solution of the complementary equation a(n) = a(n-1) + a(n-2) + b(n-2)*b(n), where a(0) = 1, a(1) = 2, b(0) = 3, b(1) = 4, b(2) = 5, and (a(n)) and (b(n)) are increasing complementary sequences.

The 35 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A296266

/-- Known terms of `A296266`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 18, 44, 97, 189, 349, 618, 1066, 1804,
    3013, 4985, 8193, 13402, 21850, 35556, 57746, 93701, 151887, 246071,
    398486, 645132, 1044242, 1690049, 2735019, 4425851, 7161710, 11588460, 18751130, 30340613,
    49092831, 79434599, 128528654, 207964548, 336494570]

/-- `A296266` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 35) : A296266 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 35) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 35) : fz n = data[n.toNat]! := sorry

end A296266
