import LOEIS.A111.A111885.Defs

set_option linter.unusedVariables false

/-!
# A111885

Row sums of triangle A112492.

The 15 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A111885

/-- Known terms of `A111885`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 5, 20, 152, 2542, 100326, 10194844, 2809233510, 2212797607312,
    5359196565766782, 39928779843430949176, 1018129474625651322506886, 85890171235256453902613870992, 26477529277143069417959927152215342]

/-- `A111885` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 15) : A111885 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 15) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 15) : fz n = data[n.toNat]! := sorry

end A111885
