import LOEIS.A148.A148778.Defs

set_option linter.unusedVariables false

/-!
# A148778

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 1), (-1, 1, 0), (0, 1, -1), (1, 0, 1)}.

The 30 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A148778

/-- Known terms of `A148778`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 8, 23, 75, 242, 797, 2722, 9358,
    32361, 113558, 401386, 1423419, 5080996, 18236262, 65633113, 237023257, 859125261, 3121571670,
    11366570789, 41490482518, 151752532780, 555940056833, 2040133494268, 7498551097214, 27597459751318, 101697901462645, 375227305219404, 1385969645879384]

/-- `A148778` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 30) : A148778 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 30) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 30) : fz n = data[n.toNat]! := sorry

end A148778
