import LOEIS.A199.A199341.Defs

set_option linter.unusedVariables false

/-!
# A199341

Primes having only {1, 3, 4} as digits.

The 44 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A199341

/-- Known terms of `A199341`, starting at index `1`. -/
def data : List retType :=
  [3, 11, 13, 31, 41, 43, 113, 131, 311, 313,
    331, 431, 433, 443, 1433, 3313, 3331, 3343, 3413, 3433,
    4111, 4133, 4441, 11113, 11131, 11311, 11411, 11443, 13313, 13331,
    13411, 13441, 14143, 14341, 14411, 14431, 31333, 33113, 33311, 33331,
    33343, 33413, 34141, 34313]

/-- `A199341` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 45) : A199341 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 45) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 45) : fz n = data[n.toNat - 1]! := sorry

end A199341
