import LOEIS.A339.A339494.Defs

set_option linter.unusedVariables false

/-!
# A339494

T(n, k) is the number of domino towers of n bricks with height at most 3 and k bricks in the base floor. Triangle read by rows, T(n, k) for 1 <= k <= n.

The 66 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A339494

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 2, 1, 5, 3, 1, 5, 9, 4, 1,
    3, 14, 14, 5, 1, 1, 16, 29, 20, 6,
    1, 0, 12, 46, 51, 27, 7, 1, 0, 5,
    52, 101, 81, 35, 8, 1, 0, 1, 41, 150,
    190, 120, 44, 9, 1, 0, 0, 22, 169, 345,
    323, 169, 54, 10, 1, 0, 0, 7, 143, 495,
    687, 511, 229, 65, 11, 1]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 67) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 67) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 67) : flatFz n = flatData[n.toNat - 1]! := sorry

end A339494
