import LOEIS.A332.A332077.Defs

set_option linter.unusedVariables false

/-!
# A332077

Square array of sunflower numbers Sun(m,n) = minimal number of distinct sets of cardinality <= m such that there is a sunflower with at least n sets among them, read by falling antidiagonals; m, n >= 1.

The 17 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A332077

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 2, 1, 3, 2, 1, 4, 7, 2, 1,
    5, 11, 21, 2, 1, 6, 21]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 18) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 18) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 18) : flatFz n = flatData[n.toNat - 1]! := sorry

end A332077
