import LOEIS.A297.A297568.Defs

set_option linter.unusedVariables false

/-!
# A297568

Number of nonisomorphic proper colorings of partition star graph using four colors.

The 74 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A297568

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [4, 12, 24, 36, 40, 108, 108, 60, 216, 180,
    324, 324, 84, 360, 540, 648, 972, 972, 972, 112,
    540, 1080, 660, 1080, 2916, 1512, 1944, 2916, 2916, 2916,
    144, 756, 1800, 1980, 1620, 5832, 4860, 4536, 3240, 8748,
    8748, 5832, 8748, 8748, 8748, 180, 1008, 2700, 3960, 1980,
    2268, 9720, 14580, 9072, 13608, 4860, 17496, 14580, 26244, 13284,
    9720, 26244, 26244, 17496, 26244, 26244, 26244, 220, 1296, 3780,
    6600, 5940, 3024, 14580]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 74) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 74) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 74) : flatFz n = flatData[n.toNat]! := sorry

end A297568
