import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A299875

Number of nX4 0..1 arrays with every element equal to 0, 1, 2, 4, 5, 7 or 8 king-move adjacent elements, with upper left element zero.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A299875

/-- Index type of `A299875` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A299875`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A299875

/-- Number of nX4 0..1 arrays with every element equal to 0, 1, 2, 4, 5, 7 or 8 king-move adjacent elements, with upper left element zero. -/
def A299875 : A299875.argType → A299875.retType := sorry

namespace A299875

/-- Relation that defines `A299875`. -/
def prop : argType → retType → Prop := sorry

/-- `A299875` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A299875` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A299875 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A299875 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A299875 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A299875
