import LOEIS.A356.A356540.Defs

set_option linter.unusedVariables false

/-!
# A356540

Expansion of e.g.f. Product_{k>0} 1/(1 - (3 * x)^k)^(1/3^k).

The 19 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A356540

/-- Known terms of `A356540`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 6, 40, 496, 5400, 114400, 1760080, 47671680, 1090230400,
    34312096000, 916877068800, 39605683532800, 1211405062067200, 55580939301888000, 2260295506653184000, 115398744818925568000, 4928605977341190144000, 305987190350116667392000]

/-- `A356540` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 19) : A356540 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 19) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 19) : fz n = data[n.toNat]! := sorry

end A356540
