import LOEIS.A116.A116078.Defs

set_option linter.unusedVariables false

/-!
# A116078

Column 0 of triangle A116077.

The 23 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A116078

/-- Known terms of `A116078`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 7, 28, 117, 496, 2110, 8968, 38017, 160648,
    676626, 2840872, 11892562, 49650368, 206773372, 859186768, 3562780057, 14746127608, 60929182282, 251358948328,
    1035479267542, 4260071237728, 17505144024292]

/-- `A116078` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 23) : A116078 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 23) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 23) : fz n = data[n.toNat]! := sorry

end A116078
