import LOEIS.A340.A340383.Defs

set_option linter.unusedVariables false

/-!
# A340383

Lexicographically earliest infinite sequence such that a(i) = a(j) => f(i) = f(j), where f(n) = [A278222(A304759(n)), A278222(A291759(n))], for all i, j >= 1.

The 90 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A340383

/-- Known terms of `A340383`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 1, 3, 4, 5, 2, 6, 7, 3,
    3, 8, 1, 9, 2, 10, 11, 6, 4, 12,
    11, 13, 3, 14, 9, 15, 3, 16, 12, 17,
    3, 18, 3, 3, 7, 19, 3, 9, 19, 19,
    6, 3, 5, 8, 12, 20, 1, 21, 8, 22,
    12, 23, 11, 24, 12, 25, 6, 8, 26, 27,
    12, 13, 12, 28, 13, 29, 4, 12, 9, 20,
    26, 30, 31, 22, 10, 16, 5, 14, 6, 32,
    33, 8, 3, 12, 10, 23, 15, 14, 19, 8]

/-- `A340383` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 91) : A340383 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 91) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 91) : fz n = data[n.toNat - 1]! := sorry

end A340383
