import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A358675

Numbers k such that for all nontrivial factorizations of k as x*y, the sum (x * y') + (x' * y) will generate at least one carry when the addition is done in the primorial base. Here n' stands for A003415(n), the arithmetic derivative of n.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A358675

/-- Index type of `A358675` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A358675`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A358675

/-- Numbers k such that for all nontrivial factorizations of k as x*y, the sum (x * y') + (x' * y) will generate at least one carry when the addition is done in the primorial base. Here n' stands for A003415(n), the arithmetic derivative of n. -/
def A358675 : A358675.argType → A358675.retType := sorry

namespace A358675

/-- Relation that defines `A358675`. -/
def prop : argType → retType → Prop := sorry

/-- `A358675` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A358675` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A358675 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A358675 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A358675 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A358675
