import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A385396

Numbers k such that 8 does not divide binomial(k, j) for any j in 0..k.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A385396

/-- Index type of `A385396` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A385396`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A385396

/-- Numbers k such that 8 does not divide binomial(k, j) for any j in 0..k. -/
def A385396 : A385396.argType → A385396.retType := sorry

namespace A385396

/-- Relation that defines `A385396`. -/
def prop : argType → retType → Prop := sorry

/-- `A385396` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A385396` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A385396 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A385396 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A385396 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A385396
