import LOEIS.A105.A105069.Defs

set_option linter.unusedVariables false

/-!
# A105069

Number of distinct prime divisors of 100^n - 3.

The 111 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A105069

/-- Known terms of `A105069`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 2, 2, 2, 2, 2, 4, 4, 4,
    2, 2, 3, 3, 3, 4, 2, 4, 3, 5,
    5, 4, 4, 5, 4, 4, 2, 4, 5, 4,
    3, 4, 3, 5, 5, 3, 5, 5, 4, 4,
    5, 5, 2, 3, 6, 4, 4, 8, 4, 4,
    6, 3, 4, 6, 6, 5, 6, 5, 5, 3,
    3, 7, 8, 5, 5, 3, 3, 5, 4, 1,
    6, 4, 5, 6, 3, 5, 6, 6, 4, 5,
    7, 3, 3, 7, 3, 6, 4, 5, 6, 8,
    2, 7, 3, 4, 8, 6, 6, 7, 5, 4,
    8, 6, 6, 5, 4, 4, 6, 4, 3, 5,
    7]

/-- `A105069` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 112) : A105069 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 112) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 112) : fz n = data[n.toNat - 1]! := sorry

end A105069
