import LOEIS.A143.A143306.Defs

set_option linter.unusedVariables false

/-!
# A143306

Decimal expansion of the transcendental constant in the definition of van der Corput's constant (negated).

The 105 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A143306

/-- Known terms of `A143306`, starting at index `0`. -/
def data : List retType :=
  [7, 2, 6, 6, 4, 3, 2, 4, 6, 8,
    1, 3, 2, 4, 2, 5, 0, 9, 5, 9,
    0, 2, 1, 9, 5, 5, 5, 9, 4, 1,
    9, 8, 5, 5, 6, 3, 2, 5, 7, 2,
    7, 8, 9, 3, 3, 4, 6, 9, 9, 9,
    4, 0, 0, 8, 6, 8, 7, 9, 7, 5,
    9, 0, 8, 3, 5, 7, 0, 9, 0, 2,
    6, 6, 9, 3, 7, 0, 9, 4, 5, 6,
    3, 3, 7, 3, 1, 3, 2, 1, 9, 9,
    5, 4, 5, 0, 3, 0, 7, 6, 9, 5,
    1, 2, 8, 5, 2]

/-- `A143306` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 105) : A143306 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 105) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 105) : fz n = data[n.toNat]! := sorry

end A143306
