import LOEIS.A000.A000484.Defs

set_option linter.unusedVariables false

/-!
# A000484

a(n) = round(cos(n)).

The 84 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A000484

/-- Known terms of `A000484`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 0, -1, -1, 0, 1, 1, 0, -1,
    -1, 0, 1, 1, 0, -1, -1, 0, 1, 1,
    0, -1, -1, -1, 0, 1, 1, 0, -1, -1,
    0, 1, 1, 0, -1, -1, 0, 1, 1, 0,
    -1, -1, 0, 1, 1, 1, 0, -1, -1, 0,
    1, 1, 0, -1, -1, 0, 1, 1, 0, -1,
    -1, 0, 1, 1, 0, -1, -1, -1, 0, 1,
    1, 0, -1, -1, 0, 1, 1, 0, -1, -1,
    0, 1, 1, 0]

/-- `A000484` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 84) : A000484 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 84) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 84) : fz n = data[n.toNat]! := sorry

end A000484
