import LOEIS.A159.A159474.Defs

set_option linter.unusedVariables false

/-!
# A159474

Pandigital primes with least digit sum (46) starting with the largest and listed in descending order.

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A159474

/-- Known terms of `A159474`, starting at index `1`. -/
def data : List retType :=
  [98765421103, 98765410231, 98765401321, 98765321401, 98765320411, 98765301241, 98765241103, 98765240131, 98765240113, 98765234011,
    98765204311, 98765201341, 98765140231, 98765134021, 98765124103, 98765124013, 98765121043, 98765120431, 98765120413, 98765120143]

/-- `A159474` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 21) : A159474 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : fz n = data[n.toNat - 1]! := sorry

end A159474
