import LOEIS.A205.A205940.Defs

set_option linter.unusedVariables false

/-!
# A205940

Number of (n+1) X 5 0..3 arrays with no 2 X 2 subblock having the number of clockwise edge increases equal to the number of counterclockwise edge increases in its adjacent leftward or upward neighbors.

The 14 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A205940

/-- Known terms of `A205940`, starting at index `1`. -/
def data : List retType :=
  [91440, 620988, 6705048, 70027468, 692354440, 6909160028, 72541287824, 778680028616, 7889326861776, 81346754344248,
    853506521827200, 9001326523610412, 92292464888517816, 960070329464841064]

/-- `A205940` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 15) : A205940 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 15) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 15) : fz n = data[n.toNat - 1]! := sorry

end A205940
