import LOEIS.A142.A142105.Defs

set_option linter.unusedVariables false

/-!
# A142105

Primes congruent to 17 mod 36.

The 46 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A142105

/-- Known terms of `A142105`, starting at index `1`. -/
def data : List retType :=
  [17, 53, 89, 197, 233, 269, 449, 521, 557, 593,
    701, 773, 809, 881, 953, 1061, 1097, 1277, 1493, 1601,
    1637, 1709, 1889, 1997, 2069, 2141, 2213, 2357, 2393, 2609,
    2753, 2789, 2861, 2897, 2969, 3041, 3221, 3257, 3329, 3581,
    3617, 3761, 3797, 3833, 4013, 4049]

/-- `A142105` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 47) : A142105 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 47) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 47) : fz n = data[n.toNat - 1]! := sorry

end A142105
