import LOEIS.A242.A242771.Defs

set_option linter.unusedVariables false

/-!
# A242771

Number of integer points in a certain quadrilateral scaled by a factor of n (another version).

The 55 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A242771

/-- Known terms of `A242771`, starting at index `1`. -/
def data : List retType :=
  [0, 0, 1, 3, 6, 9, 14, 19, 25, 32,
    40, 48, 58, 68, 79, 91, 104, 117, 132, 147,
    163, 180, 198, 216, 236, 256, 277, 299, 322, 345,
    370, 395, 421, 448, 476, 504, 534, 564, 595, 627,
    660, 693, 728, 763, 799, 836, 874, 912, 952, 992,
    1033, 1075, 1118, 1161, 1206]

/-- `A242771` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 56) : A242771 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 56) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 56) : fz n = data[n.toNat - 1]! := sorry

end A242771
