import LOEIS.A129.A129713.Defs

set_option linter.unusedVariables false

/-!
# A129713

Triangle read by rows: T(n,k) is the number of Fibonacci binary words of length n and starting with exactly k 1's (0<=k<=n). A Fibonacci binary word is a binary word having no 00 subword.

The 93 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A129713

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
    3, 2, 1, 1, 1, 5, 3, 2, 1, 1,
    1, 8, 5, 3, 2, 1, 1, 1, 13, 8,
    5, 3, 2, 1, 1, 1, 21, 13, 8, 5,
    3, 2, 1, 1, 1, 34, 21, 13, 8, 5,
    3, 2, 1, 1, 1, 55, 34, 21, 13, 8,
    5, 3, 2, 1, 1, 1, 89, 55, 34, 21,
    13, 8, 5, 3, 2, 1, 1, 1, 144, 89,
    55, 34, 21, 13, 8, 5, 3, 2, 1, 1,
    1, 233, 144]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 93) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 93) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 93) : flatFz n = flatData[n.toNat]! := sorry

end A129713
