import LOEIS.A315.A315631.Defs

set_option linter.unusedVariables false

/-!
# A315631

Coordination sequence Gal.5.68.5 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A315631

/-- Known terms of `A315631`, starting at index `0`. -/
def data : List retType :=
  [1, 6, 12, 16, 20, 24, 28, 32, 38, 44,
    50, 56, 60, 64, 68, 72, 76, 82, 88, 94,
    100, 104, 108, 112, 116, 120, 126, 132, 138, 144,
    148, 152, 156, 160, 164, 170, 176, 182, 188, 192,
    196, 200, 204, 208, 214, 220, 226, 232, 236, 240]

/-- `A315631` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A315631 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A315631
