import LOEIS.A266.A266929.Defs

set_option linter.unusedVariables false

/-!
# A266929

Number of n X n binary arrays with rows lexicographically nondecreasing and columns lexicographically nondecreasing and row sums nondecreasing and column sums nonincreasing.

The 9 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A266929

/-- Known terms of `A266929`, starting at index `1`. -/
def data : List retType :=
  [2, 4, 9, 35, 210, 2577, 68890, 4605960, 821453747]

/-- `A266929` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 10) : A266929 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 10) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 10) : fz n = data[n.toNat - 1]! := sorry

end A266929
