import LOEIS.A060.A060221.Defs

set_option linter.unusedVariables false

/-!
# A060221

Number of orbits of length n under the full 18-shift (whose periodic points are counted by A001027).

The 19 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A060221

/-- Known terms of `A060221`, starting at index `1`. -/
def data : List retType :=
  [18, 153, 1938, 26163, 377910, 5667681, 87460002, 1377481950, 22039920504, 357046533675,
    5842582734474, 96402612275775, 1601766528128550, 26772383354990049, 449776041098370870, 7589970692848393200, 128583032925805678350, 2185911559727674682148, 37275544492386193492506]

/-- `A060221` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 20) : A060221 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 20) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 20) : fz n = data[n.toNat - 1]! := sorry

end A060221
