import LOEIS.A032.A032930.Defs

set_option linter.unusedVariables false

/-!
# A032930

Numbers whose set of base-9 digits is {1,2}.

The 43 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A032930

/-- Known terms of `A032930`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 10, 11, 19, 20, 91, 92, 100, 101,
    172, 173, 181, 182, 820, 821, 829, 830, 901, 902,
    910, 911, 1549, 1550, 1558, 1559, 1630, 1631, 1639, 1640,
    7381, 7382, 7390, 7391, 7462, 7463, 7471, 7472, 8110, 8111,
    8119, 8120, 8191]

/-- `A032930` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 44) : A032930 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 44) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 44) : fz n = data[n.toNat - 1]! := sorry

end A032930
