import LOEIS.A147.A147458.Defs

set_option linter.unusedVariables false

/-!
# A147458

Number of n X n binary arrays symmetric under 90 degree rotation with all ones connected only in a 11000-01111-11000 pattern in any orientation.

The 24 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A147458

/-- Known terms of `A147458`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 1, 1, 1, 1, 1, 3, 9, 21,
    34, 61, 142, 363, 998, 3151, 10096, 34473, 121095, 493961,
    2091176, 9966879, 48888970, 265507652]

/-- `A147458` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 25) : A147458 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 25) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 25) : fz n = data[n.toNat - 1]! := sorry

end A147458
