import LOEIS.A072.A072985.Defs

set_option linter.unusedVariables false

/-!
# A072985

Coefficient of the highest power of q in the expansion of nu(0)=1, nu(1)=b and for n >= 2, nu(n) = b*nu(n-1) + lambda*(n-1)_q*nu(n-2) with (b,lambda)=(2,3), where (n)_q = (1+q+...+q^(n-1)) and q is a root of unity.

The 34 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A072985

/-- Known terms of `A072985`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 7, 6, 21, 18, 63, 54, 189, 162,
    567, 486, 1701, 1458, 5103, 4374, 15309, 13122, 45927, 39366,
    137781, 118098, 413343, 354294, 1240029, 1062882, 3720087, 3188646, 11160261, 9565938,
    33480783, 28697814, 100442349, 86093442]

/-- `A072985` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 34) : A072985 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 34) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 34) : fz n = data[n.toNat]! := sorry

end A072985
