import LOEIS.A229.A229534.Defs

set_option linter.unusedVariables false

/-!
# A229534

T(n,k) = number of defective 3-colorings of an n X k 0..2 array connected horizontally, diagonally and antidiagonally with exactly one mistake, and colors introduced in row-major 0..2 order.

The 50 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A229534

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [0, 1, 0, 2, 4, 0, 6, 8, 20, 0,
    16, 36, 58, 84, 0, 40, 112, 361, 356, 324,
    0, 96, 368, 1588, 3064, 2038, 1188, 0, 224, 1152,
    7460, 19276, 24344, 11184, 4212, 0, 512, 3568, 33136, 130854,
    221096, 185808, 59626, 14580, 0, 1152, 10880, 146300, 833108, 2171944]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 51) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 51) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 51) : flatFz n = flatData[n.toNat - 1]! := sorry

end A229534
