import LOEIS.A048.A048277.Defs

set_option linter.unusedVariables false

/-!
# A048277

Number of (not necessarily distinct) nonsquarefree numbers among C(n,k), k=0..n.

The 75 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A048277

/-- Known terms of `A048277`, starting at index `0`. -/
def data : List retType :=
  [0, 0, 0, 0, 2, 0, 1, 0, 6, 8,
    5, 0, 9, 4, 3, 2, 15, 12, 17, 12,
    13, 12, 11, 0, 21, 22, 19, 26, 25, 18,
    25, 20, 31, 30, 27, 28, 35, 30, 25, 28,
    37, 30, 29, 18, 29, 38, 27, 6, 47, 48,
    49, 48, 47, 36, 51, 50, 55, 52, 49, 38,
    53, 36, 23, 56, 63, 62, 61, 60, 61, 54,
    59, 54, 71, 66, 57]

/-- `A048277` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 75) : A048277 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 75) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 75) : fz n = data[n.toNat]! := sorry

end A048277
