import LOEIS.A048.A048802.Defs

set_option linter.unusedVariables false

/-!
# A048802

Number of labeled rooted trees of nonempty sets with n points. (Each node is a set of 1 or more points.)

The 19 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A048802

/-- Known terms of `A048802`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 16, 133, 1521, 22184, 393681, 8233803, 198342718, 5408091155,
    164658043397, 5537255169582, 203840528337291, 8153112960102283, 352079321494938344, 16325961781591781401, 809073412162081974237, 42674870241038732398720, 2386963662244981472850709]

/-- `A048802` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 20) : A048802 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 20) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 20) : fz n = data[n.toNat - 1]! := sorry

end A048802
