import LOEIS.A269.A269934.Defs

set_option linter.unusedVariables false

/-!
# A269934

Number of nX4 0..6 arrays with some element plus some horizontally, diagonally, antidiagonally or vertically adjacent neighbor totalling six exactly once.

The 11 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A269934

/-- Known terms of `A269934`, starting at index `1`. -/
def data : List retType :=
  [756, 1213836, 755009274, 399002850360, 193171242190020, 88942337408262936, 39591200828582988102, 17206536333078160595304, 7344924168583134203517654, 3091899703680951440763165408,
    1287126422247369227744582964456]

/-- `A269934` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 12) : A269934 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 12) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 12) : fz n = data[n.toNat - 1]! := sorry

end A269934
