import LOEIS.A260.A260268.Defs

set_option linter.unusedVariables false

/-!
# A260268

Primes having only {1, 4, 5} as digits.

The 39 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A260268

/-- Known terms of `A260268`, starting at index `1`. -/
def data : List retType :=
  [5, 11, 41, 151, 541, 1151, 1451, 1511, 4111, 4441,
    4451, 5441, 11411, 11551, 14411, 14551, 15451, 15511, 15541, 15551,
    41141, 41411, 44111, 45541, 51151, 51511, 51551, 54151, 54541, 55411,
    55441, 55511, 55541, 114451, 115151, 141511, 141551, 144451, 144511]

/-- `A260268` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 40) : A260268 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 40) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 40) : fz n = data[n.toNat - 1]! := sorry

end A260268
