import LOEIS.A263.A263756.Defs

set_option linter.unusedVariables false

/-!
# A263756

Triangle read by rows: T(n,k) (n>=0, k>=0) is the number of permutations of n with sum of descent bottoms equal to k.

The 69 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A263756

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 1, 3, 1, 1, 1, 7,
    3, 8, 3, 1, 1, 1, 15, 7, 34, 18,
    14, 18, 8, 3, 1, 1, 1, 31, 15, 122,
    72, 69, 147, 83, 71, 33, 45, 18, 8, 3,
    1, 1, 1, 63, 31, 406, 252, 263, 822, 544,
    554, 399, 613, 351, 307, 160, 102, 96, 45, 18,
    8, 3, 1, 1, 1, 127, 63, 1298, 828]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 69) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 69) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 69) : flatFz n = flatData[n.toNat]! := sorry

end A263756
