import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A394389

The number of squares visited by a (1,2)-darter moving on a square-spiral numbered board, starting from square n, and always moving to the lowest available unvisited square that can be reached without crossing a square that has been previously visited  (Cf. A394387).

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A394389

/-- Index type of `A394389` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A394389`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A394389

/-- The number of squares visited by a (1,2)-darter moving on a square-spiral numbered board, starting from square n, and always moving to the lowest available unvisited square that can be reached without crossing a square that has been previously visited  (Cf. A394387). -/
def A394389 : A394389.argType → A394389.retType := sorry

namespace A394389

/-- Relation that defines `A394389`. -/
def prop : argType → retType → Prop := sorry

/-- `A394389` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A394389` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A394389 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A394389 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A394389 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A394389
