import LOEIS.A013.A013869.Defs

set_option linter.unusedVariables false

/-!
# A013869

a(n) = 13^(5*n + 4).

The 8 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A013869

/-- Known terms of `A013869`, starting at index `0`. -/
def data : List retType :=
  [28561, 10604499373, 3937376385699289, 1461920290375446110677, 542800770374370512771595361, 201538126434611150798503956371773, 74829695578286078013428929473144712489, 27783742160348572763840067510872319734178277]

/-- `A013869` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 8) : A013869 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 8) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 8) : fz n = data[n.toNat]! := sorry

end A013869
