import LOEIS.A267.A267626.Defs

set_option linter.unusedVariables false

/-!
# A267626

Number of nX3 arrays containing 3 copies of 0..n-1 with every element equal to or 1 greater than any west neighbor modulo n and the upper left element equal to 0.

The 12 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A267626

/-- Known terms of `A267626`, starting at index `1`. -/
def data : List retType :=
  [1, 10, 39, 208, 1576, 14830, 168500, 2247280, 34423760, 596248800,
    11529957600, 246360114000]

/-- `A267626` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 13) : A267626 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 13) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 13) : fz n = data[n.toNat - 1]! := sorry

end A267626
