import LOEIS.A110.A110122.Defs

set_option linter.unusedVariables false

/-!
# A110122

Number of Delannoy paths of length n with no EE's crossing the line y = x (i.e., no two consecutive E steps from the line y = x+1 to the line y = x-1).

The 24 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A110122

/-- Known terms of `A110122`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 12, 53, 247, 1192, 5897, 29723, 152020, 786733,
    4111295, 21661168, 114925697, 613442227, 3291704108, 17745496453, 96062011319, 521943400056, 2845404909129, 15558847792747,
    85311186002036, 468951179698653, 2583765541267647, 14266052382826208]

/-- `A110122` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 24) : A110122 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 24) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 24) : fz n = data[n.toNat]! := sorry

end A110122
