import LOEIS.A153.A153904.Defs

set_option linter.unusedVariables false

/-!
# A153904

Number of planar n X n X n binary triangular grids symmetric both under 120-degree rotation and reflection with no more than 1 one in any 4 X 4 X 4 subtriangle.

The 31 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A153904

/-- Known terms of `A153904`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 1, 1, 2, 2, 2, 4, 3, 5,
    6, 8, 8, 24, 15, 28, 52, 66, 85, 246,
    226, 453, 898, 1300, 1806, 6204, 5820, 13820, 31156, 51179,
    81402]

/-- `A153904` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 31) : A153904 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 31) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 31) : fz n = data[n.toNat]! := sorry

end A153904
