import LOEIS.A313.A313037.Defs

set_option linter.unusedVariables false

/-!
# A313037

Coordination sequence Gal.6.446.1 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A313037

/-- Known terms of `A313037`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 9, 14, 18, 22, 29, 33, 38, 42,
    49, 51, 57, 60, 68, 70, 77, 79, 88, 89,
    96, 97, 107, 107, 116, 116, 127, 126, 136, 134,
    146, 144, 155, 153, 166, 163, 175, 172, 185, 181,
    194, 190, 205, 200, 214, 209, 225, 218, 233, 227]

/-- `A313037` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A313037 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A313037
