import LOEIS.A155.A155281.Defs

set_option linter.unusedVariables false

/-!
# A155281

Number of ways to place zero or more nonadjacent 0,0 1,0 2,0 3,0 4,1 4,2 polyhexes in any orientation on a planar nXnXn triangular grid.

The 13 terms known to OEIS, indexed from `4`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A155281

/-- Known terms of `A155281`, starting at index `4`. -/
def data : List retType :=
  [1, 7, 25, 76, 289, 1579, 11207, 100558, 1021474, 12631241,
    194406300, 3780423351, 90519767008]

/-- `A155281` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A155281 n = data[n.val - 4]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 4 ≤ n) (h : n < 17) : fn n = data[n - 4]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 4 ≤ n) (h : n < 17) : fz n = data[n.toNat - 4]! := sorry

end A155281
