import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A090535

Least n-digit prime using digit 7 once and rest all 1, or 0 if no such prime exists.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A090535

/-- Index type of `A090535` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A090535`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A090535

/-- Least n-digit prime using digit 7 once and rest all 1, or 0 if no such prime exists. -/
def A090535 : A090535.argType → A090535.retType := sorry

namespace A090535

/-- Relation that defines `A090535`. -/
def prop : argType → retType → Prop := sorry

/-- `A090535` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A090535` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A090535 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A090535 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A090535 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A090535
