import LOEIS.A026.A026086.Defs

set_option linter.unusedVariables false

/-!
# A026086

Number of (s(0), s(1), ..., s(n)) such that s(0) = 0, |s(i) - s(i-1)| = 1 for i = 1,2,3; |s(i) - s(i-1)| <= 1 for i >= 4, s(n) = 3; also a(n) = T(n,n-3), where T is the array defined in A026082.

The 26 terms known to OEIS, indexed from `4`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A026086

/-- Known terms of `A026086`, starting at index `4`. -/
def data : List retType :=
  [1, 6, 16, 52, 156, 475, 1429, 4293, 12853, 38413,
    114621, 341639, 1017407, 3027909, 9007017, 26783331, 79622595, 236662764, 703350798, 2090179494,
    6211285598, 18457764317, 54851312871, 163009822939, 484469104651, 1439956255806]

/-- `A026086` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 30) : A026086 n = data[n.val - 4]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 4 ≤ n) (h : n < 30) : fn n = data[n - 4]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 4 ≤ n) (h : n < 30) : fz n = data[n.toNat - 4]! := sorry

end A026086
