import LOEIS.A213.A213259.Defs

set_option linter.unusedVariables false

/-!
# A213259

The number of primorials that neither exceed nor divide the n-th colossally abundant number.

The 75 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A213259

/-- Known terms of `A213259`, starting at index `1`. -/
def data : List retType :=
  [0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
    1, 1, 2, 2, 2, 1, 2, 2, 1, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
    2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
    4, 4, 4, 4, 4, 3, 3, 3, 3, 3,
    3, 3, 3, 4, 4, 4, 4, 4, 4, 4,
    4, 4, 4, 4, 4, 5, 5, 5, 5, 5,
    5, 5, 5, 5, 5]

/-- `A213259` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 76) : A213259 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 76) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 76) : fz n = data[n.toNat - 1]! := sorry

end A213259
