import LOEIS.A059.A059093.Defs

set_option linter.unusedVariables false

/-!
# A059093

Numbers ending with the letter "e" (in English).

The 61 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A059093

/-- Known terms of `A059093`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 5, 9, 12, 21, 23, 25, 29, 31,
    33, 35, 39, 41, 43, 45, 49, 51, 53, 55,
    59, 61, 63, 65, 69, 71, 73, 75, 79, 81,
    83, 85, 89, 91, 93, 95, 99, 101, 103, 105,
    109, 112, 121, 123, 125, 129, 131, 133, 135, 139,
    141, 143, 145, 149, 151, 153, 155, 159, 161, 163,
    165]

/-- `A059093` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 62) : A059093 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 62) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 62) : fz n = data[n.toNat - 1]! := sorry

end A059093
