import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A217352

Numbers k such that 6^k - 7 is prime.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A217352

/-- Index type of `A217352` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A217352`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A217352

/-- Numbers k such that 6^k - 7 is prime. -/
def A217352 : A217352.argType → A217352.retType := sorry

namespace A217352

/-- Relation that defines `A217352`. -/
def prop : argType → retType → Prop := sorry

/-- `A217352` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A217352` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A217352 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A217352 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A217352 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A217352
