import LOEIS.A352.A352442.Defs

set_option linter.unusedVariables false

/-!
# A352442

Largest prime "r" among all pairs of Goldbach partitions of A352240(n), (p,q) and (r,s) with p,q,r,s prime and p < r <= s < q, such that all integers in the open intervals (p,r) and (s,q) are composite.

The 70 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A352442

/-- Known terms of `A352442`, starting at index `1`. -/
def data : List retType :=
  [5, 5, 7, 5, 11, 13, 5, 17, 13, 5,
    19, 17, 29, 5, 23, 31, 29, 19, 29, 41,
    37, 17, 37, 43, 53, 41, 37, 29, 53, 59,
    53, 61, 53, 41, 67, 59, 47, 71, 5, 47,
    29, 79, 71, 73, 83, 53, 83, 37, 59, 83,
    37, 29, 71, 29, 101, 103, 107, 67, 89, 73,
    67, 59, 101, 79, 59, 107, 79, 113, 5, 109]

/-- `A352442` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 71) : A352442 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 71) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 71) : fz n = data[n.toNat - 1]! := sorry

end A352442
