import LOEIS.A204.A204616.Defs

set_option linter.unusedVariables false

/-!
# A204616

T(n,k) = Number of (n+1) X (k+1) 0..1 arrays with the determinants of 2 X 2 subblocks nondecreasing rightwards and downwards.

The 38 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A204616

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [16, 47, 47, 125, 181, 125, 335, 749, 749, 335,
    907, 3254, 4901, 3254, 907, 2470, 14199, 31805, 31805, 14199,
    2470, 6740, 62031, 205117, 313597, 205117, 62031, 6740, 18406, 271125,
    1322417, 3084029, 3084029, 1322417, 271125, 18406, 50278, 1185255]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 39) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 39) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 39) : flatFz n = flatData[n.toNat - 1]! := sorry

end A204616
