import LOEIS.A261.A261374.Defs

set_option linter.unusedVariables false

/-!
# A261374

Number of (n+2) X (2+2) 0..1 arrays with each 3 X 3 subblock having clockwise perimeter pattern 00001011 00010101 or 01010101.

The 31 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A261374

/-- Known terms of `A261374`, starting at index `1`. -/
def data : List retType :=
  [39, 41, 82, 157, 266, 470, 864, 1553, 2758, 4960,
    8924, 16001, 28662, 51503, 92374, 165796, 297284, 533858, 957252, 1718645,
    3081790, 5533474, 9922064, 17814980, 31944528, 57356546, 102846820, 184661677, 331120454, 594527399,
    1066057422]

/-- `A261374` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 32) : A261374 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 32) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 32) : fz n = data[n.toNat - 1]! := sorry

end A261374
