import LOEIS.A158.A158010.Defs

set_option linter.unusedVariables false

/-!
# A158010

a(n) = 256*n^2 - n.

The 34 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A158010

/-- Known terms of `A158010`, starting at index `1`. -/
def data : List retType :=
  [255, 1022, 2301, 4092, 6395, 9210, 12537, 16376, 20727, 25590,
    30965, 36852, 43251, 50162, 57585, 65520, 73967, 82926, 92397, 102380,
    112875, 123882, 135401, 147432, 159975, 173030, 186597, 200676, 215267, 230370,
    245985, 262112, 278751, 295902]

/-- `A158010` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 35) : A158010 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 35) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 35) : fz n = data[n.toNat - 1]! := sorry

end A158010
