import LOEIS.A143.A143752.Defs

set_option linter.unusedVariables false

/-!
# A143752

Expansion of eta(q^3) * eta(q^4) * eta(q^5) * eta(q^60) / (eta(q) * eta(q^12) * eta(q^15) * eta(q^20)) in powers of q.

The 58 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A143752

/-- Known terms of `A143752`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 2, 2, 3, 3, 4, 5, 6, 7,
    8, 10, 11, 14, 17, 20, 23, 27, 31, 36,
    41, 48, 55, 63, 72, 82, 94, 106, 122, 137,
    156, 175, 197, 222, 249, 280, 314, 352, 393, 439,
    490, 546, 608, 676, 751, 834, 923, 1024, 1133, 1253,
    1384, 1528, 1686, 1857, 2045, 2250, 2474, 2718]

/-- `A143752` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 59) : A143752 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 59) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 59) : fz n = data[n.toNat - 1]! := sorry

end A143752
