import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A191198

Integers in (-1+A191137)/3; contains A191137 as a proper subsequence.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A191198

/-- Index type of `A191198` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A191198`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A191198

/-- Integers in (-1+A191137)/3; contains A191137 as a proper subsequence. -/
def A191198 : A191198.argType → A191198.retType := sorry

namespace A191198

/-- Relation that defines `A191198`. -/
def prop : argType → retType → Prop := sorry

/-- `A191198` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A191198` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A191198 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A191198 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A191198 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A191198
