import LOEIS.A205.A205760.Defs

set_option linter.unusedVariables false

/-!
# A205760

Number of (n+1)X(n+1) 0..3 arrays with every 2X2 subblock having nonzero determinant and having the same number of clockwise edge increases as its horizontal and vertical neighbors.

The 8 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A205760

/-- Known terms of `A205760`, starting at index `1`. -/
def data : List retType :=
  [192, 17674, 9909258, 31592825608, 492612437238998, 37329289868928312037, 13716254602126712440880420, 24435414110066470652645658456176]

/-- `A205760` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 9) : A205760 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 9) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 9) : fz n = data[n.toNat - 1]! := sorry

end A205760
