import LOEIS.A323.A323419.Defs

set_option linter.unusedVariables false

/-!
# A323419

The fourth greedy 3-free sequence on nonnegative integers.

The 67 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A323419

/-- Known terms of `A323419`, starting at index `1`. -/
def data : List retType :=
  [21, 22, 24, 25, 48, 49, 51, 52, 57, 58,
    60, 61, 102, 103, 105, 106, 129, 130, 132, 133,
    138, 139, 141, 142, 165, 166, 168, 169, 264, 265,
    267, 268, 291, 292, 294, 295, 300, 301, 303, 304,
    345, 346, 348, 349, 372, 373, 375, 376, 381, 382,
    384, 385, 408, 409, 411, 412, 489, 490, 492, 493,
    750, 751, 753, 754, 777, 778, 780]

/-- `A323419` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 68) : A323419 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 68) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 68) : fz n = data[n.toNat - 1]! := sorry

end A323419
