import LOEIS.A385.A385883.Defs

set_option linter.unusedVariables false

/-!
# A385883

Values of v in the quartets (1, u, v, w) of type 2; i.e., values of v for solutions to (1 + u) =  v(v - w), in positive integers, with v > 1, sorted by  nondecreasing values of u; see A386218.

The 70 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A385883

/-- Known terms of `A385883`, starting at index `1`. -/
def data : List retType :=
  [4, 5, 6, 7, 5, 8, 6, 9, 10, 7,
    11, 6, 8, 12, 13, 9, 7, 14, 10, 15,
    8, 16, 11, 17, 7, 9, 12, 18, 19, 13,
    8, 10, 20, 14, 21, 11, 22, 9, 15, 23,
    8, 12, 16, 24, 10, 25, 17, 13, 26, 9,
    18, 27, 11, 14, 28, 19, 29, 10, 12, 15,
    20, 30, 31, 9, 21, 16, 32, 13, 11, 22]

/-- `A385883` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 71) : A385883 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 71) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 71) : fz n = data[n.toNat - 1]! := sorry

end A385883
