import LOEIS.A092.A092185.Defs

set_option linter.unusedVariables false

/-!
# A092185

a(n) = (5/6)*n^3+(5/2)*n^2+(8/3)*n.

The 43 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A092185

/-- Known terms of `A092185`, starting at index `0`. -/
def data : List retType :=
  [0, 6, 22, 53, 104, 180, 286, 427, 608, 834,
    1110, 1441, 1832, 2288, 2814, 3415, 4096, 4862, 5718, 6669,
    7720, 8876, 10142, 11523, 13024, 14650, 16406, 18297, 20328, 22504,
    24830, 27311, 29952, 32758, 35734, 38885, 42216, 45732, 49438, 53339,
    57440, 61746, 66262]

/-- `A092185` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 43) : A092185 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 43) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 43) : fz n = data[n.toNat]! := sorry

end A092185
