import LOEIS.A009.A009163.Defs

set_option linter.unusedVariables false

/-!
# A009163

Expansion of e.g.f.: cosh(tan(x)*log(1+x)).

The 21 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A009163

/-- Known terms of `A009163`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 0, 0, 12, -60, 570, -3780, 36960, -326592,
    3712200, -41836080, 554861736, -7563345504, 114963916704, -1819859452320, 31173297642240, -558346710891904, 10642982507666880, -212150797420894848,
    4456607540110934912]

/-- `A009163` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 21) : A009163 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 21) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 21) : fz n = data[n.toNat]! := sorry

end A009163
