import LOEIS.A358.A358603.Defs

set_option linter.unusedVariables false

/-!
# A358603

a(n) = Sum_{k=0..floor(n/2)} (-1)^k * (n-k)!/(n-2*k)!.

The 33 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A358603

/-- Known terms of `A358603`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 0, -1, 0, 3, 2, -9, -12, 35,
    78, -153, -544, 723, 4170, -3337, -35028, 10851, 320678, 57255,
    -3178152, -2190253, 33864546, 42120183, -385314460, -719159517, 4649508222, 12033407591, -59076411312, -204022615725,
    784134861818, 3554417974647, -10768948801764]

/-- `A358603` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 33) : A358603 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 33) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 33) : fz n = data[n.toNat]! := sorry

end A358603
