import LOEIS.A132.A132813.Defs

set_option linter.unusedVariables false

/-!
# A132813

Triangle read by rows: A001263 * A127648 as infinite lower triangular matrices.

The 55 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A132813

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 2, 1, 6, 3, 1, 12, 18, 4,
    1, 20, 60, 40, 5, 1, 30, 150, 200, 75,
    6, 1, 42, 315, 700, 525, 126, 7, 1, 56,
    588, 1960, 2450, 1176, 196, 8, 1, 72, 1008, 4704,
    8820, 7056, 2352, 288, 9, 1, 90, 1620, 10080, 26460,
    31752, 17640, 4320, 405, 10]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 55) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 55) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 55) : flatFz n = flatData[n.toNat]! := sorry

end A132813
