import LOEIS.A190.A190964.Defs

set_option linter.unusedVariables false

/-!
# A190964

a(n) = 3*a(n-1) - 10*a(n-2), with a(0)=0, a(1)=1.

The 28 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A190964

/-- Known terms of `A190964`, starting at index `0`. -/
def data : List retType :=
  [0, 1, 3, -1, -33, -89, 63, 1079, 2607, -2969,
    -34977, -75241, 124047, 1124551, 2133183, -4845961, -35869713, -59149529, 181248543, 1135240919,
    1593237327, -6572697209, -35650464897, -41224422601, 232831381167, 1110738369511, 1003901296863, -8095679804521]

/-- `A190964` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 28) : A190964 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 28) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 28) : fz n = data[n.toNat]! := sorry

end A190964
