import LOEIS.A281.A281251.Defs

set_option linter.unusedVariables false

/-!
# A281251

T(n,k)=Number of nXk 0..2 arrays with no element equal to more than one of its horizontal, vertical and antidiagonal neighbors, with the exception of exactly two elements, and with new values introduced in order 0 sequentially upwards.

The 43 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A281251

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [0, 0, 0, 0, 0, 0, 1, 12, 12, 1,
    2, 139, 443, 139, 2, 9, 1222, 8489, 8489, 1222,
    9, 34, 9151, 105368, 197429, 105368, 9151, 34, 124, 63138,
    1113148, 3291920, 3291920, 1113148, 63138, 124, 432, 412070, 10598099, 47427679,
    76670685, 47427679, 10598099]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 44) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 44) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 44) : flatFz n = flatData[n.toNat - 1]! := sorry

end A281251
