import LOEIS.A044.A044440.Defs

set_option linter.unusedVariables false

/-!
# A044440

Numbers n such that string 2,1 occurs in the base 3 representation of n but not of n+1.

The 49 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A044440

/-- Known terms of `A044440`, starting at index `1`. -/
def data : List retType :=
  [7, 16, 23, 25, 34, 43, 50, 52, 61, 71,
    77, 79, 88, 97, 104, 106, 115, 124, 131, 133,
    142, 152, 158, 160, 169, 178, 185, 187, 215, 223,
    233, 239, 241, 250, 259, 266, 268, 277, 286, 293,
    295, 304, 314, 320, 322, 331, 340, 347, 349]

/-- `A044440` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 50) : A044440 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 50) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 50) : fz n = data[n.toNat - 1]! := sorry

end A044440
