import LOEIS.A374.A374627.Defs

set_option linter.unusedVariables false

/-!
# A374627

Expansion of Product_{k>=0} 1 / (1 - x^(3^k))^3.

The 47 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A374627

/-- Known terms of `A374627`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 6, 13, 24, 39, 64, 99, 144, 212,
    303, 417, 578, 786, 1041, 1382, 1809, 2322, 2985, 3798,
    4761, 5973, 7434, 9144, 11247, 13743, 16632, 20126, 24225, 28929,
    34541, 41061, 48489, 57242, 67320, 78723, 92029, 107238, 124350, 144151,
    166641, 191820, 220729, 253368, 289737, 331218, 377811]

/-- `A374627` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 47) : A374627 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 47) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 47) : fz n = data[n.toNat]! := sorry

end A374627
