import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A094669

Number of halving and tripling steps for 10^n to reach 1 in '3x+1' problem.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A094669

/-- Index type of `A094669` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A094669`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A094669

/-- Number of halving and tripling steps for 10^n to reach 1 in '3x+1' problem. -/
def A094669 : A094669.argType → A094669.retType := sorry

namespace A094669

/-- Relation that defines `A094669`. -/
def prop : argType → retType → Prop := sorry

/-- `A094669` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A094669` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A094669 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A094669 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A094669 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A094669
