import LOEIS.A313.A313291.Defs

set_option linter.unusedVariables false

/-!
# A313291

Coordination sequence Gal.4.101.1 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A313291

/-- Known terms of `A313291`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 9, 15, 21, 27, 32, 38, 44, 50,
    54, 58, 64, 70, 76, 80, 86, 92, 100, 104,
    108, 110, 118, 124, 132, 134, 140, 144, 154, 158,
    164, 164, 172, 176, 186, 188, 196, 198, 208, 210,
    218, 218, 228, 230, 240, 240, 250, 252, 264, 264]

/-- `A313291` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A313291 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A313291
