import LOEIS.A234.A234867.Defs

set_option linter.unusedVariables false

/-!
# A234867

T(n,k)=Number of (n+2)X(k+2) 0..3 arrays with each 3X3 subblock having the sum of its 72 absolute element differences equal to 52, and no adjacent elements equal.

The 28 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A234867

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [2216, 11714, 11714, 61954, 56100, 61954, 326786, 272878, 272878, 326786,
    1791552, 1375612, 1241772, 1375612, 1791552, 9897540, 7418922, 6113796, 6113796, 7418922,
    9897540, 54119058, 41004436, 33431812, 29472954, 33431812, 41004436, 54119058]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 29) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 29) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 29) : flatFz n = flatData[n.toNat - 1]! := sorry

end A234867
