import LOEIS.A088.A088016.Defs

set_option linter.unusedVariables false

/-!
# A088016

To obtain a(n+1), add the square of the n-th partial sum to the n-th partial sum of the squares, then divide this result by a(n), for all n >= 0, with a(0)=1.

The 26 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A088016

/-- Known terms of `A088016`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 6, 17, 56, 179, 576, 1851, 5950, 19125,
    61474, 197597, 635140, 2041543, 6562172, 21092919, 67799386, 217928905, 700493182, 2251609065,
    7237391472, 23263290299, 74775653304, 240352858739, 772570939222, 2483290023101]

/-- `A088016` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 26) : A088016 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 26) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 26) : fz n = data[n.toNat]! := sorry

end A088016
