import LOEIS.A276.A276205.Defs

set_option linter.unusedVariables false

/-!
# A276205

a(0) = a(2) = a(3) = 0. For n>2 a(n) is the smallest nonnegative integer such that there is no arithmetic progression j,k,m,n (of length 4) such that a(j)+a(k)+a(m) = a(n).

The 118 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A276205

/-- Known terms of `A276205`, starting at index `0`. -/
def data : List retType :=
  [0, 0, 0, 1, 0, 0, 2, 0, 0, 0,
    1, 2, 1, 3, 0, 0, 0, 4, 0, 1,
    2, 2, 3, 1, 4, 0, 0, 1, 0, 0,
    0, 5, 3, 0, 7, 1, 0, 4, 2, 4,
    2, 3, 5, 1, 1, 4, 1, 3, 0, 0,
    0, 1, 0, 0, 2, 0, 0, 0, 9, 2,
    8, 10, 0, 4, 0, 0, 0, 2, 1, 7,
    13, 4, 12, 4, 6, 7, 4, 4, 2, 0,
    10, 2, 2, 1, 3, 1, 0, 0, 0, 12,
    0, 9, 1, 0, 5, 2, 1, 17, 0, 3,
    5, 0, 1, 1, 0, 0, 8, 3, 0, 0,
    0, 15, 12, 9, 10, 11, 1, 5]

/-- `A276205` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 118) : A276205 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 118) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 118) : fz n = data[n.toNat]! := sorry

end A276205
