import LOEIS.A356.A356853.Defs

set_option linter.unusedVariables false

/-!
# A356853

Number of permutations p of [2n+1] such that at most one element of {p(1),...,p(i-1)} is between p(i) and p(i+1) for all i <= 2n and p(2n+1) = n+1.

The 20 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A356853

/-- Known terms of `A356853`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 20, 216, 2720, 36228, 503216, 7171404, 104142520, 1533200656,
    22811374568, 342216338652, 5168324302672, 78483423004680, 1197266739443160, 18335055482658748, 281714880491273736, 4340894020114398672, 67055152953864109240, 1038097819961270208088]

/-- `A356853` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 20) : A356853 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 20) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 20) : fz n = data[n.toNat]! := sorry

end A356853
