import LOEIS.A011.A011400.Defs

set_option linter.unusedVariables false

/-!
# A011400

Decimal expansion of 11th root of 18.

The 99 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A011400

/-- Known terms of `A011400`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 0, 0, 5, 1, 5, 9, 4, 8,
    1, 2, 0, 2, 8, 8, 9, 8, 5, 5,
    9, 5, 6, 1, 9, 2, 7, 7, 2, 0,
    5, 2, 5, 6, 0, 9, 6, 6, 0, 7,
    7, 3, 1, 9, 2, 2, 5, 6, 7, 8,
    3, 1, 0, 4, 9, 6, 1, 9, 1, 2,
    6, 5, 5, 0, 8, 5, 9, 0, 1, 3,
    3, 0, 3, 6, 3, 6, 2, 9, 5, 2,
    5, 7, 5, 0, 0, 1, 7, 6, 1, 8,
    9, 7, 0, 0, 1, 1, 2, 6, 9]

/-- `A011400` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 100) : A011400 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 100) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 100) : fz n = data[n.toNat - 1]! := sorry

end A011400
