import LOEIS.A238.A238080.Defs

set_option linter.unusedVariables false

/-!
# A238080

Number of (n+1)X(7+1) 0..3 arrays with the maximum plus the minimum of every 2X2 subblock differing from its horizontal and vertical neighbors by exactly one.

The 10 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A238080

/-- Known terms of `A238080`, starting at index `1`. -/
def data : List retType :=
  [14349272, 831852752, 39928365220, 2220366275092, 146517793924666, 10041551776656136, 747061315866664736, 49595489178884317916, 3498270077544089978148, 246596323750056582153608]

/-- `A238080` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 11) : A238080 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 11) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 11) : fz n = data[n.toNat - 1]! := sorry

end A238080
