import LOEIS.A174.A174704.Defs

set_option linter.unusedVariables false

/-!
# A174704

The number of permutations p of {1,...,n} such that |p(i)-p(i+1)| is in {2,3,4} for all i from 1 to n-1.

The 36 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A174704

/-- Known terms of `A174704`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 0, 0, 2, 14, 60, 152, 256, 464,
    1124, 3114, 8324, 20166, 44958, 97666, 217792, 501356, 1163776, 2668126,
    6006712, 13363390, 29660118, 66006498, 147147006, 327471130, 725850010, 1602363242, 3527859498, 7756716420,
    17040151108, 37393219368, 81932669910, 179223992670, 391448289188, 853909743368]

/-- `A174704` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 36) : A174704 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 36) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 36) : fz n = data[n.toNat]! := sorry

end A174704
