import LOEIS.A354.A354732.Defs

set_option linter.unusedVariables false

/-!
# A354732

Lexicographically earliest infinite sequence of distinct positive integers such that in any run of four consecutive terms there is only one pair of terms which share a prime divisor, the rest are all pairwise coprime.

The 69 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A354732

/-- Known terms of `A354732`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 3, 4, 5, 8, 7, 6, 11, 9,
    13, 12, 17, 10, 19, 14, 23, 16, 15, 21,
    29, 22, 20, 27, 31, 25, 18, 24, 37, 35,
    26, 32, 33, 41, 28, 34, 39, 43, 38, 40,
    47, 49, 30, 36, 53, 59, 42, 44, 61, 65,
    45, 46, 67, 51, 50, 52, 71, 57, 56, 58,
    55, 69, 62, 63, 73, 64, 68, 75, 77]

/-- `A354732` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 70) : A354732 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 70) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 70) : fz n = data[n.toNat - 1]! := sorry

end A354732
