import LOEIS.A119.A119233.Defs

set_option linter.unusedVariables false

/-!
# A119233

Numbers k such that the k-th triangular number contains only digits {6,7,9}.

The 5 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A119233

/-- Known terms of `A119233`, starting at index `1`. -/
def data : List retType :=
  [3, 11, 36, 36817576, 365512507857054543]

/-- `A119233` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 6) : A119233 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 6) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 6) : fz n = data[n.toNat - 1]! := sorry

end A119233
