import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A275112

Zero together with the partial sums of A064412.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A275112

/-- Index type of `A275112` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A275112`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A275112

/-- Zero together with the partial sums of A064412. -/
def A275112 : A275112.argType → A275112.retType := sorry

namespace A275112

/-- Relation that defines `A275112`. -/
def prop : argType → retType → Prop := sorry

/-- `A275112` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A275112` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A275112 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A275112 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A275112 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A275112
