import LOEIS.A367.A367914.Defs

set_option linter.unusedVariables false

/-!
# A367914

Movement sequence in the counter-clockwise undulating spiral, whereby 1, 2, 3, 4 represent moves to the right, down, left and up.

The 94 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A367914

/-- Known terms of `A367914`, starting at index `1`. -/
def data : List retType :=
  [1, 4, 3, 4, 3, 2, 3, 2, 1, 2,
    1, 2, 1, 4, 1, 4, 1, 4, 3, 4,
    3, 4, 3, 4, 3, 2, 3, 2, 3, 2,
    3, 2, 1, 2, 1, 2, 1, 2, 1, 2,
    1, 4, 1, 4, 1, 4, 1, 4, 1, 4,
    3, 4, 3, 4, 3, 4, 3, 4, 3, 4,
    3, 2, 3, 2, 3, 2, 3, 2, 3, 2,
    3, 2, 1, 2, 1, 2, 1, 2, 1, 2,
    1, 2, 1, 2, 1, 4, 1, 4, 1, 4,
    1, 4, 1, 4]

/-- `A367914` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 95) : A367914 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 95) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 95) : fz n = data[n.toNat - 1]! := sorry

end A367914
