import LOEIS.A167.A167637.Defs

set_option linter.unusedVariables false

/-!
# A167637

Triangle read by rows: T(n,k) is the number of Dyck paths of semilength n, having no ascents and no descents of length 1, and having k peaks at even level.

The 72 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A167637

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 0, 0, 1, 1, 0, 0, 1, 1, 2,
    2, 0, 1, 3, 3, 1, 5, 8, 4, 0,
    5, 13, 12, 6, 1, 15, 32, 27, 8, 0,
    21, 59, 61, 33, 10, 1, 51, 134, 147, 76,
    15, 0, 85, 267, 327, 208, 75, 15, 1, 188,
    584, 771, 528, 186, 26, 0, 344, 1209, 1734, 1329,
    585, 150, 21, 1, 730, 2608, 4008, 3344, 1595, 408,
    42, 0]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 72) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 72) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 72) : flatFz n = flatData[n.toNat]! := sorry

end A167637
