import LOEIS.A260.A260327.Defs

set_option linter.unusedVariables false

/-!
# A260327

Triangle read by rows: T(n,k) (0 <= k <= n) gives numerators of coefficients in Nørlund's polynomials D_{2n}(x).

The 45 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A260327

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 0, -1, 0, 2, 5, 0, -16, -42, -35,
    0, 144, 404, 420, 175, 0, -768, -2288, -2684, -1540,
    -385, 0, 1061376, 3327584, 4252248, 2862860, 1051050, 175175, 0, -552960,
    -1810176, -2471456, -1849848, -820820, -210210, -25025, 0, 200005632, 679395072, 978649472,
    792548432, 397517120, 125925800, 23823800, 2127125]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 45) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 45) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 45) : flatFz n = flatData[n.toNat]! := sorry

end A260327
