import LOEIS.A220.A220581.Defs

set_option linter.unusedVariables false

/-!
# A220581

Equals one maps: number of 3Xn binary arrays indicating the locations of corresponding elements equal to exactly one of their horizontal and antidiagonal neighbors in a random 0..1 3Xn array.

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A220581

/-- Known terms of `A220581`, starting at index `1`. -/
def data : List retType :=
  [1, 32, 91, 1441, 8334, 64497, 436288, 3036588, 21023792, 146254012,
    1011489196, 7016643627, 48603225482, 336693889957, 2332461879768, 16156948253940, 111913294295697, 775187951935208, 5369332881497134, 37190288381188178]

/-- `A220581` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 21) : A220581 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : fz n = data[n.toNat - 1]! := sorry

end A220581
