import LOEIS.A314.A314520.Defs

set_option linter.unusedVariables false

/-!
# A314520

Coordination sequence Gal.6.585.2 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A314520

/-- Known terms of `A314520`, starting at index `0`. -/
def data : List retType :=
  [1, 5, 8, 14, 20, 24, 28, 33, 40, 43,
    50, 52, 58, 61, 69, 73, 78, 84, 85, 93,
    96, 102, 107, 114, 117, 119, 127, 130, 136, 143,
    146, 151, 152, 163, 163, 171, 177, 179, 186, 187,
    196, 197, 207, 210, 213, 220, 221, 230, 233, 239]

/-- `A314520` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A314520 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A314520
