import LOEIS.A348.A348453.Defs

set_option linter.unusedVariables false

/-!
# A348453

Irregular triangle read by rows: T(n,k) (n >= 1, 1 <= k <= number of divisors of n^2) is the number of ways to tile an n X n chessboard with d_k rook-connected polyominoes of equal area, where d_k is the k-th divisor of n^2.

The 28 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A348453

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 1, 2, 1, 1, 10, 1, 1, 70, 117,
    36, 1, 1, 4006, 1, 1, 80518, 264500, 442791, 451206,
    178939, 80092, 6728, 1, 1, 158753814, 1, 7157114189]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 29) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 29) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 29) : flatFz n = flatData[n.toNat - 1]! := sorry

end A348453
