import LOEIS.A245.A245489.Defs

set_option linter.unusedVariables false

/-!
# A245489

a(n) = (1^n + (-2)^n + 4^n)/3.

The 26 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A245489

/-- Known terms of `A245489`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 7, 19, 91, 331, 1387, 5419, 21931, 87211,
    349867, 1397419, 5593771, 22366891, 89483947, 357903019, 1431677611, 5726579371, 22906579627, 91625794219,
    366504225451, 1466014804651, 5864063412907, 23456245263019, 93824997829291, 375299957762731]

/-- `A245489` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 26) : A245489 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 26) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 26) : fz n = data[n.toNat]! := sorry

end A245489
