import LOEIS.A082.A082677.Defs

set_option linter.unusedVariables false

/-!
# A082677

Arises from a social choice theory problem. Sequence is a transformation of the number of non-transitive quasitransitive distinct profiles with 3 alternatives and strict individual preferences.

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A082677

/-- Known terms of `A082677`, starting at index `1`. -/
def data : List retType :=
  [1, 9, 76, 641, 5436, 46368, 397545, 3423393, 29589844, 256570304,
    2230766385, 19441407752, 169784304145, 1485444035889, 13017106358316, 114234338588193, 1003781095722180, 8830530576006408, 77766568112582169, 685514394515339496]

/-- `A082677` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 21) : A082677 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : fz n = data[n.toNat - 1]! := sorry

end A082677
