import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A346523

Number of sum pyramids for n.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A346523

/-- Index type of `A346523` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A346523`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A346523

/-- Number of sum pyramids for n. -/
def A346523 : A346523.argType → A346523.retType := sorry

namespace A346523

/-- Relation that defines `A346523`. -/
def prop : argType → retType → Prop := sorry

/-- `A346523` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A346523` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A346523 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A346523 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A346523 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A346523
