import LOEIS.A319.A319824.Defs

set_option linter.unusedVariables false

/-!
# A319824

Numbers that are not the sum of distinct lucky-indexed lucky numbers.

The 66 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A319824

/-- Known terms of `A319824`, starting at index `1`. -/
def data : List retType :=
  [2, 3, 4, 5, 6, 9, 10, 11, 12, 13,
    14, 15, 16, 17, 18, 19, 20, 23, 24, 25,
    26, 27, 30, 33, 34, 35, 36, 37, 40, 41,
    42, 43, 44, 45, 46, 47, 48, 51, 54, 55,
    58, 61, 62, 65, 66, 67, 68, 69, 72, 73,
    74, 75, 76, 79, 82, 83, 86, 89, 90, 93,
    96, 97, 98, 99, 100, 103]

/-- `A319824` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 67) : A319824 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 67) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 67) : fz n = data[n.toNat - 1]! := sorry

end A319824
