import LOEIS.A082.A082471.Defs

set_option linter.unusedVariables false

/-!
# A082471

a(1)=1, a(n) = Sum_{k=1..n-1} Fibonacci(k)*a(k).

The 19 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A082471

/-- Known terms of `A082471`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 2, 6, 24, 144, 1296, 18144, 399168, 13970880,
    782369280, 70413235200, 10209919104000, 2389121070336000, 903087764587008000, 551786624162661888000, 545165184672709945344000, 871173965106990492659712000, 2251984699801570423525355520000]

/-- `A082471` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 20) : A082471 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 20) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 20) : fz n = data[n.toNat - 1]! := sorry

end A082471
