import LOEIS.A365.A365384.Defs

set_option linter.unusedVariables false

/-!
# A365384

Lexicographically earliest infinite sequence such that a(i) = a(j) => A351251(i) = A351251(j) for all i, j >= 0, where A351251(n) is the denominator of n / A276086(n).

The 92 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A365384

/-- Known terms of `A365384`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 3, 2, 4, 5, 6, 7, 8, 7,
    4, 9, 10, 11, 12, 7, 13, 14, 15, 16,
    12, 16, 17, 18, 19, 11, 20, 21, 22, 23,
    24, 25, 26, 25, 27, 5, 28, 29, 30, 29,
    27, 31, 10, 32, 33, 29, 34, 35, 36, 16,
    30, 37, 38, 39, 40, 37, 20, 41, 42, 43,
    44, 45, 46, 25, 47, 48, 49, 50, 51, 50,
    27, 52, 53, 54, 55, 45, 56, 35, 57, 58,
    55, 58, 59, 60, 40, 58, 61, 62, 63, 64,
    65, 45]

/-- `A365384` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 92) : A365384 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 92) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 92) : fz n = data[n.toNat]! := sorry

end A365384
