import LOEIS.A148.A148540.Defs

set_option linter.unusedVariables false

/-!
# A148540

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, -1), (-1, -1, 1), (-1, 0, 0), (1, -1, -1), (1, 1, 0)}.

The 30 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A148540

/-- Known terms of `A148540`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 5, 19, 45, 167, 443, 1687, 5081,
    19851, 61949, 242911, 795239, 3205607, 10806745, 43543547, 149722163, 611995035, 2158558103,
    8864811287, 31612799289, 130436796397, 473156526527, 1966155354111, 7206688904867, 29996095281917, 111044220066677, 464651051449543, 1737431367642797]

/-- `A148540` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 30) : A148540 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 30) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 30) : fz n = data[n.toNat]! := sorry

end A148540
