import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A230492

Numbers such that the sequence of all possible sums of divisors of n is increasing but not strictly so, the sums being ordered by their characteristic functions, seen as binary numbers (see example).

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A230492

/-- Index type of `A230492` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A230492`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A230492

/-- Numbers such that the sequence of all possible sums of divisors of n is increasing but not strictly so, the sums being ordered by their characteristic functions, seen as binary numbers (see example). -/
def A230492 : A230492.argType → A230492.retType := sorry

namespace A230492

/-- Relation that defines `A230492`. -/
def prop : argType → retType → Prop := sorry

/-- `A230492` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A230492` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A230492 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A230492 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A230492 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A230492
