import LOEIS.A355.A355721.Defs

set_option linter.unusedVariables false

/-!
# A355721

Square table, read by antidiagonals: the g.f. for row n is given recursively by (2*n-1)*x*R(n,x) = 1 + (2*n-3)*x - 1/R(n-1,x) for n >= 1 with the initial value R(0,x) = Sum_{k >= 0} A112934(k+1)*x^k.

The 55 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A355721

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 2, 1, 2, 6, 1, 2, 10, 26,
    1, 2, 14, 74, 158, 1, 2, 18, 138, 706,
    1282, 1, 2, 22, 218, 1686, 8162, 13158, 1, 2,
    26, 314, 3194, 24162, 110410, 163354, 1, 2, 30, 426,
    5326, 53890, 394254, 1708394, 2374078, 1, 2, 34, 554, 8178,
    102722, 1019250, 7191018, 29752066, 39456386]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 55) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 55) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 55) : flatFz n = flatData[n.toNat]! := sorry

end A355721
