import LOEIS.A322.A322879.Defs

set_option linter.unusedVariables false

/-!
# A322879

Number of set partitions of [n] such that the maximal absolute difference between the least elements of consecutive blocks equals six.

The 21 terms known to OEIS, indexed from `6`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A322879

/-- Known terms of `A322879`, starting at index `6`. -/
def data : List retType :=
  [0, 1, 35, 413, 3709, 30396, 242366, 1934021, 15653524, 129267234,
    1091892025, 9444993005, 83722879838, 760771479660, 7087056828919, 67674638461955, 662248199987728, 6638947646238102, 68153572265860585, 716151632403862252,
    7699437833837232406]

/-- `A322879` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 27) : A322879 n = data[n.val - 6]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 6 ≤ n) (h : n < 27) : fn n = data[n - 6]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 6 ≤ n) (h : n < 27) : fz n = data[n.toNat - 6]! := sorry

end A322879
