import LOEIS.A135.A135692.Defs

set_option linter.unusedVariables false

/-!
# A135692

a(n) = a(n-2) - 2*( a(floor(n/2)) - a(abs(floor(n/2) - 1)) ) if (n mod 2) = 0, otherwise a(n-1) - 2*( a(abs(floor(n/2) - 2)) - a(abs(floor(n/2) - 3)) ), with a(0) = 0, a(1) = 1, a(2) = -2, a(3) = -4.

The 74 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A135692

/-- Known terms of `A135692`, starting at index `0`. -/
def data : List retType :=
  [0, 1, -2, -4, 4, 6, 8, 6, -8, -2,
    -12, -8, -16, -32, -12, -16, 16, 12, 4, 8,
    24, 52, 16, 4, 32, 52, 64, 56, 24, 40,
    32, 64, -32, -72, -24, -16, -8, -72, -16, -8,
    -48, -32, -104, -112, -32, -64, -8, -64, -64, 8,
    -104, -80, -128, -184, -112, -152, -48, -72, -80, -64,
    -64, 0, -128, -160, 64, 80, 144, 80, 48, 240,
    32, 112, 16, -80]

/-- `A135692` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 74) : A135692 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 74) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 74) : fz n = data[n.toNat]! := sorry

end A135692
