import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A245512

Records in A245511: smallest m > 1 such that the largest odd number less than m^k is prime for every 0 < k < n, but not for k = n.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A245512

/-- Index type of `A245512` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A245512`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A245512

/-- Records in A245511: smallest m > 1 such that the largest odd number less than m^k is prime for every 0 < k < n, but not for k = n. -/
def A245512 : A245512.argType → A245512.retType := sorry

namespace A245512

/-- Relation that defines `A245512`. -/
def prop : argType → retType → Prop := sorry

/-- `A245512` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A245512` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A245512 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A245512 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A245512 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A245512
