import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A217179

a(n) is the number of digits in the decimal representation of the smallest power of n that contains four consecutive identical digits.

OEIS offset `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A217179

/-- Index type of `A217179` (OEIS offset `2`). -/
abbrev argType : Type := {n : Nat // 2 ≤ n}

/-- Value type of `A217179`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 2

end A217179

/-- a(n) is the number of digits in the decimal representation of the smallest power of n that contains four consecutive identical digits. -/
def A217179 : A217179.argType → A217179.retType := sorry

namespace A217179

/-- Relation that defines `A217179`. -/
def prop : argType → retType → Prop := sorry

/-- `A217179` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A217179` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A217179 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 2 ≤ n) : fn n = A217179 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 2 ≤ n) : fz n = A217179 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 2 ≤ n) : fn n = fz (n : Int) := sorry

end A217179
