import LOEIS.A312.A312588.Defs

set_option linter.unusedVariables false

/-!
# A312588

Coordination sequence Gal.6.518.1 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A312588

/-- Known terms of `A312588`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 8, 14, 19, 22, 27, 30, 35, 42,
    48, 48, 58, 55, 65, 69, 77, 73, 87, 80,
    94, 97, 106, 98, 116, 105, 123, 124, 135, 123,
    146, 130, 152, 151, 164, 148, 175, 155, 181, 179,
    193, 173, 204, 180, 210, 206, 222, 198, 234, 205]

/-- `A312588` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A312588 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A312588
