import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A161995

a(n) represents the minimum number k, not already present in the sequence, whose digit sum is equal to the digital root of Sum_{j=0..n-1} a(j), with a(0)=0 and a(1)=1.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A161995

/-- Index type of `A161995` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A161995`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A161995

/-- a(n) represents the minimum number k, not already present in the sequence, whose digit sum is equal to the digital root of Sum_{j=0..n-1} a(j), with a(0)=0 and a(1)=1. -/
def A161995 : A161995.argType → A161995.retType := sorry

namespace A161995

/-- Relation that defines `A161995`. -/
def prop : argType → retType → Prop := sorry

/-- `A161995` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A161995` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A161995 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A161995 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A161995 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A161995
