import LOEIS.A051.A051023.Defs

set_option linter.unusedVariables false

/-!
# A051023

Middle column of rule-30 1-D cellular automaton, from a lone 1 cell.

The 102 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A051023

/-- Known terms of `A051023`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
    0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
    0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
    1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
    0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
    0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
    1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
    0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
    0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
    0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
    0, 1]

/-- `A051023` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 102) : A051023 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 102) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 102) : fz n = data[n.toNat]! := sorry

end A051023
