import LOEIS.A185.A185580.Defs

set_option linter.unusedVariables false

/-!
# A185580

Decimal expansion of Sum_{m,n,p = -infinity..infinity} (-1)^(m+n)/sqrt( m^2 + n^2 + (p-1/2)^2 ).

The 105 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A185580

/-- Known terms of `A185580`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 1, 9, 6, 7, 0, 5, 8, 6,
    9, 6, 7, 4, 3, 6, 2, 0, 0, 9,
    2, 9, 5, 2, 3, 3, 7, 8, 2, 8,
    6, 1, 0, 1, 7, 5, 3, 6, 7, 6,
    2, 7, 3, 4, 6, 3, 7, 2, 1, 9,
    1, 4, 8, 3, 8, 7, 1, 6, 8, 1,
    5, 4, 3, 5, 0, 4, 3, 9, 7, 9,
    1, 6, 8, 4, 9, 8, 9, 4, 7, 5,
    2, 5, 6, 6, 1, 3, 3, 8, 1, 1,
    9, 3, 2, 2, 7, 0, 0, 6, 9, 4,
    2, 2, 0, 2, 0]

/-- `A185580` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 106) : A185580 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 106) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 106) : fz n = data[n.toNat - 1]! := sorry

end A185580
