import LOEIS.A151.A151151.Defs

set_option linter.unusedVariables false

/-!
# A151151

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 1), (-1, 1, -1), (0, 1, 1), (1, 0, 0), (1, 1, 1)}.

The 27 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A151151

/-- Known terms of `A151151`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 11, 47, 205, 927, 4273, 19921, 93761, 444517,
    2118833, 10146089, 48764565, 235101077, 1136445415, 5505870237, 26727374589, 129968044895, 632964986425, 3086839690155,
    15072285466445, 73675540585185, 360497744553655, 1765544372027673, 8654028910135843, 42451454274028333, 208389423187010269]

/-- `A151151` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 27) : A151151 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 27) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 27) : fz n = data[n.toNat]! := sorry

end A151151
