import LOEIS.A019.A019284.Defs

set_option linter.unusedVariables false

/-!
# A019284

Let sigma_m (n) be result of applying sum-of-divisors function m times to n; call n (m,k)-perfect if sigma_m (n) = k*n; sequence gives the (2,7)-perfect numbers.

The 5 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A019284

/-- Known terms of `A019284`, starting at index `1`. -/
def data : List retType :=
  [24, 1536, 47360, 343976, 572941926400]

/-- `A019284` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 6) : A019284 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 6) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 6) : fz n = data[n.toNat - 1]! := sorry

end A019284
