import LOEIS.A116.A116673.Defs

set_option linter.unusedVariables false

/-!
# A116673

Row sums of triangle A116672, in which the binomial transform of the n-th row lists the Euler transform of the n-th sequence in A007318 (Pascal's Triangle).

The 27 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A116673

/-- Known terms of `A116673`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 4, 10, 26, 80, 262, 950, 3684, 15302,
    67470, 314912, 1549178, 8006194, 43324868, 244807122, 1440902090, 8815829144, 55963478926, 367981232894,
    2502358256292, 17573264810910, 127280664307590, 949633391273512, 7290427591709562, 57532132352904794, 466247761803745236]

/-- `A116673` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 28) : A116673 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 28) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 28) : fz n = data[n.toNat - 1]! := sorry

end A116673
