import LOEIS.A392.A392274.Defs

set_option linter.unusedVariables false

/-!
# A392274

Number of length n words over the alphabet [5] such that any prefix satisfies c(1) >= c(2), c(1) >= c(3), c(2) >= c(4), c(3) >= c(5), and c(4) >= c(5), where c(i) is the number of occurrences of the letter i.

The 28 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A392274

/-- Known terms of `A392274`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 8, 23, 73, 246, 867, 3166, 11839,
    45785, 179579, 717113, 2908753, 11954189, 49750400, 208980669, 885742796, 3787356399, 16314829868,
    70763117954, 308802296807, 1355046242737, 5978469864061, 26504591207399, 118019589079173, 527734730588274, 2368700497250917]

/-- `A392274` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 28) : A392274 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 28) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 28) : fz n = data[n.toNat]! := sorry

end A392274
