import LOEIS.A165.A165008.Defs

set_option linter.unusedVariables false

/-!
# A165008

Consider the base-3 Kaprekar map x->K(x) described in A164993. Sequence gives the smallest number that belongs to a cycle of length n under repeated iteration of this map, or -1 if there is no cycle of length n.

The 12 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A165008

/-- Known terms of `A165008`, starting at index `1`. -/
def data : List retType :=
  [0, 32, 320, 26240, 1240024, 11160256, 2297798771761759543384, 15075857741528904364175224, 8135830264, 5931020266096,
    659002251784, 350220815692997944]

/-- `A165008` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 13) : A165008 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 13) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 13) : fz n = data[n.toNat - 1]! := sorry

end A165008
