import LOEIS.A148.A148558.Defs

set_option linter.unusedVariables false

/-!
# A148558

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, -1), (-1, 0, 0), (0, -1, 1), (0, 1, 0), (1, -1, 0)}.

The 31 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A148558

/-- Known terms of `A148558`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 6, 18, 47, 151, 444, 1474, 4751,
    15980, 54263, 188405, 654422, 2326335, 8306683, 29854080, 108664545, 397687346, 1460169528,
    5417588114, 20172041308, 75314119276, 283455950368, 1069878059090, 4046382347316, 15403955808207, 58772144664246, 224605482392280, 862987851193742,
    3321884504024162]

/-- `A148558` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 31) : A148558 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 31) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 31) : fz n = data[n.toNat]! := sorry

end A148558
