import LOEIS.A094.A094053.Defs

set_option linter.unusedVariables false

/-!
# A094053

Triangle read by rows: T(n,k) = k*(n-k), 1 <= k <= n.

The 79 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A094053

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [0, 1, 0, 2, 2, 0, 3, 4, 3, 0,
    4, 6, 6, 4, 0, 5, 8, 9, 8, 5,
    0, 6, 10, 12, 12, 10, 6, 0, 7, 12,
    15, 16, 15, 12, 7, 0, 8, 14, 18, 20,
    20, 18, 14, 8, 0, 9, 16, 21, 24, 25,
    24, 21, 16, 9, 0, 10, 18, 24, 28, 30,
    30, 28, 24, 18, 10, 0, 11, 20, 27, 32,
    35, 36, 35, 32, 27, 20, 11, 0, 12]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 80) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 80) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 80) : flatFz n = flatData[n.toNat - 1]! := sorry

end A094053
