import LOEIS.A178.A178735.Defs

set_option linter.unusedVariables false

/-!
# A178735

a(n) = n XOR 9n, where XOR is bitwise XOR.

The 55 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A178735

/-- Known terms of `A178735`, starting at index `0`. -/
def data : List retType :=
  [0, 8, 16, 24, 32, 40, 48, 56, 64, 88,
    80, 104, 96, 120, 112, 136, 128, 136, 176, 184,
    160, 168, 208, 216, 192, 248, 240, 232, 224, 280,
    272, 264, 256, 264, 272, 280, 352, 360, 368, 376,
    320, 344, 336, 424, 416, 440, 432, 392, 384, 392,
    496, 504, 480, 488, 464]

/-- `A178735` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 55) : A178735 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 55) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 55) : fz n = data[n.toNat]! := sorry

end A178735
