import LOEIS.A098.A098188.Defs

set_option linter.unusedVariables false

/-!
# A098188

Irregular triangle with 4 columns which contains in each row the members of a 4-cycle under the map x->A063919(x), iteration of summing the proper-unitary divisors.

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A098188

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [263820, 263940, 280380, 280500, 395730, 395910, 420570, 420750, 172459210, 218725430,
    272130250, 218628662, 209524210, 246667790, 231439570, 230143790, 384121920, 384296640, 408233280, 408408000]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 21) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : flatFz n = flatData[n.toNat - 1]! := sorry

end A098188
