import LOEIS.A281.A281411.Defs

set_option linter.unusedVariables false

/-!
# A281411

Binary representation of the x-axis, from the origin to the right edge, of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 361", based on the 5-celled von Neumann neighborhood.

The 21 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A281411

/-- Known terms of `A281411`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 110, 1, 10000, 111, 1111000, 1000111, 110100000, 1011111,
    10110000000, 10001111111, 1100010000000, 10111111111, 100100010000000, 1100101111111, 10011111000000000, 110000111111111, 1011111000000000000, 1011110011111111111,
    110111101100000000000]

/-- `A281411` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 21) : A281411 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 21) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 21) : fz n = data[n.toNat]! := sorry

end A281411
