import LOEIS.A361.A361286.Defs

set_option linter.unusedVariables false

/-!
# A361286

Total over all partitions lambda of n, of factors of s_lambda in the skew Schur function s_( nu/lambda ) with (s_lambda)^2 = Sum( C(nu, lambda, lambda) s_nu ).

The 14 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A361286

/-- Known terms of `A361286`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 6, 18, 50, 138, 430, 1242, 3666, 10938,
    34598, 108098, 338634, 1058370]

/-- `A361286` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 14) : A361286 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 14) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 14) : fz n = data[n.toNat]! := sorry

end A361286
