import LOEIS.A061.A061642.Defs

set_option linter.unusedVariables false

/-!
# A061642

Decimal expansion of Hardy-Littlewood constant for prime quadruples.

The 105 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A061642

/-- Known terms of `A061642`, starting at index `1`. -/
def data : List retType :=
  [4, 1, 5, 1, 1, 8, 0, 8, 6, 3,
    2, 3, 7, 4, 1, 5, 7, 5, 7, 1,
    6, 5, 2, 8, 5, 5, 6, 1, 9, 5,
    9, 5, 3, 7, 5, 1, 5, 7, 9, 9,
    4, 1, 0, 0, 1, 9, 3, 3, 3, 9,
    6, 3, 0, 3, 2, 0, 2, 7, 1, 6,
    3, 3, 4, 9, 5, 2, 1, 9, 9, 8,
    3, 5, 8, 5, 0, 5, 3, 5, 5, 4,
    2, 9, 9, 8, 6, 8, 4, 3, 5, 7,
    3, 2, 0, 3, 1, 5, 1, 6, 6, 8,
    3, 3, 4, 0, 6]

/-- `A061642` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 106) : A061642 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 106) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 106) : fz n = data[n.toNat - 1]! := sorry

end A061642
