import LOEIS.A256.A256901.Defs

set_option linter.unusedVariables false

/-!
# A256901

Number of (n+2)X(5+2) 0..1 arrays with every 3X3 subblock sum of the two medians of the central row and column plus the two sums of the diagonal and antidiagonal nondecreasing horizontally and vertically.

The 21 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A256901

/-- Known terms of `A256901`, starting at index `1`. -/
def data : List retType :=
  [113474, 396712, 1948416, 4687873, 7212370, 12286621, 12230530, 19377777, 24869452, 35469812,
    54180018, 82633412, 128108016, 197244059, 304897422, 470254289, 720831904, 1099014235, 1665081428, 2507744625,
    3746976448]

/-- `A256901` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 22) : A256901 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 22) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 22) : fz n = data[n.toNat - 1]! := sorry

end A256901
