import LOEIS.A361.A361376.Defs

set_option linter.unusedVariables false

/-!
# A361376

Rewrite A129912(n), a product of distinct primorials P(i) = A002110(i) instead as a sum of powers 2^(i-1).

The 75 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A361376

/-- Known terms of `A361376`, starting at index `1`. -/
def data : List retType :=
  [0, 1, 2, 3, 4, 5, 6, 8, 7, 9,
    10, 16, 11, 17, 12, 13, 18, 19, 32, 14,
    33, 20, 15, 21, 34, 35, 22, 24, 64, 23,
    36, 25, 65, 37, 26, 66, 38, 27, 67, 40,
    128, 39, 41, 28, 68, 129, 29, 69, 42, 130,
    48, 43, 30, 70, 72, 131, 49, 31, 71, 44,
    73, 256, 132, 45, 50, 257, 133, 74, 51, 46,
    80, 75, 258, 134, 136]

/-- `A361376` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 76) : A361376 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 76) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 76) : fz n = data[n.toNat - 1]! := sorry

end A361376
