import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A115267

Primes of the form p*q*r-2, where p, q and r are distinct primes.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A115267

/-- Index type of `A115267` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A115267`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A115267

/-- Primes of the form p*q*r-2, where p, q and r are distinct primes. -/
def A115267 : A115267.argType → A115267.retType := sorry

namespace A115267

/-- Relation that defines `A115267`. -/
def prop : argType → retType → Prop := sorry

/-- `A115267` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A115267` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A115267 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A115267 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A115267 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A115267
