import LOEIS.A138.A138565.Defs

set_option linter.unusedVariables false

/-!
# A138565

Array read by rows: T(n,k) is the number of automorphisms of the k-th Abelian group of order n, where the ordering is such that the rows are nondecreasing.

The 68 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A138565

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 1, 2, 2, 6, 4, 2, 6, 4, 8,
    168, 6, 48, 4, 10, 4, 12, 12, 6, 8,
    8, 16, 96, 192, 20160, 16, 6, 48, 18, 8,
    24, 12, 10, 22, 8, 16, 336, 20, 480, 12,
    18, 108, 11232, 12, 36, 28, 8, 30, 16, 32,
    128, 384, 1536, 21504, 9999360, 20, 16, 24, 12, 36,
    96, 288, 36, 18, 24, 16, 32, 672]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 69) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 69) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 69) : flatFz n = flatData[n.toNat - 1]! := sorry

end A138565
