import LOEIS.A029.A029334.Defs

set_option linter.unusedVariables false

/-!
# A029334

Expansion of 1/((1-x^4)*(1-x^5)*(1-x^7)*(1-x^10)).

The 65 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A029334

/-- Known terms of `A029334`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
    2, 1, 2, 1, 3, 3, 2, 3, 3, 4,
    5, 4, 5, 4, 7, 7, 6, 7, 8, 9,
    10, 9, 11, 10, 13, 14, 13, 14, 15, 17,
    19, 17, 20, 19, 23, 24, 23, 25, 26, 29,
    31, 29, 33, 32, 37, 38, 38, 40, 41, 45,
    48, 46, 50, 50, 56]

/-- `A029334` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 65) : A029334 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 65) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 65) : fz n = data[n.toNat]! := sorry

end A029334
