import LOEIS.A004.A004852.Defs

set_option linter.unusedVariables false

/-!
# A004852

Numbers that are the sum of at most 12 positive 5th powers.

The 54 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A004852

/-- Known terms of `A004852`, starting at index `1`. -/
def data : List retType :=
  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
    10, 11, 12, 32, 33, 34, 35, 36, 37, 38,
    39, 40, 41, 42, 43, 64, 65, 66, 67, 68,
    69, 70, 71, 72, 73, 74, 96, 97, 98, 99,
    100, 101, 102, 103, 104, 105, 128, 129, 130, 131,
    132, 133, 134, 135]

/-- `A004852` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 55) : A004852 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 55) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 55) : fz n = data[n.toNat - 1]! := sorry

end A004852
