import LOEIS.A325.A325024.Defs

set_option linter.unusedVariables false

/-!
# A325024

Multiply-perfect numbers m from A007691 such that m*(m-tau(m))/sigma(m) is not an integer where k-tau(k) is the number of the non-divisors of k (A049820) and sigma(k) is the sum of the divisors of k (A000203).

The 16 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A325024

/-- Known terms of `A325024`, starting at index `1`. -/
def data : List retType :=
  [120, 523776, 459818240, 1476304896, 31998395520, 51001180160, 518666803200, 30823866178560, 740344994887680, 796928461056000,
    212517062615531520, 69357059049509038080, 87934476737668055040, 170206605192656148480, 1161492388333469337600, 1802582780370364661760]

/-- `A325024` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A325024 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 17) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 17) : fz n = data[n.toNat - 1]! := sorry

end A325024
