import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A388155

Decimal expansion of Gamma(3/4)^19 / Pi^(19/4).

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A388155

/-- Index type of `A388155` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A388155`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A388155

/-- Decimal expansion of Gamma(3/4)^19 / Pi^(19/4). -/
def A388155 : A388155.argType → A388155.retType := sorry

namespace A388155

/-- Relation that defines `A388155`. -/
def prop : argType → retType → Prop := sorry

/-- `A388155` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A388155` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A388155 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A388155 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A388155 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A388155
