import LOEIS.A076.A076504.Defs

set_option linter.unusedVariables false

/-!
# A076504

Numbers k such that (k-1, k+1) and (k/2-1, k/2+1) are both pairs of twin primes.

The 32 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A076504

/-- Known terms of `A076504`, starting at index `1`. -/
def data : List retType :=
  [12, 60, 1320, 1620, 4260, 5100, 6660, 6780, 11700, 12540,
    21060, 66360, 83220, 88260, 107100, 110880, 114660, 127680, 130200, 140760,
    141960, 144540, 148200, 149520, 157560, 161340, 163860, 175080, 186480, 204600,
    230940, 249540]

/-- `A076504` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 33) : A076504 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 33) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 33) : fz n = data[n.toNat - 1]! := sorry

end A076504
