import LOEIS.A143.A143447.Defs

set_option linter.unusedVariables false

/-!
# A143447

Expansion of 1/(x^k*(1-x-2*x^(k+1))) for k=4.

The 42 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A143447

/-- Known terms of `A143447`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 5, 7, 9, 11, 17, 27, 41, 59,
    81, 115, 169, 251, 369, 531, 761, 1099, 1601, 2339,
    3401, 4923, 7121, 10323, 15001, 21803, 31649, 45891, 66537, 96539,
    140145, 203443, 295225, 428299, 621377, 901667, 1308553, 1899003, 2755601, 3998355,
    5801689, 8418795]

/-- `A143447` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 42) : A143447 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 42) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 42) : fz n = data[n.toNat]! := sorry

end A143447
