import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A007746

Number of ways for n-3 nonintersecting loops to cross a line 2n times.

OEIS offset `4`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A007746

/-- Index type of `A007746` (OEIS offset `4`). -/
abbrev argType : Type := {n : Nat // 4 ≤ n}

/-- Value type of `A007746`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 4

end A007746

/-- Number of ways for n-3 nonintersecting loops to cross a line 2n times. -/
def A007746 : A007746.argType → A007746.retType := sorry

namespace A007746

/-- Relation that defines `A007746`. -/
def prop : argType → retType → Prop := sorry

/-- `A007746` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A007746` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A007746 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 4 ≤ n) : fn n = A007746 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 4 ≤ n) : fz n = A007746 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 4 ≤ n) : fn n = fz (n : Int) := sorry

end A007746
