import LOEIS.A220.A220715.Defs

set_option linter.unusedVariables false

/-!
# A220715

Number of ways to reciprocally link elements of an nX4 array either to themselves or to exactly two king-move neighbors, without consecutive collinear links.

The 16 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A220715

/-- Known terms of `A220715`, starting at index `1`. -/
def data : List retType :=
  [1, 118, 2243, 72923, 2126423, 63806966, 1902974315, 56814065240, 1695753689937, 50616199772781,
    1510818091855523, 45095791460540255, 1346044870553900218, 40177524253586319614, 1199241822560808863212, 35795659984527447229283]

/-- `A220715` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A220715 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 17) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 17) : fz n = data[n.toNat - 1]! := sorry

end A220715
