import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A107703

Sums of antidiagonals of number array A103209.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A107703

/-- Index type of `A107703` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A107703`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A107703

/-- Sums of antidiagonals of number array A103209. -/
def A107703 : A107703.argType → A107703.retType := sorry

namespace A107703

/-- Relation that defines `A107703`. -/
def prop : argType → retType → Prop := sorry

/-- `A107703` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A107703` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A107703 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A107703 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A107703 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A107703
