import LOEIS.A384.A384000.Defs

set_option linter.unusedVariables false

/-!
# A384000

Smallest number k with n distinct prime factors such that A010846(k) = A024718(n) (a tight lower bound), or -1 if such k does not exist.

The 7 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A384000

/-- Known terms of `A384000`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 6, 1001, 268801, 3433936673, 2603508937756211]

/-- `A384000` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 7) : A384000 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 7) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 7) : fz n = data[n.toNat]! := sorry

end A384000
