import LOEIS.A264.A264117.Defs

set_option linter.unusedVariables false

/-!
# A264117

Largest integer which cannot be partitioned using only parts from the set {perfect powers excluding the n smallest}.

The 43 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A264117

/-- Known terms of `A264117`, starting at index `1`. -/
def data : List retType :=
  [23, 55, 87, 94, 119, 178, 271, 312, 335, 403,
    501, 551, 598, 717, 861, 861, 903, 1022, 1119, 1248,
    1463, 1535, 1688, 2031, 2067, 2416, 2535, 2976, 3064, 3164,
    3407, 3552, 3552, 4023, 4143, 4416, 4633, 4663, 5424, 5424,
    5688, 6000, 6455]

/-- `A264117` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 44) : A264117 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 44) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 44) : fz n = data[n.toNat - 1]! := sorry

end A264117
