import LOEIS.A093.A093800.Defs

set_option linter.unusedVariables false

/-!
# A093800

Triangular numbers such that the least common multiple of a pair of successive terms is triangular.

The 9 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A093800

/-- Known terms of `A093800`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 6, 36, 2016, 26335, 53091360, 1420353154080, 70356589837262316000]

/-- `A093800` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 10) : A093800 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 10) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 10) : fz n = data[n.toNat - 1]! := sorry

end A093800
