import LOEIS.A280.A280521.Defs

set_option linter.unusedVariables false

/-!
# A280521

From the "Fibonachos" game: Number of phases of the following routine: during each phase, the player removes objects from a pile of n objects as the Fibonacci sequence until the pile contains fewer objects than the next Fibonacci number. The phases continue until the pile is empty.

The 87 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A280521

/-- Known terms of `A280521`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 2, 1, 2, 2, 1, 2, 2, 3,
    2, 1, 2, 2, 3, 2, 3, 3, 2, 1,
    2, 2, 3, 2, 3, 3, 2, 3, 3, 4,
    3, 2, 1, 2, 2, 3, 2, 3, 3, 2,
    3, 3, 4, 3, 2, 3, 3, 4, 3, 4,
    4, 3, 2, 1, 2, 2, 3, 2, 3, 3,
    2, 3, 3, 4, 3, 2, 3, 3, 4, 3,
    4, 4, 3, 2, 3, 3, 4, 3, 4, 4,
    3, 4, 4, 5, 4, 3, 2]

/-- `A280521` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 88) : A280521 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 88) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 88) : fz n = data[n.toNat - 1]! := sorry

end A280521
