import LOEIS.A004.A004937.Defs

set_option linter.unusedVariables false

/-!
# A004937

a(n) = round(n*phi^2), where phi is the golden ratio, A001622.

The 61 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A004937

/-- Known terms of `A004937`, starting at index `0`. -/
def data : List retType :=
  [0, 3, 5, 8, 10, 13, 16, 18, 21, 24,
    26, 29, 31, 34, 37, 39, 42, 45, 47, 50,
    52, 55, 58, 60, 63, 65, 68, 71, 73, 76,
    79, 81, 84, 86, 89, 92, 94, 97, 99, 102,
    105, 107, 110, 113, 115, 118, 120, 123, 126, 128,
    131, 134, 136, 139, 141, 144, 147, 149, 152, 154,
    157]

/-- `A004937` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 61) : A004937 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 61) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 61) : fz n = data[n.toNat]! := sorry

end A004937
