import LOEIS.A343.A343090.Defs

set_option linter.unusedVariables false

/-!
# A343090

Triangle read by rows: T(n,k) is the number of rooted toroidal maps with n edges and k faces and without separating cycles or isthmuses, n >= 2, k = 1..n-1.

The 45 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A343090

/-- Known terms of `flat`, starting at index `2`. -/
def flatData : List flatRetType :=
  [1, 4, 4, 10, 47, 10, 20, 240, 240, 20,
    35, 831, 2246, 831, 35, 56, 2282, 12656, 12656, 2282,
    56, 84, 5362, 52164, 109075, 52164, 5362, 84, 120, 11256,
    173776, 648792, 648792, 173776, 11256, 120, 165, 21690, 495820, 2978245,
    5360286, 2978245, 495820, 21690, 165]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 47) : flat n = flatData[n.val - 2]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 47) : flatFn n = flatData[n - 2]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 47) : flatFz n = flatData[n.toNat - 2]! := sorry

end A343090
