import LOEIS.A133.A133941.Defs

set_option linter.unusedVariables false

/-!
# A133941

E.g.f. satisfies: A(x) = x*(exp(tan(A(x)))).

The 21 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A133941

/-- Known terms of `A133941`, starting at index `0`. -/
def data : List retType :=
  [0, 1, 2, 9, 72, 825, 12192, 220353, 4708480, 116116497,
    3245839360, 101415497689, 3502465714176, 132486192976137, 5447446920323072, 241907419042038225, 11538444129924055040, 588321821566662253729, 31932991994214557417472, 1838324386624795978579753,
    111877161347530177330544640]

/-- `A133941` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 21) : A133941 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 21) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 21) : fz n = data[n.toNat]! := sorry

end A133941
