import LOEIS.A382.A382110.Defs

set_option linter.unusedVariables false

/-!
# A382110

Smallest number k such that k-n and k+n are consecutive primes and k has exactly n distinct prime factors.

The 18 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A382110

/-- Known terms of `A382110`, starting at index `1`. -/
def data : List retType :=
  [4, 15, 154, 3045, 22386, 2467465, 3015870, 368961285, 6326289970, 2313524242029,
    1568018377380, 5808562826801735, 1575649493651310, 6177821212870783905, 171718219950879367766, 2039004035049368722335, 13156579658122684173390, 112733682549950000276753015]

/-- `A382110` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 19) : A382110 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 19) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 19) : fz n = data[n.toNat - 1]! := sorry

end A382110
