import LOEIS.A230.A230931.Defs

set_option linter.unusedVariables false

/-!
# A230931

Number of black-square subarrays of (n+2) X (4+2) 0..3 arrays x(i,j) with each element diagonally or antidiagonally next to at least one element with value (x(i,j)+1) mod 4, no adjacent elements equal, and upper left element zero.

The 23 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A230931

/-- Known terms of `A230931`, starting at index `1`. -/
def data : List retType :=
  [8, 48, 232, 1242, 6896, 37984, 208172, 1142054, 6269172, 34409586,
    188850410, 1036485334, 5688689754, 31221981876, 171359511448, 940494098820, 5161833500756, 28330347062146, 155489043088298, 853390273229980,
    4683770286511852, 25706531669633084, 141088424473754084]

/-- `A230931` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 24) : A230931 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 24) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 24) : fz n = data[n.toNat - 1]! := sorry

end A230931
