import LOEIS.A322.A322808.Defs

set_option linter.unusedVariables false

/-!
# A322808

Lexicographically earliest such sequence a that a(i) = a(j) => f(i) = f(j) for all i, j, where f(n) = 0 if n is a squarefree number > 2, and f(n) = A097246(n) for all other numbers.

The 105 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A322808

/-- Known terms of `A322808`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 3, 4, 3, 3, 3, 5, 6, 3,
    3, 7, 3, 3, 3, 7, 3, 8, 3, 9,
    3, 3, 3, 10, 11, 3, 9, 12, 3, 3,
    3, 10, 3, 3, 3, 9, 3, 3, 3, 13,
    3, 3, 3, 14, 15, 3, 3, 16, 17, 18,
    3, 19, 3, 13, 3, 20, 3, 3, 3, 21,
    3, 3, 22, 16, 3, 3, 3, 23, 3, 3,
    3, 13, 3, 3, 12, 24, 3, 3, 3, 21,
    15, 3, 3, 25, 3, 3, 3, 26, 3, 27,
    3, 28, 3, 3, 3, 29, 3, 30, 31, 12,
    3, 3, 3, 32, 3]

/-- `A322808` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 106) : A322808 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 106) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 106) : fz n = data[n.toNat - 1]! := sorry

end A322808
