import LOEIS.A267.A267478.Defs

set_option linter.unusedVariables false

/-!
# A267478

Primes which are squares (mod 55).

The 57 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A267478

/-- Known terms of `A267478`, starting at index `1`. -/
def data : List retType :=
  [5, 11, 31, 59, 71, 89, 179, 181, 191, 199,
    229, 251, 269, 311, 331, 379, 389, 401, 419, 421,
    449, 499, 509, 521, 599, 619, 631, 641, 661, 691,
    709, 719, 751, 829, 839, 859, 881, 911, 929, 971,
    991, 1021, 1039, 1049, 1061, 1109, 1171, 1181, 1259, 1279,
    1291, 1301, 1321, 1409, 1439, 1489, 1499]

/-- `A267478` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 58) : A267478 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 58) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 58) : fz n = data[n.toNat - 1]! := sorry

end A267478
