import LOEIS.A234.A234146.Defs

set_option linter.unusedVariables false

/-!
# A234146

Number of (n+1) X (1+1) 0..5 arrays with every 2 X 2 subblock having the sum of the absolute values of the edge differences equal to 10 and no adjacent elements equal.

The 18 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A234146

/-- Known terms of `A234146`, starting at index `1`. -/
def data : List retType :=
  [184, 1264, 8752, 62004, 439572, 3129240, 22275612, 158687156, 1130414100, 8053620640,
    57377216736, 408788140012, 2912431493704, 20749855456308, 147833924812756, 1053254915776492, 7503999725717600, 53462860382183344]

/-- `A234146` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 19) : A234146 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 19) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 19) : fz n = data[n.toNat - 1]! := sorry

end A234146
