import LOEIS.A241.A241509.Defs

set_option linter.unusedVariables false

/-!
# A241509

Number of partitions of n such that (number parts having multiplicity 1) is not a part and (number of 1s) is not a part.

The 51 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A241509

/-- Known terms of `A241509`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 2, 2, 3, 2, 4, 5, 9, 10,
    16, 20, 27, 31, 48, 53, 72, 92, 118, 143,
    186, 220, 288, 356, 434, 523, 675, 792, 989, 1205,
    1469, 1754, 2165, 2565, 3133, 3752, 4498, 5345, 6496, 7629,
    9126, 10869, 12890, 15212, 18114, 21220, 25163, 29611, 34783, 40756,
    48058]

/-- `A241509` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 51) : A241509 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 51) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 51) : fz n = data[n.toNat]! := sorry

end A241509
