import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A060121

First solution mod p of x^3 = 2 for primes p such that only one solution exists.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A060121

/-- Index type of `A060121` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A060121`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A060121

/-- First solution mod p of x^3 = 2 for primes p such that only one solution exists. -/
def A060121 : A060121.argType → A060121.retType := sorry

namespace A060121

/-- Relation that defines `A060121`. -/
def prop : argType → retType → Prop := sorry

/-- `A060121` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A060121` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A060121 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A060121 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A060121 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A060121
