import LOEIS.A194.A194604.Defs

set_option linter.unusedVariables false

/-!
# A194604

Square table T(n, d) read by antidiagonals: number of ways to place 2 nonattacking kings on an n^d (n X n X ...) raumschach board (hypercubical chessboard).

The 50 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A194604

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [0, 0, 0, 1, 0, 0, 3, 16, 0, 0,
    6, 78, 193, 0, 0, 10, 228, 1548, 2080, 0,
    0, 15, 520, 6714, 27768, 21121, 0, 0, 21, 1020,
    21280, 181032, 474288, 206896, 0, 0, 28, 1806, 55395, 807040,
    4697166, 7888608, 1979713, 0, 0, 36, 2968, 125748, 2817240, 29708800]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 51) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 51) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 51) : flatFz n = flatData[n.toNat - 1]! := sorry

end A194604
