import LOEIS.A219.A219100.Defs

set_option linter.unusedVariables false

/-!
# A219100

Unmatched value maps: number of n X 2 binary arrays indicating the locations of corresponding elements not equal to any horizontal, vertical or antidiagonal neighbor in a random 0..2 n X 2 array.

The 24 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A219100

/-- Known terms of `A219100`, starting at index `1`. -/
def data : List retType :=
  [2, 11, 42, 154, 582, 2199, 8287, 31240, 117789, 444096,
    1674344, 6312696, 23800449, 89733625, 338318146, 1275543835, 4809118522, 18131576722, 68360568206, 257736398631,
    971730529991, 3663666552088, 13812937013629, 52078218972608]

/-- `A219100` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 25) : A219100 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 25) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 25) : fz n = data[n.toNat - 1]! := sorry

end A219100
