import LOEIS.A365.A365208.Defs

set_option linter.unusedVariables false

/-!
# A365208

The number of divisors d of n such that gcd(d, n/d) is a 3-smooth number (A003586).

The 86 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A365208

/-- Known terms of `A365208`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 2, 3, 2, 4, 2, 4, 3, 4,
    2, 6, 2, 4, 4, 5, 2, 6, 2, 6,
    4, 4, 2, 8, 2, 4, 4, 6, 2, 8,
    2, 6, 4, 4, 4, 9, 2, 4, 4, 8,
    2, 8, 2, 6, 6, 4, 2, 10, 2, 4,
    4, 6, 2, 8, 4, 8, 4, 4, 2, 12,
    2, 4, 6, 7, 4, 8, 2, 6, 4, 8,
    2, 12, 2, 4, 4, 6, 4, 8, 2, 10,
    5, 4, 2, 12, 4, 4]

/-- `A365208` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 87) : A365208 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 87) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 87) : fz n = data[n.toNat - 1]! := sorry

end A365208
