import LOEIS.A277.A277800.Defs

set_option linter.unusedVariables false

/-!
# A277800

Decimal representation of the x-axis, from the origin to the right edge, of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 1", based on the 5-celled von Neumann neighborhood.

The 34 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A277800

/-- Known terms of `A277800`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 4, 3, 16, 15, 64, 63, 256, 255,
    1024, 1023, 4096, 4095, 16384, 16383, 65536, 65535, 262144, 262143,
    1048576, 1048575, 4194304, 4194303, 16777216, 16777215, 67108864, 67108863, 268435456, 268435455,
    1073741824, 1073741823, 4294967296, 4294967295]

/-- `A277800` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 34) : A277800 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 34) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 34) : fz n = data[n.toNat]! := sorry

end A277800
