import LOEIS.A095.A095236.Defs

set_option linter.unusedVariables false

/-!
# A095236

Given a row of n payphones (or phone booths), all initially unused, sequence gives number of ways for n people to choose the payphones assuming each always chooses one of the most distant payphones from those in use already.

The 24 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A095236

/-- Known terms of `A095236`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 4, 8, 16, 36, 136, 216, 672, 2592,
    10656, 35904, 167808, 426240, 1866240, 15287040, 35573760, 147640320, 1323970560, 3104317440,
    64865525760, 352235520000, 1891946004480, 11505792614400]

/-- `A095236` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 25) : A095236 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 25) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 25) : fz n = data[n.toNat - 1]! := sorry

end A095236
