import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A165042

Length of cycle mentioned in A165041.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A165042

/-- Index type of `A165042` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A165042`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A165042

/-- Length of cycle mentioned in A165041. -/
def A165042 : A165042.argType → A165042.retType := sorry

namespace A165042

/-- Relation that defines `A165042`. -/
def prop : argType → retType → Prop := sorry

/-- `A165042` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A165042` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A165042 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A165042 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A165042 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A165042
