import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A095300

Numbers k such that A094758(k) < k.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A095300

/-- Index type of `A095300` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A095300`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A095300

/-- Numbers k such that A094758(k) < k. -/
def A095300 : A095300.argType → A095300.retType := sorry

namespace A095300

/-- Relation that defines `A095300`. -/
def prop : argType → retType → Prop := sorry

/-- `A095300` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A095300` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A095300 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A095300 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A095300 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A095300
