import LOEIS.A148.A148062.Defs

set_option linter.unusedVariables false

/-!
# A148062

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, -1), (-1, -1, 0), (-1, 1, -1), (0, 1, 1), (1, -1, -1)}.

The 32 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A148062

/-- Known terms of `A148062`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 3, 12, 25, 77, 181, 696, 1809,
    5991, 17609, 63958, 188683, 653258, 2112627, 7535840, 23721089, 85713509, 286499693,
    1026150382, 3374608955, 12502467560, 42456829669, 153777339420, 523923695731, 1958207627323, 6732073221545, 24744903814780, 86428974845565,
    323611236508025, 1126150114881781]

/-- `A148062` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 32) : A148062 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 32) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 32) : fz n = data[n.toNat]! := sorry

end A148062
