import LOEIS.A331.A331944.Defs

set_option linter.unusedVariables false

/-!
# A331944

a(n)/ceiling(6^(n-7)) is the expected number of rolls of a fair 6-sided die in a game where the player starts at 0, advances the position by the outcome of the die's roll until exactly position n is reached. Positions beyond n are avoided by staying at the last visited position, but counting the rolls.

The 27 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A331944

/-- Known terms of `A331944`, starting at index `1`. -/
def data : List retType :=
  [6, 6, 6, 6, 6, 6, 7, 43, 265, 1639,
    10177, 63463, 397585, 2456503, 15189313, 93961351, 581260273, 3594003799, 22197096865, 136829952295,
    843199062097, 5193720847351, 31972185139201, 196686016677319, 1209120275495089, 7428214177132183, 45613560985649761]

/-- `A331944` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 28) : A331944 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 28) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 28) : fz n = data[n.toNat - 1]! := sorry

end A331944
