import LOEIS.A035.A035105.Defs

set_option linter.unusedVariables false

/-!
# A035105

a(n) = LCM of Fibonacci sequence {F_1,...,F_n}.

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A035105

/-- Known terms of `A035105`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 2, 6, 30, 120, 1560, 10920, 185640, 2042040,
    181741560, 1090449360, 254074700880, 7368166325520, 449458145856720, 21124532855265840, 33735878969859546480, 640981700427331383120, 2679944489486672512824720, 109877724068953573025813520]

/-- `A035105` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 21) : A035105 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : fz n = data[n.toNat - 1]! := sorry

end A035105
