import LOEIS.A004.A004211.Defs

set_option linter.unusedVariables false

/-!
# A004211

Shifts one place left under 2nd-order binomial transform.

The 23 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A004211

/-- Known terms of `A004211`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 11, 49, 257, 1539, 10299, 75905, 609441,
    5284451, 49134923, 487026929, 5120905441, 56878092067, 664920021819, 8155340557697, 104652541401025, 1401572711758403, 19546873773314571,
    283314887789276721, 4259997696504874817, 66341623494636864963]

/-- `A004211` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 23) : A004211 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 23) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 23) : fz n = data[n.toNat]! := sorry

end A004211
