import LOEIS.A312.A312586.Defs

set_option linter.unusedVariables false

/-!
# A312586

Coordination sequence Gal.5.75.2 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A312586

/-- Known terms of `A312586`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 8, 14, 19, 21, 28, 34, 37, 42,
    46, 52, 57, 62, 63, 70, 77, 78, 85, 87,
    95, 101, 103, 105, 114, 119, 119, 128, 128, 138,
    144, 145, 146, 158, 163, 159, 171, 169, 181, 187,
    186, 188, 201, 207, 201, 213, 210, 224, 230, 227]

/-- `A312586` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A312586 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A312586
