import LOEIS.A285.A285886.Defs

set_option linter.unusedVariables false

/-!
# A285886

Primes of the form (1 + x)^y + (-x)^y where x is a divisor of y.

The 22 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A285886

/-- Known terms of `A285886`, starting at index `1`. -/
def data : List retType :=
  [5, 7, 13, 17, 31, 37, 97, 127, 257, 881,
    4651, 8191, 65537, 131071, 524287, 1273609, 2147483647, 2305843009213693951, 618970019642690137449562111, 3512911982806776822251393039617,
    162259276829213363391578010288127, 170141183460469231731687303715884105727]

/-- `A285886` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 23) : A285886 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 23) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 23) : fz n = data[n.toNat - 1]! := sorry

end A285886
