import LOEIS.A310.A310569.Defs

set_option linter.unusedVariables false

/-!
# A310569

Coordination sequence Gal.4.81.1 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A310569

/-- Known terms of `A310569`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 12, 8, 12, 20, 28, 28, 20, 28,
    40, 52, 40, 40, 52, 56, 64, 64, 68, 68,
    60, 84, 88, 92, 72, 84, 112, 104, 96, 100,
    116, 128, 100, 120, 128, 140, 124, 128, 152, 144,
    136, 156, 164, 168, 132, 164, 188, 188, 156, 164]

/-- `A310569` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A310569 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A310569
