import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A051018

Numbers that are 2-persistent but not 3-persistent.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A051018

/-- Index type of `A051018` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A051018`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A051018

/-- Numbers that are 2-persistent but not 3-persistent. -/
def A051018 : A051018.argType → A051018.retType := sorry

namespace A051018

/-- Relation that defines `A051018`. -/
def prop : argType → retType → Prop := sorry

/-- `A051018` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A051018` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A051018 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A051018 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A051018 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A051018
