import LOEIS.A049.A049494.Defs

set_option linter.unusedVariables false

/-!
# A049494

a(n) and a(n)+4^k are primes at least for k=1,2,3,4.

The 36 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A049494

/-- Known terms of `A049494`, starting at index `1`. -/
def data : List retType :=
  [7, 37, 163, 757, 967, 1303, 2293, 2377, 8677, 8803,
    9157, 9277, 14827, 15667, 16417, 20113, 27763, 29863, 41953, 53593,
    56527, 56893, 61027, 67153, 69763, 74827, 79333, 83203, 90007, 95467,
    111577, 129277, 135193, 137383, 142543, 151783]

/-- `A049494` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 37) : A049494 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 37) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 37) : fz n = data[n.toNat - 1]! := sorry

end A049494
