import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A163777

Even terms in the sequence of Queneau numbers A054639.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A163777

/-- Index type of `A163777` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A163777`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A163777

/-- Even terms in the sequence of Queneau numbers A054639. -/
def A163777 : A163777.argType → A163777.retType := sorry

namespace A163777

/-- Relation that defines `A163777`. -/
def prop : argType → retType → Prop := sorry

/-- `A163777` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A163777` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A163777 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A163777 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A163777 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A163777
