import LOEIS.A258.A258980.Defs

set_option linter.unusedVariables false

/-!
# A258980

Primes in A258978.

The 27 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A258980

/-- Known terms of `A258980`, starting at index `1`. -/
def data : List retType :=
  [5, 2801, 22621, 30941, 22621, 637421, 346201, 346201, 346201, 2625641,
    837931, 16007041, 3835261, 209102521, 209102521, 15018571, 262209281, 21700501, 30397351, 209102521,
    209102521, 693025471, 147753211, 4244897281, 1740422941, 6903678241, 2439903211]

/-- `A258980` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 28) : A258980 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 28) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 28) : fz n = data[n.toNat - 1]! := sorry

end A258980
