import LOEIS.A311.A311934.Defs

set_option linter.unusedVariables false

/-!
# A311934

Coordination sequence Gal.6.186.2 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A311934

/-- Known terms of `A311934`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 8, 13, 17, 22, 26, 31, 35, 40,
    46, 49, 55, 56, 63, 65, 69, 76, 75, 87,
    86, 93, 101, 101, 111, 108, 118, 117, 121, 131,
    123, 142, 139, 144, 157, 153, 166, 161, 173, 169,
    173, 186, 172, 196, 191, 197, 211, 206, 221, 213]

/-- `A311934` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A311934 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A311934
