import LOEIS.A223.A223128.Defs

set_option linter.unusedVariables false

/-!
# A223128

Number of 3Xn 0..2 arrays with no more than floor(3Xn/2) elements equal to at least one horizontal or antidiagonal neighbor, with new values introduced in row major 0..2 order.

The 16 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A223128

/-- Known terms of `A223128`, starting at index `1`. -/
def data : List retType :=
  [5, 72, 1154, 28907, 444555, 11814919, 186184618, 5048458186, 80664693231, 2214177564958,
    35719743830427, 988031616090509, 16048574199166554, 446266480581619794, 7286115298409479410, 203387498405308227681]

/-- `A223128` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A223128 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 17) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 17) : fz n = data[n.toNat - 1]! := sorry

end A223128
