import LOEIS.A314.A314859.Defs

set_option linter.unusedVariables false

/-!
# A314859

Coordination sequence Gal.6.554.3 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A314859

/-- Known terms of `A314859`, starting at index `0`. -/
def data : List retType :=
  [1, 5, 9, 14, 18, 25, 28, 31, 42, 39,
    49, 50, 58, 63, 60, 77, 72, 85, 81, 88,
    102, 93, 104, 109, 114, 121, 119, 126, 138, 137,
    136, 147, 158, 151, 159, 168, 170, 177, 176, 183,
    192, 199, 187, 206, 220, 201, 218, 225, 226, 235]

/-- `A314859` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A314859 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A314859
