import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A392003

a(n) = (7*2^n - 9 + 5*(-1)^n) / 6.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A392003

/-- Index type of `A392003` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A392003`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A392003

/-- a(n) = (7*2^n - 9 + 5*(-1)^n) / 6. -/
def A392003 : A392003.argType → A392003.retType := sorry

namespace A392003

/-- Relation that defines `A392003`. -/
def prop : argType → retType → Prop := sorry

/-- `A392003` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A392003` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A392003 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A392003 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A392003 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A392003
