import LOEIS.A233.A233100.Defs

set_option linter.unusedVariables false

/-!
# A233100

Number of 3 X n 0..3 arrays with no element x(i,j) adjacent to value 3-x(i,j) horizontally, diagonally or antidiagonally, top left element zero, and 1 appearing before 2 in row major order.

The 17 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A233100

/-- Known terms of `A233100`, starting at index `1`. -/
def data : List retType :=
  [10, 74, 941, 11486, 141566, 1742447, 21452183, 264098522, 3251348462, 40027693247,
    492785243519, 6066732018746, 74688189381254, 919494319284479, 11319993299254919, 139361653035025178, 1715696275016282462]

/-- `A233100` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 18) : A233100 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 18) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 18) : fz n = data[n.toNat - 1]! := sorry

end A233100
