import LOEIS.A247.A247512.Defs

set_option linter.unusedVariables false

/-!
# A247512

The curvature (rounded down) of touching circles inscribed in a special way in the smaller segment of circle of radius 10/9 divided by a chord of length 4/3.

The 34 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A247512

/-- Known terms of `A247512`, starting at index `0`. -/
def data : List retType :=
  [9, 10, 13, 20, 35, 64, 119, 224, 428, 821,
    1576, 3030, 5828, 11215, 21584, 41545, 79968, 153931, 296306, 570371,
    1097933, 2113463, 4068308, 7831289, 15074840, 29018319, 55858826, 107525476, 206981225, 398428629,
    766955420, 1476351286, 2841903278, 5470523390]

/-- `A247512` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 34) : A247512 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 34) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 34) : fz n = data[n.toNat]! := sorry

end A247512
