import LOEIS.A152.A152516.Defs

set_option linter.unusedVariables false

/-!
# A152516

1/21 of the number of permutations of 6 indistinguishable copies of 1..n with exactly 5 local maxima.

The 12 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A152516

/-- Known terms of `A152516`, starting at index `1`. -/
def data : List retType :=
  [0, 5, 285365, 3328373375, 23122804891093, 132106319858700205, 697701196338306192217, 3568377130807709398000279, 18013809185839252548978200161, 90462608845509339028810174966669,
    453352973288072573009512458761236141, 2270154484704085339079608424120307696559]

/-- `A152516` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 13) : A152516 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 13) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 13) : fz n = data[n.toNat - 1]! := sorry

end A152516
