import LOEIS.A337.A337014.Defs

set_option linter.unusedVariables false

/-!
# A337014

a(1) = 0 and for n > 1, a(n+1) = (k(n) - a(n))*(-1)^(n+1) where k(n) is the number of terms equal to a(n) among the first n terms.

The 83 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A337014

/-- Known terms of `A337014`, starting at index `1`. -/
def data : List retType :=
  [0, 1, 0, 2, 1, 1, -2, 3, 2, 0,
    -3, 4, 3, -1, -2, 4, 2, 1, -3, 5,
    4, -1, -3, 6, 5, -3, -7, 8, 7, -6,
    -7, 9, 8, -6, -8, 9, 7, -5, -6, 9,
    6, -4, -5, 7, 4, 0, -4, 6, 3, 0,
    -5, 8, 5, -2, -5, 9, 5, -1, -4, 7,
    3, 1, -4, 8, 4, 1, -5, 10, 9, -4,
    -9, 10, 8, -3, -8, 10, 7, -2, -6, 10,
    6, -2, -7]

/-- `A337014` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 84) : A337014 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 84) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 84) : fz n = data[n.toNat - 1]! := sorry

end A337014
