import LOEIS.A023.A023084.Defs

set_option linter.unusedVariables false

/-!
# A023084

Positive numbers k such that k and 7*k are anagrams in base 9 (written in base 9).

The 28 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A023084

/-- Known terms of `A023084`, starting at index `1`. -/
def data : List retType :=
  [10766, 12278, 100766, 101477, 101774, 102647, 103785, 105774, 107660, 108766,
    114783, 114787, 117874, 122780, 122788, 122878, 1000766, 1001477, 1001774, 1002647,
    1003785, 1005774, 1007660, 1008766, 1012673, 1012758, 1012785, 1014127]

/-- `A023084` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 29) : A023084 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 29) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 29) : fz n = data[n.toNat - 1]! := sorry

end A023084
