import LOEIS.A147.A147518.Defs

set_option linter.unusedVariables false

/-!
# A147518

Expansion of (1-x)/(1-4*x-6*x^2).

The 22 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A147518

/-- Known terms of `A147518`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 18, 90, 468, 2412, 12456, 64296, 331920, 1713456,
    8845344, 45662112, 235720512, 1216854720, 6281741952, 32428096128, 167402836224, 864179921664, 4461136704000, 23029626345984,
    118885325607936, 613719060507648]

/-- `A147518` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 22) : A147518 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 22) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 22) : fz n = data[n.toNat]! := sorry

end A147518
