import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A111011

Primes in A002533.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A111011

/-- Index type of `A111011` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A111011`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A111011

/-- Primes in A002533. -/
def A111011 : A111011.argType → A111011.retType := sorry

namespace A111011

/-- Relation that defines `A111011`. -/
def prop : argType → retType → Prop := sorry

/-- `A111011` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A111011` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A111011 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A111011 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A111011 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A111011
