import LOEIS.A186.A186762.Defs

set_option linter.unusedVariables false

/-!
# A186762

Number of permutations of {1,2,...,n} having no increasing odd cycles. A cycle (b(1), b(2), ...) is said to be increasing if, when written with its smallest element in the first position, it satisfies b(1)<b(2)<b(3)<... .  A cycle is said to be odd if it has an odd number of entries.

The 24 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A186762

/-- Known terms of `A186762`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 1, 1, 9, 33, 235, 1517, 12593, 111465,
    1122819, 12313409, 147949593, 1922353925, 26918452691, 403744456541, 6460109224801, 109820584161393, 1976779056442179, 37558742545087481,
    751175283283221129, 15774677696321630525, 347042934659313999539, 7981987292809647817237]

/-- `A186762` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 24) : A186762 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 24) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 24) : fz n = data[n.toNat]! := sorry

end A186762
