import LOEIS.A172.A172714.Defs

set_option linter.unusedVariables false

/-!
# A172714

Number of 7*n X 7 0..2 arrays with row sums 4 and column sums 4*n.

The 4 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A172714

/-- Known terms of `A172714`, starting at index `1`. -/
def data : List retType :=
  [344827336455, 134169254007831527780970675, 115401909362364329779895671658357933292000, 138888194169408560414765498059420203413991485926907191875]

/-- `A172714` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 5) : A172714 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 5) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 5) : fz n = data[n.toNat - 1]! := sorry

end A172714
