import LOEIS.A108.A108517.Defs

set_option linter.unusedVariables false

/-!
# A108517

Numbers m such that the permutation of the first m natural numbers R_m(n)=if(1<=n<m-pi(m), c(n), if(n=m, 1, prime(n-m-pi(m)+1))) is a cyclic permutation where c(k) is the k-th composite number(for each natural number k, c(k)=A002808(k)).

The 25 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A108517

/-- Known terms of `A108517`, starting at index `1`. -/
def data : List retType :=
  [1, 15, 33, 66, 85, 112, 125, 148, 213, 237,
    321, 381, 466, 518, 585, 637, 956, 2127, 2571, 4255,
    4884, 6686, 9193, 10412, 11073]

/-- `A108517` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 26) : A108517 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 26) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 26) : fz n = data[n.toNat - 1]! := sorry

end A108517
