import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A217586

a(1) = 1 and, for all n >= 1, if a(n) = 0 then a(2*n) = 1 and a(2*n+1) = 0 whereas if a(n) = 1 then a(2*n) = 0 and a(2*n+1) = 0.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A217586

/-- Index type of `A217586` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A217586`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A217586

/-- a(1) = 1 and, for all n >= 1, if a(n) = 0 then a(2*n) = 1 and a(2*n+1) = 0 whereas if a(n) = 1 then a(2*n) = 0 and a(2*n+1) = 0. -/
def A217586 : A217586.argType → A217586.retType := sorry

namespace A217586

/-- Relation that defines `A217586`. -/
def prop : argType → retType → Prop := sorry

/-- `A217586` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A217586` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A217586 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A217586 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A217586 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A217586
