import LOEIS.A062.A062771.Defs

set_option linter.unusedVariables false

/-!
# A062771

Order of automorphism group of the group C_n X C_2 (where C_n is the cyclic group with n elements).

The 69 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A062771

/-- Known terms of `A062771`, starting at index `1`. -/
def data : List retType :=
  [1, 6, 2, 8, 4, 12, 6, 16, 6, 24,
    10, 16, 12, 36, 8, 32, 16, 36, 18, 32,
    12, 60, 22, 32, 20, 72, 18, 48, 28, 48,
    30, 64, 20, 96, 24, 48, 36, 108, 24, 64,
    40, 72, 42, 80, 24, 132, 46, 64, 42, 120,
    32, 96, 52, 108, 40, 96, 36, 168, 58, 64,
    60, 180, 36, 128, 48, 120, 66, 128, 44]

/-- `A062771` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 70) : A062771 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 70) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 70) : fz n = data[n.toNat - 1]! := sorry

end A062771
