import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A106337

Number of ways of writing n as the sum of n triangular numbers.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A106337

/-- Index type of `A106337` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A106337`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A106337

/-- Number of ways of writing n as the sum of n triangular numbers. -/
def A106337 : A106337.argType → A106337.retType := sorry

namespace A106337

/-- Relation that defines `A106337`. -/
def prop : argType → retType → Prop := sorry

/-- `A106337` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A106337` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A106337 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A106337 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A106337 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A106337
