import LOEIS.A314.A314850.Defs

set_option linter.unusedVariables false

/-!
# A314850

Coordination sequence Gal.5.201.4 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A314850

/-- Known terms of `A314850`, starting at index `0`. -/
def data : List retType :=
  [1, 5, 9, 14, 18, 24, 29, 33, 38, 43,
    50, 54, 56, 62, 69, 73, 77, 81, 87, 93,
    95, 103, 107, 109, 116, 120, 130, 129, 130, 143,
    146, 153, 150, 156, 171, 167, 175, 176, 183, 193,
    187, 203, 203, 204, 214, 214, 232, 223, 224, 242]

/-- `A314850` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A314850 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A314850
