import LOEIS.A104.A104141.Defs

set_option linter.unusedVariables false

/-!
# A104141

Decimal expansion of 3/Pi^2.

The 100 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A104141

/-- Known terms of `A104141`, starting at index `0`. -/
def data : List retType :=
  [3, 0, 3, 9, 6, 3, 5, 5, 0, 9,
    2, 7, 0, 1, 3, 3, 1, 4, 3, 3,
    1, 6, 3, 8, 3, 8, 9, 6, 2, 9,
    1, 8, 2, 9, 1, 6, 7, 1, 3, 0,
    7, 6, 3, 2, 4, 0, 1, 6, 7, 3,
    9, 6, 4, 6, 5, 3, 6, 8, 2, 7,
    0, 9, 5, 6, 8, 2, 5, 1, 9, 3,
    6, 2, 8, 8, 6, 7, 0, 6, 3, 2,
    3, 5, 7, 3, 6, 2, 7, 8, 2, 1,
    7, 7, 6, 8, 6, 5, 5, 1, 2, 8]

/-- `A104141` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 100) : A104141 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 100) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 100) : fz n = data[n.toNat]! := sorry

end A104141
