import LOEIS.A271.A271849.Defs

set_option linter.unusedVariables false

/-!
# A271849

Number of ways to move elements of an nXnXn triangular array to themselves or a neighbor, with no 2-cycles and with no more than 5-1 elements moved to themselves.

The 10 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A271849

/-- Known terms of `A271849`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 22, 384, 15536, 1473994, 314196428, 149466458074, 157014841181820, 365217955668529232]

/-- `A271849` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 11) : A271849 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 11) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 11) : fz n = data[n.toNat - 1]! := sorry

end A271849
