import LOEIS.A099.A099503.Defs

set_option linter.unusedVariables false

/-!
# A099503

Expansion of 1/(1-4*x+x^3).

The 24 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A099503

/-- Known terms of `A099503`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 16, 63, 248, 976, 3841, 15116, 59488, 234111,
    921328, 3625824, 14269185, 56155412, 220995824, 869714111, 3422701032, 13469808304, 53009519105, 208615375388,
    820991693248, 3230957253887, 12715213640160, 50039862867392]

/-- `A099503` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 24) : A099503 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 24) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 24) : fz n = data[n.toNat]! := sorry

end A099503
