import LOEIS.A311.A311788.Defs

set_option linter.unusedVariables false

/-!
# A311788

Coordination sequence Gal.6.431.1 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A311788

/-- Known terms of `A311788`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 8, 13, 17, 21, 24, 29, 33, 39,
    45, 49, 54, 60, 59, 67, 65, 73, 75, 81,
    89, 92, 98, 106, 102, 114, 107, 119, 118, 123,
    133, 134, 140, 151, 144, 160, 150, 166, 162, 167,
    178, 176, 182, 195, 184, 205, 192, 212, 207, 212]

/-- `A311788` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A311788 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A311788
