import LOEIS.A178.A178754.Defs

set_option linter.unusedVariables false

/-!
# A178754

a(n) = n XOR floor(Log_2(n)), where XOR is bitwise XOR.

The 72 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A178754

/-- Known terms of `A178754`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 2, 6, 7, 4, 5, 11, 10, 9,
    8, 15, 14, 13, 12, 20, 21, 22, 23, 16,
    17, 18, 19, 28, 29, 30, 31, 24, 25, 26,
    27, 37, 36, 39, 38, 33, 32, 35, 34, 45,
    44, 47, 46, 41, 40, 43, 42, 53, 52, 55,
    54, 49, 48, 51, 50, 61, 60, 63, 62, 57,
    56, 59, 58, 70, 71, 68, 69, 66, 67, 64,
    65, 78]

/-- `A178754` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 73) : A178754 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 73) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 73) : fz n = data[n.toNat - 1]! := sorry

end A178754
