import LOEIS.A297.A297706.Defs

set_option linter.unusedVariables false

/-!
# A297706

Lexicographically earliest sequence of distinct positive terms such that for any n > 0, a(n) XOR a(n+1) XOR a(n+2) is prime (where XOR denotes the bitwise XOR operator).

The 67 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A297706

/-- Known terms of `A297706`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 4, 3, 5, 11, 9, 7, 12, 6,
    8, 13, 14, 16, 15, 18, 10, 19, 20, 22,
    17, 24, 26, 21, 28, 30, 29, 38, 36, 31,
    40, 32, 23, 42, 34, 25, 44, 48, 27, 41,
    33, 35, 39, 43, 37, 51, 45, 49, 53, 47,
    63, 57, 59, 55, 67, 61, 69, 77, 65, 75,
    73, 81, 87, 79, 91, 71, 83]

/-- `A297706` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 68) : A297706 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 68) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 68) : fz n = data[n.toNat - 1]! := sorry

end A297706
