import LOEIS.A355.A355146.Defs

set_option linter.unusedVariables false

/-!
# A355146

Triangle read by rows: T(n,k) is the number of subsets of {1,...,n} of cardinality k in which every pair of elements is coprime; n >= 0, 0 <= k <= A036234(n).

The 78 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A355146

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 2, 1, 1, 3, 3, 1,
    1, 4, 5, 2, 1, 5, 9, 7, 2, 1,
    6, 11, 8, 2, 1, 7, 17, 19, 10, 2,
    1, 8, 21, 25, 14, 3, 1, 9, 27, 37,
    24, 6, 1, 10, 31, 42, 26, 6, 1, 11,
    41, 73, 68, 32, 6, 1, 12, 45, 79, 72,
    33, 6, 1, 13, 57, 124, 151, 105, 39, 6,
    1, 14, 63, 138, 167, 114, 41, 6]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 78) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 78) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 78) : flatFz n = flatData[n.toNat]! := sorry

end A355146
