import LOEIS.A038.A038129.Defs

set_option linter.unusedVariables false

/-!
# A038129

Beatty sequence for cube root of 2.

The 72 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A038129

/-- Known terms of `A038129`, starting at index `0`. -/
def data : List retType :=
  [0, 1, 2, 3, 5, 6, 7, 8, 10, 11,
    12, 13, 15, 16, 17, 18, 20, 21, 22, 23,
    25, 26, 27, 28, 30, 31, 32, 34, 35, 36,
    37, 39, 40, 41, 42, 44, 45, 46, 47, 49,
    50, 51, 52, 54, 55, 56, 57, 59, 60, 61,
    62, 64, 65, 66, 68, 69, 70, 71, 73, 74,
    75, 76, 78, 79, 80, 81, 83, 84, 85, 86,
    88, 89]

/-- `A038129` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 72) : A038129 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 72) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 72) : fz n = data[n.toNat]! := sorry

end A038129
