import LOEIS.A119.A119389.Defs

set_option linter.unusedVariables false

/-!
# A119389

Numerator of (1^2/n + 2^2/(n-1) + ... + k^2/(n-k+1) + ... + (n-1)^2/2 + n^2/1).

The 25 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A119389

/-- Known terms of `A119389`, starting at index `1`. -/
def data : List retType :=
  [1, 9, 34, 265, 186, 1141, 2868, 31401, 18635, 477301,
    91192, 8051069, 4508441, 3336145, 22048024, 410111791, 223063947, 3057889621, 823596665, 706952715,
    125961187, 6173866701, 9838037952, 521135614075, 275363139571]

/-- `A119389` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 26) : A119389 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 26) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 26) : fz n = data[n.toNat - 1]! := sorry

end A119389
