import LOEIS.A168.A168328.Defs

set_option linter.unusedVariables false

/-!
# A168328

a(n) = 6 * floor( n/2 ).

The 61 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A168328

/-- Known terms of `A168328`, starting at index `1`. -/
def data : List retType :=
  [0, 6, 6, 12, 12, 18, 18, 24, 24, 30,
    30, 36, 36, 42, 42, 48, 48, 54, 54, 60,
    60, 66, 66, 72, 72, 78, 78, 84, 84, 90,
    90, 96, 96, 102, 102, 108, 108, 114, 114, 120,
    120, 126, 126, 132, 132, 138, 138, 144, 144, 150,
    150, 156, 156, 162, 162, 168, 168, 174, 174, 180,
    180]

/-- `A168328` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 62) : A168328 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 62) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 62) : fz n = data[n.toNat - 1]! := sorry

end A168328
