import LOEIS.A111.A111117.Defs

set_option linter.unusedVariables false

/-!
# A111117

Divisors of 10^15 - 1.

The 43 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A111117

/-- Known terms of `A111117`, starting at index `1`. -/
def data : List retType :=
  [1, 3, 9, 27, 31, 37, 41, 93, 111, 123,
    271, 279, 333, 369, 813, 837, 999, 1107, 1147, 1271,
    1517, 2439, 3441, 3813, 4551, 7317, 8401, 10027, 10323, 11111,
    11439, 13653, 25203, 30081, 30969, 33333, 34317, 40959, 47027, 75609,
    90243, 99999, 141081]

/-- `A111117` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 44) : A111117 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 44) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 44) : fz n = data[n.toNat - 1]! := sorry

end A111117
