import LOEIS.A101.A101181.Defs

set_option linter.unusedVariables false

/-!
# A101181

Least positive integer that can be represented as sum of a semiprime and a square in exactly n ways.

The 48 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A101181

/-- Known terms of `A101181`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 13, 10, 26, 50, 58, 74, 146, 159,
    218, 302, 290, 458, 515, 647, 650, 794, 962, 986,
    1178, 1403, 1322, 1418, 1658, 1898, 1802, 2126, 1970, 2210,
    3062, 2930, 3143, 3263, 3482, 3527, 4142, 4667, 4010, 4562,
    5123, 4955, 5018, 6242, 5330, 6695, 7178, 7103]

/-- `A101181` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 48) : A101181 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 48) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 48) : fz n = data[n.toNat]! := sorry

end A101181
