import LOEIS.A278.A278184.Defs

set_option linter.unusedVariables false

/-!
# A278184

Number of nX3 0..3 arrays with every element plus 1 mod 4 equal to some element at offset (-1,-1) (-1,0) (-1,1) (0,-1) (0,1) or (1,0), with upper left element zero.

The 16 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A278184

/-- Known terms of `A278184`, starting at index `1`. -/
def data : List retType :=
  [0, 19, 544, 13720, 347116, 8803344, 223230876, 5660949042, 143557203008, 3640498372990,
    92320193797850, 2341167983288042, 59370190792031534, 1505581649925192516, 38180374263992817136, 968224459304580152320]

/-- `A278184` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 17) : A278184 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 17) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 17) : fz n = data[n.toNat - 1]! := sorry

end A278184
