import LOEIS.A060.A060386.Defs

set_option linter.unusedVariables false

/-!
# A060386

In base ten, we try to get the digits 0,1,2,3,...,9,0,1,2,3,... in order only using primes and each time choosing the smallest prime that will give the desired digit.

The 61 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A060386

/-- Known terms of `A060386`, starting at index `0`. -/
def data : List retType :=
  [101, 11, 2, 3, 41, 5, 61, 7, 83, 19,
    101, 11, 2, 3, 41, 5, 61, 7, 83, 19,
    101, 11, 2, 3, 41, 5, 61, 7, 83, 19,
    101, 11, 2, 3, 41, 5, 61, 7, 83, 19,
    101, 11, 2, 3, 41, 5, 61, 7, 83, 19,
    101, 11, 2, 3, 41, 5, 61, 7, 83, 19,
    101]

/-- `A060386` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 61) : A060386 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 61) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 61) : fz n = data[n.toNat]! := sorry

end A060386
