import LOEIS.A377.A377633.Defs

set_option linter.unusedVariables false

/-!
# A377633

E.g.f. satisfies A(x) = (1 + x * A(x)^2 * exp(x*A(x)^2))^2.

The 18 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A377633

/-- Known terms of `A377633`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 22, 474, 15512, 685450, 38251212, 2582466950, 204744089104, 18650699228754,
    1919767092675860, 220378941471652942, 27916112634179586456, 3868191824049865945178, 582034397153512353488284, 94509039130326185624148150, 16472375319790734221438146592, 3067435511995844132675459958178]

/-- `A377633` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 18) : A377633 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 18) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 18) : fz n = data[n.toNat]! := sorry

end A377633
