import LOEIS.A310.A310078.Defs

set_option linter.unusedVariables false

/-!
# A310078

Coordination sequence Gal.6.39.2 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A310078

/-- Known terms of `A310078`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 6, 10, 15, 20, 24, 28, 31, 34,
    37, 40, 45, 51, 57, 62, 66, 70, 72, 76,
    80, 84, 90, 95, 99, 102, 105, 106, 111, 115,
    120, 127, 133, 136, 139, 143, 143, 148, 151, 157,
    164, 169, 171, 174, 178, 178, 184, 188, 194, 202]

/-- `A310078` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A310078 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A310078
