import LOEIS.A375.A375025.Defs

set_option linter.unusedVariables false

/-!
# A375025

Triangle read by rows: Matrix inverse of row-reversed A374439.

The 66 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A375025

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, -2, 1, 3, -2, 1, -4, 2, -2, 1,
    6, -2, 1, -2, 1, -10, 5, 0, 0, -2,
    1, 15, -10, 5, 2, -1, -2, 1, -20, 10,
    -12, 6, 4, -2, -2, 1, 30, -8, 4, -16,
    8, 6, -3, -2, 1, -52, 26, 8, -4, -22,
    11, 8, -4, -2, 1, 78, -60, 30, 30, -15,
    -30, 15, 10, -5, -2, 1]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 66) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 66) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 66) : flatFz n = flatData[n.toNat]! := sorry

end A375025
