import LOEIS.A045.A045549.Defs

set_option linter.unusedVariables false

/-!
# A045549

Numbers whose factorial has '6' as its final nonzero digit.

The 54 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A045549

/-- Known terms of `A045549`, starting at index `1`. -/
def data : List retType :=
  [3, 12, 17, 24, 29, 32, 45, 46, 48, 59,
    60, 61, 63, 65, 66, 68, 72, 79, 82, 95,
    96, 98, 104, 107, 120, 121, 123, 127, 130, 131,
    133, 139, 144, 159, 160, 161, 163, 165, 166, 168,
    172, 175, 176, 178, 187, 192, 199, 209, 210, 211,
    213, 215, 216, 218]

/-- `A045549` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 55) : A045549 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 55) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 55) : fz n = data[n.toNat - 1]! := sorry

end A045549
