import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A207975

Triangle where row n consists of a sequence of n positive integers g(1) < g(2) < ... < g(n) with the minimal sum such that A001222(g(i)+g(j)) = A001222(g(i)) + A001222(g(j)) for all 1 <= i < j <= n.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A207975

/-- Index type of `flat` (OEIS offset `1`). -/
abbrev flatArgType : Type := PNat

/-- Value type of `flat`. -/
abbrev flatRetType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev flatOffset : Int := 1

/-- Triangle where row n consists of a sequence of n positive integers g(1) < g(2) < ... < g(n) with the minimal sum such that A001222(g(i)+g(j)) = A001222(g(i)) + A001222(g(j)) for all 1 <= i < j <= n. -/
def flat : flatArgType → flatRetType := sorry

end A207975

namespace A207975

/-- Relation that defines `flat`. -/
def flatProp : flatArgType → flatRetType → Prop := sorry

/-- `flat` as a total function on `Nat`; junk value outside the domain. -/
def flatFn : Nat → flatRetType := sorry

/-- `flat` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def flatFz : Int → flatRetType := sorry

/-- The main definition satisfies its defining relation. -/
theorem flat_prop_correct (n : flatArgType) : flatProp n (flat n) := sorry

/-- `flatFn` agrees with the main definition. -/
theorem flat_fn_eq (n : Nat) (h : 0 < n) : flatFn n = flat ⟨n, h⟩ := sorry

/-- `flatFz` agrees with the main definition on the domain. -/
theorem flat_fz_eq (n : Int) (h : 1 ≤ n) : flatFz n = flat ⟨n.toNat, by omega⟩ := sorry

/-- `flatFn` and `flatFz` agree on the overlapping domain. -/
theorem flat_fn_eq_fz (n : Nat) (h : 0 < n) : flatFn n = flatFz (n : Int) := sorry

end A207975
