import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A363404

G.f. satisfies A(x) = exp( Sum_{k>=1} (A(x^k) + A(w*x^k) + A(w^2*x^k))/3 * x^k/k ), where w = exp(2*Pi*i/3).

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A363404

/-- Index type of `A363404` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A363404`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A363404

/-- G.f. satisfies A(x) = exp( Sum_{k>=1} (A(x^k) + A(w*x^k) + A(w^2*x^k))/3 * x^k/k ), where w = exp(2*Pi*i/3). -/
def A363404 : A363404.argType → A363404.retType := sorry

namespace A363404

/-- Relation that defines `A363404`. -/
def prop : argType → retType → Prop := sorry

/-- `A363404` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A363404` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A363404 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A363404 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A363404 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A363404
