import LOEIS.A298.A298489.Defs

set_option linter.unusedVariables false

/-!
# A298489

Number of nX3 0..1 arrays with every element equal to 0, 1, 2, 4 or 7 king-move adjacent elements, with upper left element zero.

The 35 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A298489

/-- Known terms of `A298489`, starting at index `1`. -/
def data : List retType :=
  [4, 13, 20, 27, 43, 70, 106, 169, 276, 444,
    720, 1183, 1947, 3207, 5311, 8826, 14681, 24474, 40897, 68419,
    114596, 192212, 322715, 542258, 911962, 1534860, 2584781, 4355511, 7343271, 12386305,
    20901774, 35285703, 59589460, 100666009, 170109263]

/-- `A298489` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 36) : A298489 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 36) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 36) : fz n = data[n.toNat - 1]! := sorry

end A298489
