import LOEIS.A152.A152929.Defs

set_option linter.unusedVariables false

/-!
# A152929

Number of sets (in the Hausdorff metric geometry) at each location between two sets defining a polygonal configuration consisting of two 4-gonal polygonal components chained with string components of length l as l varies.

The 34 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A152929

/-- Known terms of `A152929`, starting at index `1`. -/
def data : List retType :=
  [113, 176, 289, 465, 754, 1219, 1973, 3192, 5165, 8357,
    13522, 21879, 35401, 57280, 92681, 149961, 242642, 392603, 635245, 1027848,
    1663093, 2690941, 4354034, 7044975, 11399009, 18443984, 29842993, 48286977, 78129970, 126416947,
    204546917, 330963864, 535510781, 866474645]

/-- `A152929` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 35) : A152929 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 35) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 35) : fz n = data[n.toNat - 1]! := sorry

end A152929
