import LOEIS.A305.A305116.Defs

set_option linter.unusedVariables false

/-!
# A305116

O.g.f. A(x) satisfies: [x^n] exp( n^2 * x*A(x) ) * (n + 1 - A(x)) = 0 for n >= 0, where A(0) = 1.

The 17 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A305116

/-- Known terms of `A305116`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 20, 918, 80032, 12042925, 2930093028, 1091180685420, 593430683068672, 453081063936151719,
    469964400518950271900, 644367335619103754943450, 1141157288474505534959353440, 2559472926372019471694595185328, 7148083254588411836230809315647744, 24494543545202626717977721555958466300, 101668844348061438731562868186881235350528]

/-- `A305116` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 17) : A305116 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 17) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 17) : fz n = data[n.toNat]! := sorry

end A305116
