import LOEIS.A080.A080033.Defs

set_option linter.unusedVariables false

/-!
# A080033

a(n) is taken to be the smallest positive integer not already present which is consistent with the condition "n is a member of the sequence if and only if a(n) is a multiple of 4".

The 66 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A080033

/-- Known terms of `A080033`, starting at index `0`. -/
def data : List retType :=
  [0, 2, 4, 5, 8, 12, 7, 16, 20, 10,
    24, 13, 28, 32, 15, 36, 40, 18, 44, 21,
    48, 52, 23, 56, 60, 26, 64, 29, 68, 72,
    31, 76, 80, 34, 84, 37, 88, 92, 39, 96,
    100, 42, 104, 45, 108, 112, 47, 116, 120, 50,
    124, 53, 128, 132, 55, 136, 140, 58, 144, 61,
    148, 152, 63, 156, 160, 66]

/-- `A080033` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 66) : A080033 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 66) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 66) : fz n = data[n.toNat]! := sorry

end A080033
