import LOEIS.A258.A258193.Defs

set_option linter.unusedVariables false

/-!
# A258193

Define a<+>b = odd part(odd part(a) + odd part(b)), where odd part(n) = A000265(n); a(n) is the smallest prime of the form <+>_{0<=i<=k} binomial (n,i), or a(n)=0 if there is no such a prime (see comment).

The 64 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A258193

/-- Known terms of `A258193`, starting at index `1`. -/
def data : List retType :=
  [0, 0, 0, 0, 3, 3, 11, 0, 5, 3,
    3, 17, 7, 23, 53, 29, 13, 5, 5, 3,
    11, 3, 3, 823, 13, 7, 7, 457, 109, 109,
    233, 2267, 17, 59, 151, 5, 19, 5, 5, 3,
    113, 11, 11, 3, 23, 3, 3, 71, 43, 13,
    13, 7, 179, 7, 7, 193, 29, 2137, 863, 443,
    31, 5498157739, 977, 163]

/-- `A258193` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 65) : A258193 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 65) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 65) : fz n = data[n.toNat - 1]! := sorry

end A258193
