import LOEIS.A017.A017336.Defs

set_option linter.unusedVariables false

/-!
# A017336

a(n) = (10*n + 5)^8.

The 16 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A017336

/-- Known terms of `A017336`, starting at index `0`. -/
def data : List retType :=
  [390625, 2562890625, 152587890625, 2251875390625, 16815125390625, 83733937890625, 318644812890625, 1001129150390625, 2724905250390625, 6634204312890625,
    14774554437890625, 30590228625390625, 59604644775390625, 110324037687890625, 195408755062890625, 333160561500390625]

/-- `A017336` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 16) : A017336 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 16) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 16) : fz n = data[n.toNat]! := sorry

end A017336
