import LOEIS.A129.A129123.Defs

set_option linter.unusedVariables false

/-!
# A129123

Number of 4-tuples of standard tableau with height less than or equal to 2.

The 22 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A129123

/-- Known terms of `A129123`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 17, 98, 882, 7812, 78129, 815474, 8955650,
    101869508, 1194964498, 14374530436, 176681194276, 2212121332488, 28145258688369, 363177582488274, 4745064935840178, 62687665026816228, 836447728509168930,
    11261240896657686660, 152847558411986548260]

/-- `A129123` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 22) : A129123 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 22) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 22) : fz n = data[n.toNat]! := sorry

end A129123
