import LOEIS.A385.A385521.Defs

set_option linter.unusedVariables false

/-!
# A385521

Decimal expansion of a constant related to A375838.

The 105 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A385521

/-- Known terms of `A385521`, starting at index `1`. -/
def data : List retType :=
  [1, 5, 9, 5, 8, 5, 4, 3, 3, 0,
    5, 0, 0, 3, 6, 6, 2, 1, 2, 4,
    7, 0, 0, 6, 5, 6, 9, 7, 4, 0,
    0, 1, 6, 5, 1, 6, 9, 6, 4, 5,
    0, 2, 5, 0, 5, 8, 4, 8, 3, 2,
    4, 0, 6, 4, 2, 4, 7, 9, 4, 1,
    8, 9, 0, 9, 3, 4, 1, 1, 9, 1,
    0, 3, 8, 6, 1, 2, 7, 7, 4, 3,
    8, 1, 3, 9, 3, 5, 8, 2, 4, 0,
    2, 3, 5, 5, 5, 9, 9, 6, 5, 8,
    7, 7, 1, 8, 3]

/-- `A385521` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 106) : A385521 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 106) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 106) : fz n = data[n.toNat - 1]! := sorry

end A385521
