import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A388007

a(n) = Sum_{j=1..A066272(n)} (A066417(n) mod d_j), where d_j are the antidivisors of n.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A388007

/-- Index type of `A388007` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A388007`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A388007

/-- a(n) = Sum_{j=1..A066272(n)} (A066417(n) mod d_j), where d_j are the antidivisors of n. -/
def A388007 : A388007.argType → A388007.retType := sorry

namespace A388007

/-- Relation that defines `A388007`. -/
def prop : argType → retType → Prop := sorry

/-- `A388007` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A388007` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A388007 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A388007 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A388007 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A388007
