import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A347844

a(n) is the number of (strict) chains of subspaces with ends 0 and (F_7)^n.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A347844

/-- Index type of `A347844` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A347844`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A347844

/-- a(n) is the number of (strict) chains of subspaces with ends 0 and (F_7)^n. -/
def A347844 : A347844.argType → A347844.retType := sorry

namespace A347844

/-- Relation that defines `A347844`. -/
def prop : argType → retType → Prop := sorry

/-- `A347844` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A347844` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A347844 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A347844 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A347844 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A347844
