import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A199268

Decimal expansion of x > 0 satisfying 2*x^2 + x*cos(x) = 3.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A199268

/-- Index type of `A199268` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A199268`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A199268

/-- Decimal expansion of x > 0 satisfying 2*x^2 + x*cos(x) = 3. -/
def A199268 : A199268.argType → A199268.retType := sorry

namespace A199268

/-- Relation that defines `A199268`. -/
def prop : argType → retType → Prop := sorry

/-- `A199268` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A199268` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A199268 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A199268 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A199268 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A199268
