import LOEIS.A385.A385069.Defs

set_option linter.unusedVariables false

/-!
# A385069

G.f.: Sum_{k>=0} x^k * Product_{j=1..5*k} (1 + x^j).

The 52 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A385069

/-- Known terms of `A385069`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 3, 5, 7, 10, 13, 17, 22,
    28, 36, 45, 56, 69, 86, 106, 130, 159, 192,
    232, 279, 333, 397, 472, 557, 657, 773, 905, 1059,
    1236, 1437, 1669, 1935, 2236, 2582, 2976, 3422, 3930, 4507,
    5157, 5894, 6728, 7664, 8721, 9911, 11246, 12746, 14430, 16312,
    18421, 20780]

/-- `A385069` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 52) : A385069 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 52) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 52) : fz n = data[n.toNat]! := sorry

end A385069
