import LOEIS.A068.A068438.Defs

set_option linter.unusedVariables false

/-!
# A068438

Expansion of Pi in base 13.

The 92 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A068438

/-- Known terms of `A068438`, starting at index `1`. -/
def data : List retType :=
  [3, 1, 10, 12, 1, 0, 4, 9, 0, 5,
    2, 10, 2, 12, 7, 7, 3, 6, 9, 12,
    0, 11, 11, 8, 9, 12, 12, 9, 8, 8,
    3, 2, 7, 8, 2, 9, 8, 3, 5, 8,
    11, 3, 7, 0, 1, 6, 0, 3, 0, 6,
    1, 3, 3, 12, 10, 5, 10, 12, 11, 10,
    5, 7, 6, 1, 4, 11, 6, 5, 11, 4,
    1, 0, 0, 2, 0, 12, 2, 2, 11, 4,
    12, 7, 1, 4, 5, 7, 10, 9, 5, 5,
    10, 5]

/-- `A068438` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 93) : A068438 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 93) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 93) : fz n = data[n.toNat - 1]! := sorry

end A068438
