import LOEIS.A271.A271702.Defs

set_option linter.unusedVariables false

/-!
# A271702

Triangle read by rows, T(n,k) = Sum_{j=0..n} (-1)^(n-j)*C(-j-1,-n-1)*S2(k,j), S2 the Stirling set numbers A048993, for n>=0 and 0<=k<=n.

The 55 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A271702

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 2, 3, 1, 3, 6, 13,
    1, 4, 10, 26, 71, 1, 5, 15, 45, 140,
    456, 1, 6, 21, 71, 246, 887, 3337, 1, 7,
    28, 105, 399, 1568, 6405, 27203, 1, 8, 36, 148,
    610, 2584, 11334, 51564, 243203, 1, 9, 45, 201, 891,
    4035, 18849, 91101, 455712, 2357356]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 55) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 55) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 55) : flatFz n = flatData[n.toNat]! := sorry

end A271702
