import LOEIS.A079.A079751.Defs

set_option linter.unusedVariables false

/-!
# A079751

Operation count to create all permutations of n distinct elements using the "streamlined" version of Algorithm L (lexicographic permutation generation) from Knuth's The Art of Computer Programming, Vol. 4, chapter 7.2.1.2. Sequence gives number of cases where the j search loop runs beyond j=n-3.

The 21 terms known to OEIS, indexed from `3`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A079751

/-- Known terms of `A079751`, starting at index `3`. -/
def data : List retType :=
  [0, 1, 6, 37, 260, 2081, 18730, 187301, 2060312, 24723745,
    321408686, 4499721605, 67495824076, 1079933185217, 18358864148690, 330459554676421, 6278731538852000, 125574630777040001, 2637067246317840022, 58015479418992480485,
    1334356026636827051156]

/-- `A079751` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 24) : A079751 n = data[n.val - 3]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 3 ≤ n) (h : n < 24) : fn n = data[n - 3]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 3 ≤ n) (h : n < 24) : fz n = data[n.toNat - 3]! := sorry

end A079751
