import LOEIS.A201.A201357.Defs

set_option linter.unusedVariables false

/-!
# A201357

Numbers k such that (2^k + k + 1)*2^k - 1 is prime.

The 9 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A201357

/-- Known terms of `A201357`, starting at index `1`. -/
def data : List retType :=
  [1, 13, 1468, 2701, 2959, 3735, 8686, 11920, 89757]

/-- `A201357` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 10) : A201357 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 10) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 10) : fz n = data[n.toNat - 1]! := sorry

end A201357
