import LOEIS.A068.A068337.Defs

set_option linter.unusedVariables false

/-!
# A068337

a(n) = n!*Sum_{k=1..n} mu(k)/k, where mu(k) is the Möbius function.

The 22 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A068337

/-- Known terms of `A068337`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 1, 4, -4, 96, -48, -384, -3456, 328320,
    -17280, -207360, -481697280, -516741120, 79427174400, 1270834790400, 681401548800, 12265227878400, -6169334376038400, -123386687520768000,
    -158218429759488000, 47610136717000704000]

/-- `A068337` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 23) : A068337 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 23) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 23) : fz n = data[n.toNat - 1]! := sorry

end A068337
