import LOEIS.A208.A208880.Defs

set_option linter.unusedVariables false

/-!
# A208880

Number of words either empty or beginning with the first letter of the cyclic n-ary alphabet, where each letter of the alphabet occurs twice and letters of neighboring word positions are equal or neighbors in the alphabet.

The 36 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A208880

/-- Known terms of `A208880`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 30, 62, 114, 202, 346, 582, 966,
    1590, 2602, 4242, 6898, 11198, 18158, 29422, 47650, 77146, 124874,
    202102, 327062, 529254, 856410, 1385762, 2242274, 3628142, 5870526, 9498782, 15369426,
    24868330, 40237882, 65106342, 105344358, 170450838, 275795338]

/-- `A208880` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 36) : A208880 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 36) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 36) : fz n = data[n.toNat]! := sorry

end A208880
