import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A279625

Number of ternary palindromes of length 2n+1 having no (7/4)+ powers.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A279625

/-- Index type of `A279625` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A279625`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A279625

/-- Number of ternary palindromes of length 2n+1 having no (7/4)+ powers. -/
def A279625 : A279625.argType → A279625.retType := sorry

namespace A279625

/-- Relation that defines `A279625`. -/
def prop : argType → retType → Prop := sorry

/-- `A279625` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A279625` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A279625 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A279625 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A279625 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A279625
