import LOEIS.A147.A147301.Defs

set_option linter.unusedVariables false

/-!
# A147301

a(n) = smallest value of parameter m such that the function rad(m n (n - m)) has maximal value n=2,3,4..., 0 < m < n where the function rad(k) (also called radical(k)) is the product of distinct prime divisors of k.

The 76 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A147301

/-- Known terms of `A147301`, starting at index `2`. -/
def data : List retType :=
  [1, 1, 1, 2, 1, 2, 3, 2, 3, 5,
    5, 6, 3, 2, 5, 7, 7, 6, 7, 10,
    7, 10, 11, 11, 11, 13, 13, 14, 13, 14,
    15, 14, 15, 13, 17, 15, 17, 17, 19, 19,
    19, 21, 21, 22, 17, 21, 19, 23, 21, 22,
    23, 23, 23, 26, 23, 26, 23, 29, 29, 30,
    29, 29, 31, 31, 31, 33, 33, 34, 33, 34,
    35, 35, 35, 37, 37, 38]

/-- `A147301` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 78) : A147301 n = data[n.val - 2]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 78) : fn n = data[n - 2]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 78) : fz n = data[n.toNat - 2]! := sorry

end A147301
