import LOEIS.A023.A023998.Defs

set_option linter.unusedVariables false

/-!
# A023998

Number of block permutations on an n-set which are uniform, i.e., corresponding blocks have same size.

The 20 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A023998

/-- Known terms of `A023998`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 16, 131, 1496, 22482, 426833, 9934563, 277006192,
    9085194458, 345322038293, 15024619744202, 740552967629021, 40984758230303149, 2527342803112928081, 172490568947825135203, 12952575262915522547136, 1064521056888312620947794, 95305764621957309071404877]

/-- `A023998` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 20) : A023998 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 20) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 20) : fz n = data[n.toNat]! := sorry

end A023998
