import LOEIS.A307.A307744.Defs

set_option linter.unusedVariables false

/-!
# A307744

A fractal function, related to ruler functions and the Cantor set. a(1) = 0; for m >= 0, a(3m) = 1; for m >= 1, a(3m-1) = a(m-1) + sign(a(m-1)), a(3m+1) = a(m+1) + sign(a(m+1)).

The 85 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A307744

/-- Known terms of `A307744`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 2, 1, 3, 0, 1, 2, 3, 1,
    4, 2, 1, 0, 4, 1, 2, 0, 1, 3,
    2, 1, 4, 3, 1, 2, 4, 1, 5, 2,
    1, 3, 5, 1, 2, 3, 1, 0, 2, 1,
    5, 0, 1, 2, 5, 1, 3, 2, 1, 0,
    3, 1, 2, 0, 1, 4, 2, 1, 3, 4,
    1, 2, 3, 1, 5, 2, 1, 4, 5, 1,
    2, 4, 1, 3, 2, 1, 5, 3, 1, 2,
    5, 1, 6, 2, 1]

/-- `A307744` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 85) : A307744 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 85) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 85) : fz n = data[n.toNat]! := sorry

end A307744
