import LOEIS.A068.A068384.Defs

set_option linter.unusedVariables false

/-!
# A068384

a(n) is the smallest number m such that any lattice having at least m elements must have a sublattice with exactly n elements.

The 8 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A068384

/-- Known terms of `A068384`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 3, 4, 5, 6, 9, 8]

/-- `A068384` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 9) : A068384 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 9) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 9) : fz n = data[n.toNat - 1]! := sorry

end A068384
