import LOEIS.A128.A128285.Defs

set_option linter.unusedVariables false

/-!
# A128285

Numbers of the form m = p1 * p2 * p3 * p4 where for each d|m we have (d+m/d)/2 prime and p1 < p2 < p3 < p4 each prime.

The 32 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A128285

/-- Known terms of `A128285`, starting at index `1`. -/
def data : List retType :=
  [1365, 4305, 10465, 11685, 15873, 27105, 31845, 35245, 50065, 54033,
    58765, 74965, 84513, 91977, 95557, 95613, 96033, 104377, 113997, 114405,
    117957, 118105, 126357, 127605, 136437, 170905, 197985, 209605, 215373, 226185,
    248385, 277797]

/-- `A128285` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 33) : A128285 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 33) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 33) : fz n = data[n.toNat - 1]! := sorry

end A128285
