import LOEIS.A349.A349384.Defs

set_option linter.unusedVariables false

/-!
# A349384

Dirichlet convolution of A003961 with the Dirichlet inverse of A048673, where A003961 is fully multiplicative with a(p) = nextprime(p), and A048673(n) = (1+A003961(n))/2.

The 83 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A349384

/-- Known terms of `A349384`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 2, 2, 3, 0, 5, 4, 6, 0,
    6, -2, 8, 0, 0, 8, 9, -4, 11, -3,
    0, 0, 14, -8, 12, 0, 18, -5, 15, -12,
    18, 16, 0, 0, 0, -14, 20, 0, 0, -12,
    21, -20, 23, -6, -12, 0, 26, -24, 30, -9,
    0, -8, 29, -24, 0, -20, 0, 0, 30, -24,
    33, 0, -20, 32, 0, -24, 35, -9, 0, -30,
    36, -36, 39, 0, -18, -11, 0, -32, 41, -36,
    54, 0, 44]

/-- `A349384` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 84) : A349384 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 84) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 84) : fz n = data[n.toNat - 1]! := sorry

end A349384
