import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A379346

Number of integers of the form k^2 + 1 whose greatest prime factor is A002313(n), the n-th prime not congruent to 3 mod 4.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A379346

/-- Index type of `A379346` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A379346`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A379346

/-- Number of integers of the form k^2 + 1 whose greatest prime factor is A002313(n), the n-th prime not congruent to 3 mod 4. -/
def A379346 : A379346.argType → A379346.retType := sorry

namespace A379346

/-- Relation that defines `A379346`. -/
def prop : argType → retType → Prop := sorry

/-- `A379346` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A379346` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A379346 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A379346 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A379346 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A379346
