import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A203246

Second elementary symmetric function of the first n terms of (1,1,2,2,3,3,4,4,...).

OEIS offset `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A203246

/-- Index type of `A203246` (OEIS offset `2`). -/
abbrev argType : Type := {n : Nat // 2 ≤ n}

/-- Value type of `A203246`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 2

end A203246

/-- Second elementary symmetric function of the first n terms of (1,1,2,2,3,3,4,4,...). -/
def A203246 : A203246.argType → A203246.retType := sorry

namespace A203246

/-- Relation that defines `A203246`. -/
def prop : argType → retType → Prop := sorry

/-- `A203246` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A203246` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A203246 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 2 ≤ n) : fn n = A203246 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 2 ≤ n) : fz n = A203246 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 2 ≤ n) : fn n = fz (n : Int) := sorry

end A203246
