import LOEIS.A380.A380104.Defs

set_option linter.unusedVariables false

/-!
# A380104

Minimal conductors c of complex dihedral normal closures K = L(zeta_3) of pure cubic number fields L = Q(d^1/3), d > 1 cubefree, with elementary bicyclic 3-class group Cl_3(K)=(3,3) and second 3-class group M=Gal(F_3^2(K)/K) of assigned coclass cc(M)=0,1,2,3,...

The 4 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A380104

/-- Known terms of `A380104`, starting at index `1`. -/
def data : List retType :=
  [30, 90, 418, 1626]

/-- `A380104` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 5) : A380104 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 5) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 5) : fz n = data[n.toNat - 1]! := sorry

end A380104
