import LOEIS.A030.A030879.Defs

set_option linter.unusedVariables false

/-!
# A030879

[ exp(13/18)*n! ].

The 20 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A030879

/-- Known terms of `A030879`, starting at index `1`. -/
def data : List retType :=
  [2, 4, 12, 49, 247, 1482, 10377, 83019, 747171, 7471712,
    82188838, 986266063, 12821458831, 179500423635, 2692506354539, 43080101672631, 732361728434739, 13182511111825302, 250467711124680749, 5009354222493614990]

/-- `A030879` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 21) : A030879 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 21) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 21) : fz n = data[n.toNat - 1]! := sorry

end A030879
