import LOEIS.A329.A329168.Defs

set_option linter.unusedVariables false

/-!
# A329168

Numbers m that divide 4^(m + 1) + 1.

The 25 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A329168

/-- Known terms of `A329168`, starting at index `1`. -/
def data : List retType :=
  [1, 17, 4097, 7361, 85073, 658529, 3999137, 72281281, 285143057, 628944689,
    854112113, 1423081169, 2561019281, 3111576929, 4298117633, 5921265041, 14224884929, 21336998129, 34317377233, 50723421713,
    63797137889, 144269032049, 163834314353, 187397322209, 212565453281]

/-- `A329168` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 26) : A329168 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 26) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 26) : fz n = data[n.toNat - 1]! := sorry

end A329168
