import LOEIS.A108.A108990.Defs

set_option linter.unusedVariables false

/-!
# A108990

Triangle, read by rows, where the g.f. of row n, R_n(x), is a polynomial of degree n that satisfies: [x^k] R_{n+1}(x) = [x^k] (1 + x*R_n(x))^(n+1) for k=0..n+1, with R_0(x) = 1.

The 51 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A108990

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 2, 3, 1, 3, 9, 22,
    1, 4, 18, 76, 287, 1, 5, 30, 180, 1025,
    5496, 1, 6, 45, 350, 2670, 19656, 139727, 1, 7,
    63, 602, 5761, 54096, 495964, 4447234, 1, 8, 84, 952,
    10962, 125328, 1411228, 15629720, 170501039, 1, 9, 108, 1416, 19062,
    257040]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 51) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 51) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 51) : flatFz n = flatData[n.toNat]! := sorry

end A108990
