import LOEIS.A260.A260059.Defs

set_option linter.unusedVariables false

/-!
# A260059

Infinite square array whose n-th row lists the numbers k for which A086793(k)=n, where A086793 = number of iteration of A034690 (sum of digits of divisors) to reach a fixed point, read by antidiagonals.

The 79 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A260059

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [8, 14, 7, 20, 21, 4, 26, 39, 35, 3,
    59, 43, 44, 54, 2, 62, 52, 48, 56, 11,
    19, 122, 57, 49, 128, 101, 37, 12, 123, 61,
    50, 171, 136, 73, 64, 6, 143, 67, 65, 182,
    138, 109, 108, 29, 5, 149, 84, 99, 188, 160,
    127, 301, 33, 23, 13, 167, 93, 104, 216, 184,
    163, 553, 47, 24, 31, 9, 206, 112, 105, 248,
    190, 181, 589, 83, 28, 38, 25, 10, 239]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 80) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 80) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 80) : flatFz n = flatData[n.toNat - 1]! := sorry

end A260059
