import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A344787

a(n) = n * Sum_{d|n} sigma_d(d) / d, where sigma_k(n) is the sum of the k-th powers of the divisors of n.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A344787

/-- Index type of `A344787` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A344787`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A344787

/-- a(n) = n * Sum_{d|n} sigma_d(d) / d, where sigma_k(n) is the sum of the k-th powers of the divisors of n. -/
def A344787 : A344787.argType → A344787.retType := sorry

namespace A344787

/-- Relation that defines `A344787`. -/
def prop : argType → retType → Prop := sorry

/-- `A344787` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A344787` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A344787 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A344787 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A344787 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A344787
