import LOEIS.A338.A338969.Defs

set_option linter.unusedVariables false

/-!
# A338969

a(n) is the sum of the lengths of all the segments used to draw a rectangle of height partition(n) and width n divided into partition(n) rectangles of unit height, in turn, divided into rectangles of unit height and lengths corresponding to the parts of the partitions of n.

The 40 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A338969

/-- Known terms of `A338969`, starting at index `1`. -/
def data : List retType :=
  [4, 11, 21, 41, 67, 118, 181, 292, 437, 664,
    958, 1412, 1983, 2819, 3899, 5406, 7328, 9977, 13317, 17817,
    23497, 30967, 40349, 52573, 67784, 87320, 111601, 142395, 180432, 228317,
    287110, 360476, 450261, 561346, 696699, 863199, 1065055, 1311824, 1610026, 1972444]

/-- `A338969` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 41) : A338969 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 41) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 41) : fz n = data[n.toNat - 1]! := sorry

end A338969
