import LOEIS.A301.A301014.Defs

set_option linter.unusedVariables false

/-!
# A301014

Coordination sequence T8 for Zeolite Code EON.

The 47 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A301014

/-- Known terms of `A301014`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 10, 21, 37, 55, 76, 103, 149, 191,
    218, 266, 326, 374, 433, 520, 603, 653, 716, 809,
    910, 1002, 1091, 1215, 1320, 1400, 1520, 1673, 1824, 1932,
    2039, 2200, 2362, 2482, 2631, 2831, 3006, 3131, 3291, 3511,
    3696, 3864, 4057, 4256, 4449, 4633, 4832]

/-- `A301014` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 47) : A301014 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 47) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 47) : fz n = data[n.toNat]! := sorry

end A301014
