import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A177950

Numbers k that divide the digit reversal of k^2.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A177950

/-- Index type of `A177950` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A177950`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A177950

/-- Numbers k that divide the digit reversal of k^2. -/
def A177950 : A177950.argType → A177950.retType := sorry

namespace A177950

/-- Relation that defines `A177950`. -/
def prop : argType → retType → Prop := sorry

/-- `A177950` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A177950` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A177950 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A177950 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A177950 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A177950
