import LOEIS.A336.A336485.Defs

set_option linter.unusedVariables false

/-!
# A336485

The least positive integer k for which there exist primes p, q, r such that phi(p*q*s^k) = phi(r*s^(2k+1)) and sigma(p*q*s^k) = sigma(r*s^(2k+1)), where s is the n-th prime.

The 31 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A336485

/-- Known terms of `A336485`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 1, 1, 17, 3, 29, 4, 4, 4,
    1, 5, 4, 1, 20, 32, 2, 38, 12, 29,
    9, 4, 26, 20, 8, 14, 2, 14, 8, 41,
    4]

/-- `A336485` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 32) : A336485 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 32) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 32) : fz n = data[n.toNat - 1]! := sorry

end A336485
