import LOEIS.A148.A148051.Defs

set_option linter.unusedVariables false

/-!
# A148051

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 0), (-1, -1, 1), (-1, 0, -1), (-1, 1, 0), (1, 0, 0)}.

The 33 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A148051

/-- Known terms of `A148051`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 3, 10, 20, 63, 133, 488, 1134,
    4159, 9977, 38619, 96551, 380001, 972913, 3913896, 10241310, 41846263, 111378893,
    461040755, 1244667953, 5208010325, 14229194099, 60121447699, 165980137990, 706675809803, 1968160352808, 8441479695283, 23696553049202,
    102251059507356, 289003009054919, 1253963610330642]

/-- `A148051` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 33) : A148051 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 33) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 33) : fz n = data[n.toNat]! := sorry

end A148051
