import LOEIS.A381.A381616.Defs

set_option linter.unusedVariables false

/-!
# A381616

a(n) is the smallest prime that starts the first occurrence of exactly n consecutive primes in A381019.

The 43 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A381616

/-- Known terms of `A381616`, starting at index `1`. -/
def data : List retType :=
  [7643, 31, 3517, 1049, 2, 41, 173, 401, 523, 113,
    337, 449, 6599, 251, 1993, 2543, 743, 593, 1481, 1301,
    1069, 2357, 17657, 4079, 2797, 8219, 64123, 81299, 19289, 40129,
    6709, 13999, 4271, 1669, 37579, 28793, 38039, 12413, 125711, 24907,
    3181, 41597, 27253]

/-- `A381616` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 44) : A381616 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 44) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 44) : fz n = data[n.toNat - 1]! := sorry

end A381616
