import LOEIS.A280.A280565.Defs

set_option linter.unusedVariables false

/-!
# A280565

Binary representation of the x-axis, from the left edge to the origin, of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 291", based on the 5-celled von Neumann neighborhood.

The 25 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A280565

/-- Known terms of `A280565`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 11, 1000, 1, 111101, 11, 11110000, 111, 1111110000,
    1, 111111101101, 10011, 11111111010000, 10101, 1111111101011111, 1100000, 111111111100001111, 1100000, 11111111111000001111,
    100000, 1111111111111110100111, 1100000, 111111111111111000000001, 11111101]

/-- `A280565` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 25) : A280565 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 25) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 25) : fz n = data[n.toNat]! := sorry

end A280565
