import LOEIS.A391.A391008.Defs

set_option linter.unusedVariables false

/-!
# A391008

Triangle read by rows: T(n, k) = [x^k] Sum_{j=0..n} FallingFactorial(n, j)*RisingFactorial(x, j).

The 45 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A391008

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 1, 4, 2, 1, 21, 24, 6,
    1, 208, 348, 168, 24, 1, 3745, 7520, 4980, 1320,
    120, 1, 106116, 237630, 189480, 68760, 11520, 720, 1, 4299589,
    10407432, 9412410, 4158840, 960120, 110880, 5040, 1, 234834496, 603905624, 599743536,
    304343760, 86392320, 13849920, 1169280, 40320]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 45) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 45) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 45) : flatFz n = flatData[n.toNat]! := sorry

end A391008
