import LOEIS.A274.A274320.Defs

set_option linter.unusedVariables false

/-!
# A274320

Least inverse of A073454: Smallest m such that m divided by the primes up to m have exactly n repeated residues.

The 61 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A274320

/-- Known terms of `A274320`, starting at index `1`. -/
def data : List retType :=
  [6, 15, 35, 95, 187, 259, 671, 903, 905, 1273,
    1967, 2938, 3161, 4382, 6004, 6005, 9718, 11049, 12371, 14194,
    16181, 17285, 20842, 27242, 27257, 31937, 35758, 35767, 50407, 54071,
    56345, 59917, 59923, 75898, 86833, 86839, 106999, 116651, 116653, 134027,
    134034, 134041, 156138, 171613, 173499, 188170, 194554, 194555, 228122, 253291,
    253327, 260374, 302371, 302395, 302396, 346837, 368983, 376262, 376267, 376268,
    376270]

/-- `A274320` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 62) : A274320 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 62) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 62) : fz n = data[n.toNat - 1]! := sorry

end A274320
