import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A235343

a(n) = |{0 < k < n: f(n,k) - 1, f(n,k) + 1 and q(f(n,k)) + 1 are all prime with f(n,k) = phi(k) + phi(n-k)/4}|, where phi(.) is Euler's totient function, and q(.) is the strict partition function (A000009).

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A235343

/-- Index type of `A235343` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A235343`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A235343

/-- a(n) = |{0 < k < n: f(n,k) - 1, f(n,k) + 1 and q(f(n,k)) + 1 are all prime with f(n,k) = phi(k) + phi(n-k)/4}|, where phi(.) is Euler's totient function, and q(.) is the strict partition function (A000009). -/
def A235343 : A235343.argType → A235343.retType := sorry

namespace A235343

/-- Relation that defines `A235343`. -/
def prop : argType → retType → Prop := sorry

/-- `A235343` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A235343` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A235343 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A235343 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A235343 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A235343
