import LOEIS.A186.A186902.Defs

set_option linter.unusedVariables false

/-!
# A186902

T(n,k)=Number of (n+1)X(k+1) binary arrays with every 2X2 subblock determinant equal to exactly one or two horizontal and vertical neighbor 2X2 subblock determinants.

The 43 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A186902

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [0, 30, 30, 76, 148, 76, 234, 140, 140, 234,
    632, 406, 444, 406, 632, 1832, 1246, 1692, 1692, 1246,
    1832, 5182, 3106, 3948, 5401, 3948, 3106, 5182, 14860, 7240,
    13894, 14437, 14437, 13894, 7240, 14860, 42346, 19040, 35270, 49303,
    39372, 49303, 35270]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 44) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 44) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 44) : flatFz n = flatData[n.toNat - 1]! := sorry

end A186902
