import LOEIS.A148.A148657.Defs

set_option linter.unusedVariables false

/-!
# A148657

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, -1), (-1, -1, 1), (-1, 0, 1), (1, -1, -1), (1, 1, 0)}.

The 29 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A148657

/-- Known terms of `A148657`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 3, 6, 25, 65, 254, 789, 3276, 10614,
    44813, 155906, 661434, 2362970, 10220577, 37614941, 162469168, 612478229, 2669883881, 10204917780,
    44610693636, 173498753593, 760158224730, 2986524969699, 13137421409875, 52170082765338, 229643658222326, 920137704825030, 4060516913281992]

/-- `A148657` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 29) : A148657 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 29) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 29) : fz n = data[n.toNat]! := sorry

end A148657
