import LOEIS.A328.A328524.Defs

set_option linter.unusedVariables false

/-!
# A328524

T(n,k) is the k-th smallest least integer of prime signatures for partitions of n into distinct parts; triangle T(n,k), n>=0, 1<=k<=A000009(n), read by rows.

The 49 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A328524

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 2, 4, 8, 12, 16, 24, 32, 48, 72,
    64, 96, 144, 360, 128, 192, 288, 432, 720, 256,
    384, 576, 864, 1440, 2160, 512, 768, 1152, 1728, 2592,
    2880, 4320, 10800, 1024, 1536, 2304, 3456, 5184, 5760, 8640,
    12960, 21600, 75600, 2048, 3072, 4608, 6912, 10368, 11520]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 49) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 49) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 49) : flatFz n = flatData[n.toNat]! := sorry

end A328524
