import LOEIS.A040.A040846.Defs

set_option linter.unusedVariables false

/-!
# A040846

Continued fraction for sqrt(876).

The 84 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A040846

/-- Known terms of `A040846`, starting at index `0`. -/
def data : List retType :=
  [29, 1, 1, 2, 14, 2, 1, 1, 58, 1,
    1, 2, 14, 2, 1, 1, 58, 1, 1, 2,
    14, 2, 1, 1, 58, 1, 1, 2, 14, 2,
    1, 1, 58, 1, 1, 2, 14, 2, 1, 1,
    58, 1, 1, 2, 14, 2, 1, 1, 58, 1,
    1, 2, 14, 2, 1, 1, 58, 1, 1, 2,
    14, 2, 1, 1, 58, 1, 1, 2, 14, 2,
    1, 1, 58, 1, 1, 2, 14, 2, 1, 1,
    58, 1, 1, 2]

/-- `A040846` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 84) : A040846 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 84) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 84) : fz n = data[n.toNat]! := sorry

end A040846
