import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A173830

Primes of the form p - floor(sqrt(p)), p prime.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A173830

/-- Index type of `A173830` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A173830`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A173830

/-- Primes of the form p - floor(sqrt(p)), p prime. -/
def A173830 : A173830.argType → A173830.retType := sorry

namespace A173830

/-- Relation that defines `A173830`. -/
def prop : argType → retType → Prop := sorry

/-- `A173830` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A173830` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A173830 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A173830 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A173830 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A173830
