import LOEIS.A263.A263373.Defs

set_option linter.unusedVariables false

/-!
# A263373

T(n,k)=Number of (n+1)X(k+1) 0..2 arrays with each row and column divisible by 7, read as a base-3 number with top and left being the most significant digits.

The 48 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A263373

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 1, 1, 2, 2, 2, 5, 7, 7, 5,
    10, 29, 82, 29, 10, 19, 112, 865, 865, 112,
    19, 37, 367, 9888, 24711, 9888, 367, 37, 73, 1359,
    107514, 826249, 826249, 107514, 1359, 73, 146, 5370, 1260442, 27274339,
    84790557, 27274339, 1260442, 5370, 146, 293, 21447, 15048493]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 49) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 49) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 49) : flatFz n = flatData[n.toNat - 1]! := sorry

end A263373
