import LOEIS.A062.A062419.Defs

set_option linter.unusedVariables false

/-!
# A062419

Integer part of log(n)^log(n).

The 63 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A062419

/-- Known terms of `A062419`, starting at index `1`. -/
def data : List retType :=
  [1, 0, 1, 1, 2, 2, 3, 4, 5, 6,
    8, 9, 11, 12, 14, 16, 19, 21, 24, 26,
    29, 32, 35, 39, 43, 46, 50, 55, 59, 64,
    69, 74, 79, 85, 90, 96, 103, 109, 116, 123,
    130, 138, 145, 153, 162, 170, 179, 188, 198, 207,
    217, 227, 238, 249, 260, 271, 283, 295, 308, 320,
    334, 347, 361]

/-- `A062419` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 64) : A062419 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 64) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 64) : fz n = data[n.toNat - 1]! := sorry

end A062419
