import LOEIS.A314.A314932.Defs

set_option linter.unusedVariables false

/-!
# A314932

Coordination sequence Gal.6.558.3 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A314932

/-- Known terms of `A314932`, starting at index `0`. -/
def data : List retType :=
  [1, 5, 9, 14, 20, 22, 30, 35, 34, 47,
    47, 50, 61, 59, 66, 75, 77, 77, 89, 92,
    89, 109, 102, 103, 125, 115, 122, 136, 127, 137,
    150, 148, 146, 163, 164, 158, 186, 171, 170, 204,
    183, 193, 211, 196, 208, 225, 219, 214, 239, 234]

/-- `A314932` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A314932 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A314932
