import LOEIS.A026.A026407.Defs

set_option linter.unusedVariables false

/-!
# A026407

a(n) = greatest k such that s(j) > 0 for all j < k at end of stage n in forming A026409.

The 62 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A026407

/-- Known terms of `A026407`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 4, 6, 7, 10, 12, 15, 19, 23,
    28, 31, 36, 37, 45, 49, 58, 60, 67, 75,
    77, 90, 91, 104, 110, 111, 125, 135, 145, 158,
    160, 163, 186, 202, 203, 218, 219, 236, 254, 256,
    274, 283, 303, 322, 325, 353, 358, 359, 390, 405,
    407, 448, 450, 477, 492, 494, 498, 543, 544, 547,
    587, 589]

/-- `A026407` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 63) : A026407 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 63) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 63) : fz n = data[n.toNat - 1]! := sorry

end A026407
