import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A296737

Number of nX6 0..1 arrays with each 1 adjacent to 1, 2 or 4 king-move neighboring 1s.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A296737

/-- Index type of `A296737` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A296737`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A296737

/-- Number of nX6 0..1 arrays with each 1 adjacent to 1, 2 or 4 king-move neighboring 1s. -/
def A296737 : A296737.argType → A296737.retType := sorry

namespace A296737

/-- Relation that defines `A296737`. -/
def prop : argType → retType → Prop := sorry

/-- `A296737` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A296737` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A296737 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A296737 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A296737 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A296737
