import LOEIS.A167.A167340.Defs

set_option linter.unusedVariables false

/-!
# A167340

Totally multiplicative sequence with a(p) = p*(p+2) = p^2+2p for prime p.

The 46 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A167340

/-- Known terms of `A167340`, starting at index `1`. -/
def data : List retType :=
  [1, 8, 15, 64, 35, 120, 63, 512, 225, 280,
    143, 960, 195, 504, 525, 4096, 323, 1800, 399, 2240,
    945, 1144, 575, 7680, 1225, 1560, 3375, 4032, 899, 4200,
    1023, 32768, 2145, 2584, 2205, 14400, 1443, 3192, 2925, 17920,
    1763, 7560, 1935, 9152, 7875, 4600]

/-- `A167340` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 47) : A167340 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 47) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 47) : fz n = data[n.toNat - 1]! := sorry

end A167340
