import LOEIS.A390.A390272.Defs

set_option linter.unusedVariables false

/-!
# A390272

E.g.f. A(x) satisfies A(x) = exp( x / (1+x^3)^2 * A(x)^2 ).

The 19 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A390272

/-- Known terms of `A390272`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 5, 49, 681, 13441, 336013, 10181025, 362152913, 14800216897,
    683416124181, 35192610816529, 1999704346712185, 124289978967627201, 8388496934772060317, 610953501719493093121, 47762129258134699822497, 3989238163603650826552705, 354531079431585063672998437]

/-- `A390272` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 19) : A390272 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 19) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 19) : fz n = data[n.toNat]! := sorry

end A390272
