import LOEIS.A218.A218385.Defs

set_option linter.unusedVariables false

/-!
# A218385

(n-2)!/n when an integer.

The 18 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A218385

/-- Known terms of `A218385`, starting at index `1`. -/
def data : List retType :=
  [4, 90, 560, 4032, 302400, 34214400, 415134720, 5448643200, 1162377216000, 320118685286400,
    5792623828992000, 110586454917120000, 46833363657400320000, 1034080669555399065600, 23863400066663055360000, 574489260864110592000000, 14403266468807344128000000, 10162944820390462016716800000]

/-- `A218385` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 19) : A218385 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 19) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 19) : fz n = data[n.toNat - 1]! := sorry

end A218385
