import LOEIS.A224.A224511.Defs

set_option linter.unusedVariables false

/-!
# A224511

Roots of squares generated in A221643. That is, S = i^2 XOR (i+1)^2; increment i; if S is a square then square root of S is appended to a(n). Initially i=0. XOR is the binary logical exclusive-or operator.

The 66 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A224511

/-- Known terms of `A224511`, starting at index `1`. -/
def data : List retType :=
  [1, 5, 3, 9, 7, 13, 11, 21, 17, 15,
    43, 45, 29, 19, 41, 25, 23, 59, 39, 27,
    35, 33, 31, 85, 37, 61, 51, 53, 47, 81,
    79, 49, 55, 121, 83, 75, 57, 73, 77, 67,
    65, 63, 71, 69, 125, 89, 87, 123, 105, 107,
    95, 101, 163, 93, 91, 99, 97, 349, 243, 103,
    169, 109, 233, 115, 119, 171]

/-- `A224511` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 67) : A224511 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 67) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 67) : fz n = data[n.toNat - 1]! := sorry

end A224511
