import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A119845

Positions where new distinct values appear in A119842.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A119845

/-- Index type of `A119845` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A119845`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A119845

/-- Positions where new distinct values appear in A119842. -/
def A119845 : A119845.argType → A119845.retType := sorry

namespace A119845

/-- Relation that defines `A119845`. -/
def prop : argType → retType → Prop := sorry

/-- `A119845` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A119845` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A119845 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A119845 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A119845 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A119845
