import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A005916

Molien series for a certain group of order 52.

OEIS offset `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A005916

/-- Index type of `A005916` (OEIS offset `0`). -/
abbrev argType : Type := Nat

/-- Value type of `A005916`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 0

end A005916

/-- Molien series for a certain group of order 52. -/
def A005916 : A005916.argType → A005916.retType := sorry

namespace A005916

/-- Relation that defines `A005916`. -/
def prop : argType → retType → Prop := sorry

/-- `A005916` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A005916` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A005916 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) : fn n = A005916 n := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 0 ≤ n) : fz n = A005916 n.toNat := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) : fn n = fz (n : Int) := sorry

end A005916
