import LOEIS.A222.A222759.Defs

set_option linter.unusedVariables false

/-!
# A222759

Conjectured number of primes p for which binomial(n*p,p) (mod p^3) does not equal n.

The 87 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A222759

/-- Known terms of `A222759`, starting at index `1`. -/
def data : List retType :=
  [0, 2, 1, 0, 1, 1, 1, 2, 1, 1,
    2, 1, 1, 2, 1, 1, 2, 1, 1, 2,
    1, 1, 2, 1, 1, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 2, 2, 2, 2, 2]

/-- `A222759` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 88) : A222759 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 88) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 88) : fz n = data[n.toNat - 1]! := sorry

end A222759
