import LOEIS.A387.A387103.Defs

set_option linter.unusedVariables false

/-!
# A387103

For any n >= 2, a(n) is the number of positive values k < A386482(n-1) missing from the first n-1 terms of A386482 such that gcd(k, A386482(n-1)) != 1.

The 83 terms known to OEIS, indexed from `2`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A387103

/-- Known terms of `A387103`, starting at index `2`. -/
def data : List retType :=
  [0, 0, 0, 1, 0, 0, 2, 2, 0, 1,
    0, 2, 2, 0, 2, 1, 0, 0, 5, 3,
    3, 1, 1, 0, 1, 0, 2, 2, 0, 1,
    0, 6, 10, 8, 7, 6, 4, 2, 3, 1,
    0, 1, 1, 0, 2, 4, 2, 1, 0, 1,
    1, 0, 3, 3, 1, 1, 0, 8, 16, 11,
    9, 11, 7, 7, 6, 3, 3, 2, 1, 0,
    1, 1, 0, 0, 1, 0, 17, 31, 22, 20,
    28, 24, 16]

/-- `A387103` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 85) : A387103 n = data[n.val - 2]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 2 ≤ n) (h : n < 85) : fn n = data[n - 2]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 2 ≤ n) (h : n < 85) : fz n = data[n.toNat - 2]! := sorry

end A387103
