import LOEIS.A306.A306427.Defs

set_option linter.unusedVariables false

/-!
# A306427

Least integer m such that there are exactly n quadruples of distinct divisors (d_i, d_j, d_k, d_l) among the divisors of m having the property d_i * d_j - d_k * d_l = 1, for some i, j, k, l.

The 44 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A306427

/-- Known terms of `A306427`, starting at index `1`. -/
def data : List retType :=
  [28, 84, 120, 240, 360, 252, 210, 660, 1008, 1848,
    630, 1320, 420, 2310, 840, 4830, 1680, 3360, 5880, 11700,
    1980, 4200, 1260, 9660, 3960, 3780, 2520, 6930, 4620, 8190,
    6300, 7560, 5040, 18900, 19320, 5460, 23760, 7140, 39600, 15120,
    27300, 12600, 59220, 45360]

/-- `A306427` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 45) : A306427 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 45) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 45) : fz n = data[n.toNat - 1]! := sorry

end A306427
