import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A270884

Smallest of 4 consecutive prime numbers that when represented as a simple continued fraction, generates prime numbers in the numerator and denominator, when reduced.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A270884

/-- Index type of `A270884` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A270884`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A270884

/-- Smallest of 4 consecutive prime numbers that when represented as a simple continued fraction, generates prime numbers in the numerator and denominator, when reduced. -/
def A270884 : A270884.argType → A270884.retType := sorry

namespace A270884

/-- Relation that defines `A270884`. -/
def prop : argType → retType → Prop := sorry

/-- `A270884` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A270884` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A270884 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A270884 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A270884 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A270884
