import LOEIS.A346.A346724.Defs

set_option linter.unusedVariables false

/-!
# A346724

Use the cells of a hexagonal grid to represent the algebraic integers in the integer ring of Q(sqrt(-43)) as explained in the comments. Number the cells along the counterclockwise hexagonal spiral that starts with cells 0 and 1 representing integers 0 and 1. List the cells that represent 0 or a prime in the ring.

The 70 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A346724

/-- Known terms of `A346724`, starting at index `1`. -/
def data : List retType :=
  [0, 2, 3, 5, 6, 7, 8, 9, 11, 13,
    14, 15, 17, 19, 20, 21, 22, 23, 25, 26,
    28, 29, 30, 31, 32, 34, 35, 37, 39, 41,
    43, 45, 47, 49, 51, 53, 55, 57, 59, 61,
    62, 63, 64, 65, 66, 67, 68, 69, 71, 72,
    73, 74, 76, 77, 78, 79, 80, 81, 82, 83,
    84, 86, 87, 88, 89, 91, 95, 97, 101, 109]

/-- `A346724` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 71) : A346724 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 71) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 71) : fz n = data[n.toNat - 1]! := sorry

end A346724
