import LOEIS.A368.A368501.Defs

set_option linter.unusedVariables false

/-!
# A368501

Number of compositions (ordered partitions) of n into distinct parts not greater than n/2.

The 46 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A368501

/-- Known terms of `A368501`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 0, 0, 0, 0, 6, 0, 6, 6,
    36, 30, 66, 60, 120, 234, 318, 432, 666, 894,
    1272, 2226, 2772, 3960, 5496, 7524, 10068, 13776, 22488, 27756,
    39162, 51264, 70398, 91386, 124152, 158574, 247554, 301656, 416748, 537690,
    730854, 929196, 1248798, 1576014, 2078328, 2956110]

/-- `A368501` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 46) : A368501 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 46) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 46) : fz n = data[n.toNat]! := sorry

end A368501
