import LOEIS.A356.A356784.Defs

set_option linter.unusedVariables false

/-!
# A356784

Inventory of positions as an irregular table; row 0 contains 0, subsequent rows contain the 0-based positions of 0's, followed by the position of 1's, of 2's, etc. in prior rows flattened.

The 76 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A356784

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [0, 0, 0, 1, 0, 1, 2, 3, 0, 1,
    2, 4, 3, 5, 6, 7, 0, 1, 2, 4,
    8, 3, 5, 9, 6, 10, 7, 12, 11, 13,
    14, 15, 0, 1, 2, 4, 8, 16, 3, 5,
    9, 17, 6, 10, 18, 7, 12, 21, 11, 19,
    13, 22, 14, 24, 15, 26, 20, 23, 25, 28,
    27, 29, 30, 31, 0, 1, 2, 4, 8, 16,
    32, 3, 5, 9, 17, 33]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 76) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 76) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 76) : flatFz n = flatData[n.toNat]! := sorry

end A356784
