import LOEIS.A321.A321298.Defs

set_option linter.unusedVariables false

/-!
# A321298

Triangle read by rows: T(n,k) is the number of the k-th eliminated person in the Josephus elimination process for n people and a count of 2, 1 <= k <= n.

The 98 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A321298

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 2, 1, 2, 1, 3, 2, 4, 3, 1,
    2, 4, 1, 5, 3, 2, 4, 6, 3, 1,
    5, 2, 4, 6, 1, 5, 3, 7, 2, 4,
    6, 8, 3, 7, 5, 1, 2, 4, 6, 8,
    1, 5, 9, 7, 3, 2, 4, 6, 8, 10,
    3, 7, 1, 9, 5, 2, 4, 6, 8, 10,
    1, 5, 9, 3, 11, 7, 2, 4, 6, 8,
    10, 12, 3, 7, 11, 5, 1, 9, 2, 4,
    6, 8, 10, 12, 1, 5, 9, 13, 7, 3,
    11, 2, 4, 6, 8, 10, 12, 14]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 99) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 99) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 99) : flatFz n = flatData[n.toNat - 1]! := sorry

end A321298
