import LOEIS.A178.A178096.Defs

set_option linter.unusedVariables false

/-!
# A178096

Cube of n is equal to sum of four positive distinct squares; n^3=a^2+b^2+c^2+d^2; a>b>c>d>0.

The 48 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A178096

/-- Known terms of `A178096`, starting at index `1`. -/
def data : List retType :=
  [5, 6, 7, 9, 10, 11, 13, 14, 15, 17,
    18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
    28, 29, 30, 31, 33, 34, 35, 36, 37, 38,
    39, 40, 41, 42, 43, 44, 45, 46, 47, 49,
    50, 51, 52, 53, 54, 55, 56, 57]

/-- `A178096` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 49) : A178096 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 49) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 49) : fz n = data[n.toNat - 1]! := sorry

end A178096
