import LOEIS.A357.A357425.Defs

set_option linter.unusedVariables false

/-!
# A357425

Smallest number for which the sum of digits in fractional base 4/3 is n.

The 54 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A357425

/-- Known terms of `A357425`, starting at index `0`. -/
def data : List retType :=
  [0, 1, 2, 3, 5, 6, 7, 10, 11, 15,
    21, 22, 23, 31, 39, 43, 54, 55, 74, 75,
    101, 102, 103, 138, 139, 183, 187, 246, 247, 330,
    331, 439, 443, 587, 783, 790, 791, 1047, 1355, 1398,
    1399, 1866, 1867, 2487, 2491, 3318, 3319, 4199, 4427, 5903,
    5911, 7882, 7883, 9959]

/-- `A357425` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 54) : A357425 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 54) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 54) : fz n = data[n.toNat]! := sorry

end A357425
