import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A331013

Number of unlabeled bicolored bipartite graphs on 2n nodes having n nodes of each color with no edges between vertices of the same color and edges having two colors and allowing the node color classes to be interchanged. Edge colors are swappable (permuted by the symmetric group).

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A331013

/-- Index type of `A331013` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A331013`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A331013

/-- Number of unlabeled bicolored bipartite graphs on 2n nodes having n nodes of each color with no edges between vertices of the same color and edges having two colors and allowing the node color classes to be interchanged. Edge colors are swappable (permuted by the symmetric group). -/
def A331013 : A331013.argType → A331013.retType := sorry

namespace A331013

/-- Relation that defines `A331013`. -/
def prop : argType → retType → Prop := sorry

/-- `A331013` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A331013` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A331013 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A331013 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A331013 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A331013
