import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A343880

Positions of 0's in A342585.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A343880

/-- Index type of `A343880` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A343880`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A343880

/-- Positions of 0's in A342585. -/
def A343880 : A343880.argType → A343880.retType := sorry

namespace A343880

/-- Relation that defines `A343880`. -/
def prop : argType → retType → Prop := sorry

/-- `A343880` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A343880` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A343880 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A343880 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A343880 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A343880
