import LOEIS.A173.A173939.Defs

set_option linter.unusedVariables false

/-!
# A173939

The number of permutations avoiding simultaneously consecutive patterns 132 and 213.

The 25 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A173939

/-- Known terms of `A173939`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 4, 11, 37, 149, 705, 3814, 23199,
    156940, 1167862, 9478482, 83347221, 789272024, 8007691756, 86661018861, 996483990245, 12132147428205, 155914784843610,
    2109180000370399, 29959103479924280, 445807660125129870, 6935399147203692664, 112584529786912528601]

/-- `A173939` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 25) : A173939 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 25) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 25) : fz n = data[n.toNat]! := sorry

end A173939
