import LOEIS.A203.A203011.Defs

set_option linter.unusedVariables false

/-!
# A203011

(n-1)-st elementary symmetric function of {1,3,7,15,31,63,...-1+2^n}.

The 15 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A203011

/-- Known terms of `A203011`, starting at index `1`. -/
def data : List retType :=
  [1, 4, 31, 486, 15381, 978768, 124918731, 31932406170, 16337382642945, 16723323142761060,
    34243057328337866295, 140246638967945496322350, 1148847521944847479468879725, 18822284044001939139425413111800, 616761496621711735518439444437389475]

/-- `A203011` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 16) : A203011 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 16) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 16) : fz n = data[n.toNat - 1]! := sorry

end A203011
