import LOEIS.A210.A210097.Defs

set_option linter.unusedVariables false

/-!
# A210097

G.f.: 1 = Sum_{n>=0} a(n)*x^n*(1-x)^(n+1)/(1 + (n+1)*x)^(2*n+1).

The 18 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A210097

/-- Known terms of `A210097`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 14, 180, 3464, 90018, 2968968, 119252060, 5664108920, 311212995732,
    19447137310280, 1363465685120296, 106080538006819320, 9075286815352325570, 847179165282912257160, 85729124193701299050252, 9351018056855217246637304, 1094013446495887840421430300]

/-- `A210097` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 18) : A210097 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 18) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 18) : fz n = data[n.toNat]! := sorry

end A210097
