import LOEIS.A314.A314203.Defs

set_option linter.unusedVariables false

/-!
# A314203

Coordination sequence Gal.5.88.5 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A314203

/-- Known terms of `A314203`, starting at index `0`. -/
def data : List retType :=
  [1, 5, 11, 17, 22, 26, 30, 35, 41, 47,
    52, 57, 63, 69, 74, 78, 82, 87, 93, 99,
    104, 109, 115, 121, 126, 130, 134, 139, 145, 151,
    156, 161, 167, 173, 178, 182, 186, 191, 197, 203,
    208, 213, 219, 225, 230, 234, 238, 243, 249, 255]

/-- `A314203` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A314203 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A314203
