import LOEIS.A347.A347263.Defs

set_option linter.unusedVariables false

/-!
# A347263

Irregular triangle read by rows: T(n,k) is the sum of the subparts of the ziggurat diagram of n (described in A347186) that arise from the (2*k-1)-th double-staircase of the double-staircases diagram of n (described in A335616), n >= 1, k >= 1, and the first element of column k is in row A000384(k).

The 78 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A347263

/-- Known terms of `flat`, starting at index `1`. -/
def flatData : List flatRetType :=
  [1, 4, 6, 16, 12, 36, 1, 20, 0, 64,
    0, 30, 6, 90, 0, 42, 0, 144, 17, 56,
    0, 156, 0, 72, 34, 1, 256, 0, 0, 90,
    0, 0, 324, 10, 0, 110, 0, 0, 400, 0,
    8, 132, 70, 0, 342, 0, 0, 156, 0, 0,
    576, 121, 0, 182, 0, 25, 462, 0, 0, 210,
    102, 0, 784, 0, 0, 1, 240, 0, 0, 0,
    900, 24, 52, 0, 272, 0, 0, 0]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n.val < 79) : flat n = flatData[n.val - 1]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 79) : flatFn n = flatData[n - 1]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 79) : flatFz n = flatData[n.toNat - 1]! := sorry

end A347263
