import LOEIS.A282.A282147.Defs

set_option linter.unusedVariables false

/-!
# A282147

Numbers n with k digits in base x (MSD(n)=d_k, LSD(n)=d_1) such that, chosen one of their digits in position d_k < j < d_1, is Sum_{i=j..k}{(i-j+1)*d_i} = Sum_{i=1..j-1}{(j-i)*d_i}. Case x = 6.

The 56 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A282147

/-- Known terms of `A282147`, starting at index `1`. -/
def data : List retType :=
  [7, 14, 21, 28, 35, 38, 42, 45, 52, 59,
    73, 76, 83, 84, 115, 126, 146, 157, 168, 188,
    199, 210, 217, 219, 226, 228, 233, 252, 257, 259,
    270, 290, 301, 312, 332, 343, 354, 363, 374, 385,
    405, 416, 427, 434, 438, 445, 456, 476, 487, 498,
    504, 507, 518, 529, 549, 560]

/-- `A282147` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 57) : A282147 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 57) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 57) : fz n = data[n.toNat - 1]! := sorry

end A282147
