import LOEIS.A148.A148235.Defs

set_option linter.unusedVariables false

/-!
# A148235

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 1), (-1, 1, 1), (1, 0, -1), (1, 0, 0)}.

The 31 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A148235

/-- Known terms of `A148235`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 2, 4, 13, 35, 118, 341, 1222, 3871,
    14095, 46182, 172636, 588711, 2213167, 7681235, 29298637, 104046951, 397960363, 1428060581,
    5509869249, 20062858933, 77534482146, 284269944662, 1104891547397, 4091541637473, 15918933390799, 59235013814143, 231394948623317, 867248153419761,
    3390021144010261]

/-- `A148235` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 31) : A148235 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 31) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 31) : fz n = data[n.toNat]! := sorry

end A148235
