import LOEIS.A195.A195359.Defs

set_option linter.unusedVariables false

/-!
# A195359

Decimal expansion of shortest length, (A), of segment from side AB through incenter to side AC in right triangle ABC with sidelengths (a,b,c)=(2,5,sqrt(29)).

The 100 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A195359

/-- Known terms of `A195359`, starting at index `1`. -/
def data : List retType :=
  [1, 6, 4, 4, 5, 0, 8, 0, 6, 0,
    3, 2, 3, 0, 2, 4, 2, 4, 9, 0,
    0, 0, 2, 9, 9, 7, 3, 1, 4, 3,
    0, 5, 1, 3, 3, 1, 4, 8, 7, 5,
    9, 6, 6, 3, 2, 9, 1, 3, 1, 4,
    2, 8, 2, 3, 4, 6, 5, 7, 9, 9,
    0, 2, 4, 0, 2, 4, 4, 3, 1, 7,
    7, 8, 7, 2, 2, 0, 2, 2, 3, 8,
    3, 8, 8, 5, 5, 0, 3, 6, 2, 6,
    4, 9, 3, 8, 6, 0, 2, 8, 5, 1]

/-- `A195359` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 101) : A195359 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 101) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 101) : fz n = data[n.toNat - 1]! := sorry

end A195359
