import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A241953

Number of possible representations of n as a sum of distinct positive integers from the Fibonacci-type sequences  2,1,3,4,7,11,... and 0,3,3,6,9,15,... (A000032 and A022086).

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A241953

/-- Index type of `A241953` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A241953`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A241953

/-- Number of possible representations of n as a sum of distinct positive integers from the Fibonacci-type sequences  2,1,3,4,7,11,... and 0,3,3,6,9,15,... (A000032 and A022086). -/
def A241953 : A241953.argType → A241953.retType := sorry

namespace A241953

/-- Relation that defines `A241953`. -/
def prop : argType → retType → Prop := sorry

/-- `A241953` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A241953` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A241953 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A241953 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A241953 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A241953
