import LOEIS.A213.A213736.Defs

set_option linter.unusedVariables false

/-!
# A213736

Triangle read by rows, coefficients of the Swiss-Knife median polynomials M_{n}(x) in descending order of powers.

The 48 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A213736

/-- Known terms of `flat`, starting at index `0`. -/
def flatData : List flatRetType :=
  [1, 1, -1, -1, 1, -2, -5, 6, 4, 1,
    -3, -12, 29, 57, -72, -46, 1, -4, -22, 80,
    261, -660, -1264, 1608, 1024, 1, -5, -35, 170, 775,
    -2941, -9385, 23880, 45620, -58080, -36976, 1, -6, -51, 310,
    1815, -9186, -41033, 156618, 498660, -1269720, -2425056, 3087648]

/-- `flat` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq (n : flatArgType) (h : n < 48) : flat n = flatData[n]! := sorry

/-- `flatFn` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fn (n : Nat) (h : n < 48) : flatFn n = flatData[n]! := sorry

/-- `flatFz` agrees with `flatData` on the known range. -/
@[simp]
theorem flat_data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 48) : flatFz n = flatData[n.toNat]! := sorry

end A213736
