import LOEIS.A150.A150722.Defs

set_option linter.unusedVariables false

/-!
# A150722

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, -1, 0), (-1, 0, 0), (1, 0, -1), (1, 0, 1), (1, 1, 0)}.

The 28 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A150722

/-- Known terms of `A150722`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 8, 28, 120, 487, 2164, 9332, 42459, 189347,
    875147, 3987803, 18636188, 86192575, 406149540, 1898912298, 9005660987, 42453474667, 202375900257, 960205508652,
    4596633770293, 21923165079461, 105318991555772, 504456145736517, 2430647938121871, 11683853096762053, 56441336631484042, 272127022704314869]

/-- `A150722` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 28) : A150722 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 28) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 28) : fz n = data[n.toNat]! := sorry

end A150722
