import LOEIS.A310.A310571.Defs

set_option linter.unusedVariables false

/-!
# A310571

Coordination sequence Gal.6.111.2 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.

The 50 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A310571

/-- Known terms of `A310571`, starting at index `0`. -/
def data : List retType :=
  [1, 4, 5, 6, 12, 15, 19, 19, 20, 32,
    29, 26, 34, 40, 43, 44, 43, 51, 58, 52,
    56, 58, 65, 72, 68, 70, 76, 82, 86, 81,
    79, 97, 98, 93, 96, 95, 113, 119, 100, 106,
    126, 126, 123, 113, 120, 149, 139, 122, 138, 152]

/-- `A310571` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 50) : A310571 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 50) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 50) : fz n = data[n.toNat]! := sorry

end A310571
