import LOEIS.A300.A300016.Defs

set_option linter.unusedVariables false

/-!
# A300016

For any k, the cumulative sum a(1) + a(2) + a(3) + ... + a(k) shows at least a digit 2.

The 75 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A300016

/-- Known terms of `A300016`, starting at index `1`. -/
def data : List retType :=
  [2, 10, 8, 1, 3, 4, 14, 20, 30, 28,
    5, 7, 40, 29, 6, 9, 11, 12, 13, 15,
    16, 19, 18, 22, 50, 31, 39, 58, 32, 60,
    17, 23, 68, 42, 59, 21, 70, 80, 33, 27,
    69, 41, 38, 24, 25, 26, 37, 90, 100, 110,
    108, 52, 48, 62, 43, 47, 34, 35, 36, 44,
    45, 46, 49, 51, 53, 54, 55, 56, 57, 61,
    63, 64, 65, 66, 67]

/-- `A300016` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 76) : A300016 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 76) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 76) : fz n = data[n.toNat - 1]! := sorry

end A300016
