import LOEIS.A282.A282608.Defs

set_option linter.unusedVariables false

/-!
# A282608

Decimal representation of the x-axis, from the left edge to the origin, of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 489", based on the 5-celled von Neumann neighborhood.

The 34 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A282608

/-- Known terms of `A282608`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 7, 4, 27, 30, 115, 90, 441, 488,
    1849, 1448, 7065, 7832, 29593, 23192, 113049, 125336, 473497, 371096,
    1808793, 2005400, 7575961, 5937560, 28940697, 32086424, 121215385, 95000984, 463051161, 513382808,
    1939446169, 1520015768, 7408818585, 8214124952]

/-- `A282608` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 34) : A282608 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 34) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 34) : fz n = data[n.toNat]! := sorry

end A282608
