import Mathlib.Tactic
import Mathlib.Data.PNat.Defs

set_option linter.unusedVariables false

/-!
# A106385

Consider the Gaussian primes of the first quadrant a+bi, with a>0, b>=0, ordered as a sequence by the size of the norm and the size of a, as defined in A103431. The sum of these primes up to a+bi is divisible by a+bi. a(n) is the real part a of such a+bi.

OEIS offset `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A106385

/-- Index type of `A106385` (OEIS offset `1`). -/
abbrev argType : Type := PNat

/-- Value type of `A106385`. -/
abbrev retType : Type := Nat

/-- OEIS offset: the index of the first known term. -/
abbrev offset : Int := 1

end A106385

/-- Consider the Gaussian primes of the first quadrant a+bi, with a>0, b>=0, ordered as a sequence by the size of the norm and the size of a, as defined in A103431. The sum of these primes up to a+bi is divisible by a+bi. a(n) is the real part a of such a+bi. -/
def A106385 : A106385.argType → A106385.retType := sorry

namespace A106385

/-- Relation that defines `A106385`. -/
def prop : argType → retType → Prop := sorry

/-- `A106385` as a total function on `Nat`; junk value outside the domain. -/
def fn : Nat → retType := sorry

/-- `A106385` as a total function on `Int`; junk value outside the domain.
Always used when composing sequences. -/
def fz : Int → retType := sorry

/-- The main definition satisfies its defining relation. -/
theorem prop_correct (n : argType) : prop n (A106385 n) := sorry

/-- `fn` agrees with the main definition. -/
theorem fn_eq (n : Nat) (h : 0 < n) : fn n = A106385 ⟨n, h⟩ := sorry

/-- `fz` agrees with the main definition on the domain. -/
theorem fz_eq (n : Int) (h : 1 ≤ n) : fz n = A106385 ⟨n.toNat, by omega⟩ := sorry

/-- `fn` and `fz` agree on the overlapping domain. -/
theorem fn_eq_fz (n : Nat) (h : 0 < n) : fn n = fz (n : Int) := sorry

end A106385
