import LOEIS.A182.A182189.Defs

set_option linter.unusedVariables false

/-!
# A182189

a(n) = 6*a(n-1) - a(n-2) - 4 with n > 1, a(0)=1, a(1)=3.

The 24 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A182189

/-- Known terms of `A182189`, starting at index `0`. -/
def data : List retType :=
  [1, 3, 13, 71, 409, 2379, 13861, 80783, 470833, 2744211,
    15994429, 93222359, 543339721, 3166815963, 18457556053, 107578520351, 627013566049, 3654502875939, 21300003689581, 124145519261543,
    723573111879673, 4217293152016491, 24580185800219269, 143263821649299119]

/-- `A182189` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 24) : A182189 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 24) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 24) : fz n = data[n.toNat]! := sorry

end A182189
