import LOEIS.A253.A253469.Defs

set_option linter.unusedVariables false

/-!
# A253469

Number of (n+1) X (7+1) 0..2 arrays with every 2 X 2 subblock diagonal maximum minus antidiagonal minimum unequal to its neighbors horizontally, vertically, diagonally and antidiagonally.

The 25 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A253469

/-- Known terms of `A253469`, starting at index `1`. -/
def data : List retType :=
  [7227096, 44464, 17000, 15680, 20000, 20864, 32000, 41600, 80000, 124544,
    272000, 456320, 1040000, 1783424, 4112000, 7091840, 16400000, 28325504, 65552000, 113260160,
    262160000, 452998784, 1048592000, 1811953280, 4194320000]

/-- `A253469` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 26) : A253469 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 26) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 26) : fz n = data[n.toNat - 1]! := sorry

end A253469
