import LOEIS.A346.A346227.Defs

set_option linter.unusedVariables false

/-!
# A346227

Number of n-step 6-dimensional nonnegative lattice walks starting at the origin and using steps that increment all components or decrement one component by 1.

The 24 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A346227

/-- Known terms of `A346227`, starting at index `0`. -/
def data : List retType :=
  [1, 1, 7, 43, 241, 1315, 7525, 46165, 292015, 1839901,
    11536747, 72847417, 466127719, 3018752041, 19678318207, 128531220955, 840554295625, 5513681844355, 36333611660245, 240480114800023,
    1596692607223561, 10621894482682471, 70761572688601777, 472172623607888563]

/-- `A346227` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 24) : A346227 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 24) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 24) : fz n = data[n.toNat]! := sorry

end A346227
