import LOEIS.A274.A274875.Defs

set_option linter.unusedVariables false

/-!
# A274875

Number of set partitions of [2n] into exactly n blocks such that all odd elements are in blocks with an odd index and all even elements are in blocks with an even index.

The 21 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A274875

/-- Known terms of `A274875`, starting at index `0`. -/
def data : List retType :=
  [1, 0, 1, 3, 35, 226, 3632, 36780, 770481, 10677444,
    277114769, 4882093495, 151410615066, 3238949008872, 116936529884088, 2943848265346408, 121318690777898613, 3513774792447267240, 162794429514873454259, 5332375501915984656921,
    274393112247007415104839]

/-- `A274875` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 21) : A274875 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 21) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 21) : fz n = data[n.toNat]! := sorry

end A274875
