import LOEIS.A293.A293338.Defs

set_option linter.unusedVariables false

/-!
# A293338

The integer k that minimizes |k/2^n - e|.

The 33 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A293338

/-- Known terms of `A293338`, starting at index `0`. -/
def data : List retType :=
  [3, 5, 11, 22, 43, 87, 174, 348, 696, 1392,
    2784, 5567, 11134, 22268, 44536, 89073, 178145, 356291, 712581, 1425163,
    2850325, 5700650, 11401300, 22802601, 45605201, 91210403, 182420806, 364841611, 729683222, 1459366444,
    2918732889, 5837465777, 11674931555]

/-- `A293338` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 33) : A293338 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 33) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 33) : fz n = data[n.toNat]! := sorry

end A293338
