import LOEIS.A383.A383357.Defs

set_option linter.unusedVariables false

/-!
# A383357

Integers m such that R(Sum_{k=1..m} (10^k+k)) is prime, where R is the digit reversal function A004086.

The 13 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A383357

/-- Known terms of `A383357`, starting at index `1`. -/
def data : List retType :=
  [1, 2, 4, 20, 34, 35, 77, 158, 181, 401,
    973, 3517, 6818]

/-- `A383357` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 14) : A383357 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 14) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 14) : fz n = data[n.toNat - 1]! := sorry

end A383357
