import LOEIS.A319.A319627.Defs

set_option linter.unusedVariables false

/-!
# A319627

Primorial deflation of n (denominator): Let f be the completely multiplicative function over the positive rational numbers defined by f(p) = A034386(p) for any prime number p; f constitutes a permutation of the positive rational numbers; let g be the inverse of f; for any n > 0, a(n) is the denominator of g(n).

The 75 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A319627

/-- Known terms of `A319627`, starting at index `1`. -/
def data : List retType :=
  [1, 1, 2, 1, 3, 1, 5, 1, 4, 3,
    7, 1, 11, 5, 2, 1, 13, 2, 17, 3,
    10, 7, 19, 1, 9, 11, 8, 5, 23, 1,
    29, 1, 14, 13, 3, 1, 31, 17, 22, 3,
    37, 5, 41, 7, 4, 19, 43, 1, 25, 9,
    26, 11, 47, 4, 21, 5, 34, 23, 53, 1,
    59, 29, 20, 1, 33, 7, 61, 13, 38, 3,
    67, 1, 71, 31, 6]

/-- `A319627` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 76) : A319627 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 76) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 76) : fz n = data[n.toNat - 1]! := sorry

end A319627
