import LOEIS.A219.A219933.Defs

set_option linter.unusedVariables false

/-!
# A219933

Number of nX2 arrays of the minimum value of corresponding elements and their horizontal or diagonal neighbors in a random, but sorted with lexicographically nondecreasing rows and nonincreasing columns, 0..3 nX2 array.

The 31 terms known to OEIS, indexed from `1`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A219933

/-- Known terms of `A219933`, starting at index `1`. -/
def data : List retType :=
  [4, 23, 76, 208, 519, 1212, 2670, 5574, 11076, 21043,
    38390, 67522, 114907, 189804, 305172, 478788, 734604, 1104375, 1629592, 2363756,
    3375031, 4749316, 6593778, 9040890, 12253020, 16427619, 21803058, 28665166, 37354523, 48274564,
    61900552]

/-- `A219933` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n.val < 32) : A219933 n = data[n.val - 1]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h0 : 0 < n) (h : n < 32) : fn n = data[n - 1]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 1 ≤ n) (h : n < 32) : fz n = data[n.toNat - 1]! := sorry

end A219933
