import LOEIS.A150.A150574.Defs

set_option linter.unusedVariables false

/-!
# A150574

Number of walks within N^3 (the first octant of Z^3) starting at (0,0,0) and consisting of n steps taken from {(-1, 0, 1), (0, -1, 1), (0, 1, -1), (0, 1, 1), (1, 0, 0)}.

The 27 terms known to OEIS, indexed from `0`.

Skeleton generated by `lake exe oeis-gen`; every declaration is a `sorry` placeholder.
-/

namespace A150574

/-- Known terms of `A150574`, starting at index `0`. -/
def data : List retType :=
  [1, 2, 7, 26, 108, 460, 2040, 9160, 41992, 193966,
    907142, 4263879, 20204144, 96076478, 459418961, 2202642718, 10602765149, 51141494983, 247415643188, 1198881420190,
    5822704304805, 28316263718875, 137954149322970, 672818284714096, 3286202581072715, 16064975889588637, 78629304225011383]

/-- `A150574` agrees with `data` on the known range. -/
@[simp]
theorem data_eq (n : argType) (h : n < 27) : A150574 n = data[n]! := sorry

/-- `fn` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fn (n : Nat) (h : n < 27) : fn n = data[n]! := sorry

/-- `fz` agrees with `data` on the known range. -/
@[simp]
theorem data_eq_fz (n : Int) (h0 : 0 ≤ n) (h : n < 27) : fz n = data[n.toNat]! := sorry

end A150574
